Repository GoogleCloudPlatform/guest-test-infra, pull requests merged in 2019-11, with the labels that each got.

#14 New package build tooling
  container_images/daisy-builder/main.sh
  packagebuild/common.sh
  packagebuild/daisy_startupscript_deb.sh
  packagebuild/daisy_startupscript_goo.sh
  packagebuild/daisy_startupscript_rpm.sh
  packagebuild/workflows/build_deb10.wf.json
  packagebuild/workflows/build_deb9.wf.json
  packagebuild/workflows/build_el6.wf.json
  packagebuild/workflows/build_el7.wf.json
  packagebuild/workflows/build_el8.wf.json
  packagebuild/workflows/build_goo.wf.json
  packagebuild/workflows/build_package.wf.json
Labels: approved, cla: yes, lgtm, size/XL

#15 Add tagging to postsubmit jobs
  container_images/autoversioner/Dockerfile
  container_images/daisy-builder/main.sh
Labels: approved, cla: yes, lgtm, size/M

#16 verbose gotest
  container_images/gotest/main.sh
Labels: approved, cla: yes, lgtm, size/XS
