Repository GoogleCloudPlatform/guest-test-infra, pull requests merged in 2020-12, with the labels that each got.

#43 Removing CentOS6 and RHEL6 from integration tests
  container_images/gointegtest/integ-test-all.wf.json
Labels: approved, cla: yes, lgtm, size/M

#42 image build and release concourse pipeline (centos, rhel, debian, build, publish-to-test, publish-to-staging, publish-to-prod)
  concourse/README.md
  concourse/pipeline/linux-image-build.yaml
  concourse/tasks/daisy-build-images-debian.yaml
  concourse/tasks/daisy-build-images.yaml
  concourse/tasks/daisy-publish-images.yaml
  concourse/tasks/generate-build-id.yaml
  concourse/tasks/generate-version.yaml
  concourse/tasks/get-credential.yaml
  concourse/tasks/gsutil-ls.yaml
Labels: approved, cla: yes, lgtm, size/XXL

#44 fix regexp in resource, use underscore in 'gcs_url' and 'build_date'
  concourse/pipeline/linux-image-build.yaml
Labels: approved, cla: yes, lgtm, size/L

#45 fix invalid underscores in load_var vars
  concourse/pipeline/linux-image-build.yaml
Labels: approved, cla: yes, lgtm, size/M

#46 more underscore fixes
  concourse/pipeline/linux-image-build.yaml
  concourse/tasks/daisy-build-images-debian.yaml
  concourse/tasks/daisy-build-images.yaml
Labels: approved, cla: yes, lgtm, size/M

#47 add pipeline-set-pipeline
  concourse/pipeline/pipeline-set-pipeline.yaml
Labels: approved, cla: yes, lgtm, size/S

#48 rename pipeline dir to pipelines
  concourse/pipelines/linux-image-build.yaml
  concourse/pipelines/pipeline-set-pipeline.yaml
Labels: approved, cla: yes, lgtm, size/XS
