Repository GoogleCloudPlatform/guest-test-infra, pull requests merged in 2020-10, with the labels that each got.

#37 Add integ test runner
  container_images/cloudbuild.yaml
  container_images/gointegtest/Dockerfile
  container_images/gointegtest/common.sh
  container_images/gointegtest/integ-test-all.wf.json
  container_images/gointegtest/main.sh
  container_images/gointegtest/run_integ_tests.sh
Labels: approved, cla: yes, lgtm, size/XL

#38 small fixes for gointegtest
  container_images/cloudbuild.yaml
  container_images/gointegtest/run_integ_tests.sh
Labels: approved, cla: yes, lgtm, size/XS

#39 pytest: allow in-repo dependencies
  container_images/pytest/.dockerignore
  container_images/pytest/Dockerfile
  container_images/pytest/README.md
  container_images/pytest/example/.gitignore
  container_images/pytest/example/README.md
  container_images/pytest/example/run.sh
  container_images/pytest/example/src/application/main.py
  container_images/pytest/example/src/application/main_test.py
  container_images/pytest/example/src/application/pyproject.toml
  container_images/pytest/example/src/application/setup.py
  container_images/pytest/example/src/sums/ints.py
  container_images/pytest/example/src/sums/setup.py
  container_images/pytest/main.py
Labels: approved, cla: yes, lgtm, size/L
