Repository GoogleCloudPlatform/guest-test-infra, pull requests merged in 2020-05, with the labels that each got.

#27 add flake8 runner
  container_images/cloudbuild.yaml
  container_images/flake8/Dockerfile
  container_images/flake8/main.sh
Labels: approved, cla: yes, lgtm, size/M

#28 update dockerfile
  container_images/flake8/Dockerfile
Labels: approved, cla: yes, lgtm, size/S

#29 update IUS RPM URL
  packagebuild/daisy_startupscript_rpm.sh
Labels: approved, cla: yes, lgtm, size/XS

#30 use git224 instead of git2u on EL builds
  packagebuild/daisy_startupscript_rpm.sh
Labels: approved, cla: yes, lgtm, size/XS

#31 Remove @rofuentes from reviewers list
  OWNERS
Labels: approved, cla: yes, lgtm, size/XS
