Repository GoogleCloudPlatform/guest-test-infra, pull requests merged in 2021-09, with the labels that each got.

#224 Fix generate timestamp by using bash image instead of busybox's date
  concourse/tasks/generate-timestamp.yaml
Labels: size/XS, lgtm, approved, cla: yes

#225 Add cli tool for publishing a cloud monitoring time series data point
  container_images/concourse-metrics/cmd/publish-job-result/main.go
  container_images/concourse-metrics/pkg/requests/requests.go
  container_images/concourse-metrics/pkg/requests/requests_test.go
  go.mod
  go.sum
Labels: size/L, lgtm, approved, cla: yes

#227 Create Dockerfile and Cloud Build config for the concourse-metrics image
  container_images/cloudbuild.yaml
  container_images/concourse-metrics/Dockerfile
Labels: lgtm, approved, cla: yes, size/S

#226 skip network test in package testing
  concourse/pipelines/guest-package-build.yaml
  concourse/tasks/image-test-args.yaml
Labels: lgtm, approved, cla: yes, size/S

#229 Add concourse-metrics to the images list in cloudbuild configuration
  container_images/cloudbuild.yaml
Labels: size/XS, lgtm, approved, cla: yes

#230 Add CA certs from base golang image for metric publishing image
  container_images/concourse-metrics/Dockerfile
Labels: size/XS, lgtm, approved, cla: yes

#231 Update owners file to include linskeyd
  OWNERS
Labels: size/XS, lgtm, approved, cla: yes

#232 build linux images daily
  concourse/pipelines/linux-image-build.yaml
Labels: lgtm, approved, size/M, cla: yes

#233 fix package generation task
  concourse/tasks/generate-package-version.yaml
Labels: lgtm, approved, cla: yes, size/S

#228 Add publish-job-result Concourse task
  concourse/tasks/publish-job-result.yaml
Labels: lgtm, approved, cla: yes, size/S

#236 lock go version
  container_images/gocheck/Dockerfile
Labels: size/XS, lgtm, approved, cla: yes

#237 Pin gobuild and gotest containers to 1.13.15
  container_images/gobuild/Dockerfile
  container_images/gotest/Dockerfile
Labels: size/XS, lgtm, approved, cla: yes

#238 Instrument the dev-image-build pipeline with success/failure/duration metrics
  concourse/pipelines/dev-image-build.yaml
  concourse/tasks/publish-job-result.yaml
Labels: size/L, lgtm, approved, cla: yes
