Repository GoogleCloudPlatform/guest-test-infra, pull requests merged in 2021-03, with the labels that each got.

#68 Change testing machine to use e2-standard-2 and add centos-stream-8.
  container_images/gointegtest/integ-test-all.wf.json
  packagebuild/workflows/build_package.wf.json
Labels: approved, cla: yes, lgtm, size/M

#72 fix typo in output path
  concourse/pipelines/guest-package-build.yaml
Labels: approved, cla: yes, lgtm, size/XS

#74 new package build workflow
  concourse/pipelines/guest-package-build.yaml
  concourse/tasks/gcloud-inject-package.yaml
  concourse/tasks/generate-package-version.yaml
Labels: approved, cla: yes, lgtm, size/XL

#76 correct package version generation
  concourse/tasks/generate-package-version.yaml
Labels: approved, cla: yes, lgtm, size/XS

#75 Change prod publish dependency to only require publish-to-testing.
  concourse/pipelines/linux-image-build.yaml
Labels: approved, cla: yes, lgtm, size/S

#77 correct guest-test-infra url in pkgbuild pipeline
  concourse/pipelines/guest-package-build.yaml
Labels: approved, cla: yes, lgtm, size/XS

#78 correct task for injecting package
  concourse/pipelines/guest-package-build.yaml
Labels: approved, cla: yes, lgtm, size/S

#79 use alpine variant for package injector
  concourse/pipelines/guest-package-build.yaml
  concourse/tasks/gcloud-inject-package.yaml
Labels: approved, cla: yes, lgtm, size/XS

#71 AlmaLinux build.
  concourse/pipelines/linux-image-build.yaml
Labels: approved, cla: yes, lgtm, size/L

#82 Debian 11 bullseye package builds.
  concourse/pipelines/guest-package-build.yaml
  packagebuild/workflows/build_deb11.wf.json
Labels: approved, cla: yes, lgtm, size/M

#83 correct partial yaml
  concourse/pipelines/linux-image-build.yaml
Labels: approved, cla: yes, lgtm, size/S

#85 rollback #82
  concourse/pipelines/guest-package-build.yaml
Labels: approved, cla: yes, lgtm, size/S

#86 guest-package-build bugfixes
  concourse/pipelines/guest-package-build.yaml
  concourse/tasks/gcloud-inject-package.yaml
  concourse/tasks/generate-package-version.yaml
Labels: approved, cla: yes, lgtm, size/S

#87 split linux build by distros
  concourse/pipelines/linux-image-build-centos.yaml
  concourse/pipelines/linux-image-build-debian.yaml
  concourse/pipelines/linux-image-build-rhel.yaml
  concourse/pipelines/pipeline-set-pipeline.yaml
Labels: approved, cla: yes, lgtm, size/XXL

#88 Move almalinux to its own pipeline.
  concourse/pipelines/linux-image-build-almalinux.yaml
  concourse/pipelines/linux-image-build-rhel.yaml
  concourse/pipelines/pipeline-set-pipeline.yaml
Labels: approved, cla: yes, lgtm, size/L

#89 Package builds for Debian 11
  concourse/pipelines/guest-package-build.yaml
  packagebuild/daisy_startupscript_deb.sh
Labels: approved, cla: yes, lgtm, size/S
