Repository GoogleCloudPlatform/guest-test-infra, pull requests merged in 2021-06, with the labels that each got.

#132 add security image test
  go.mod
  go.sum
  imagetest/cmd/manager/main.go
  imagetest/test_suites/security/image_security_test.go
  imagetest/test_suites/security/setup.go
Labels: approved, cla: yes, lgtm, size/L

#153 per release repos for guest agent
  concourse/pipelines/guest-package-build.yaml
Labels: approved, cla: yes, lgtm, size/S

#154 Move rhel metal dev build/publish to bare metal pipeline.
  concourse/pipelines/bare-metal-image-build.yaml
  concourse/pipelines/dev-image-build.yaml
Labels: approved, cla: yes, lgtm, size/L

#155 Fix typo.
  concourse/pipelines/bare-metal-image-build.yaml
Labels: approved, cla: yes, lgtm, size/XS

#151 add disk resize test
  imagetest/cmd/manager/main.go
  imagetest/fixtures.go
  imagetest/test_suites/disk/disk_resize_test.go
  imagetest/test_suites/disk/setup.go
  imagetest/testworkflow.go
Labels: approved, cla: yes, lgtm, size/L

#157 Image test unit test
  imagetest/testworkflow_test.go
Labels: approved, cla: yes, lgtm, size/M

#158 Add staging/oslogin staging publish tasks.
  concourse/pipelines/linux-image-build.yaml
  concourse/pipelines/partner-image-export.yaml
Labels: approved, cla: yes, lgtm, size/XXL

#159 Run image test on correct image and publish to testing on build.
  concourse/pipelines/linux-image-build.yaml
Labels: approved, cla: yes, lgtm, size/M

#160 Fix debian image references for tests.
  concourse/pipelines/linux-image-build.yaml
Labels: approved, cla: yes, lgtm, size/XS

#161 Adding myself and Lawrence to the owners file
  OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#152 add shutdown script test
  imagetest/test_suites/image_boot/setup.go
  imagetest/test_suites/image_boot/shutdown_test.go
Labels: approved, cla: yes, lgtm, size/M

#156 Adding Windows Server image builds
  concourse/pipelines/pipeline-set-pipeline.yaml
  concourse/pipelines/windows-image-build.yaml
  concourse/tasks/daisy-build-images-windows.yaml
Labels: approved, cla: yes, lgtm, size/XXL

#162 Fix several image tests.
  imagetest/test_suites/disk/disk_resize_test.go
  imagetest/test_suites/image_boot/image_boot_test.go
  imagetest/test_suites/image_validation/license_test.go
  imagetest/test_suites/network/mtu_test.go
  imagetest/test_suites/security/image_security_test.go
Labels: approved, cla: yes, lgtm, size/M

#164 Adding a second build-id variable for internal builds
  concourse/pipelines/windows-image-build.yaml
  concourse/tasks/generate-build-ids-windows.yaml
Labels: approved, cla: yes, lgtm, size/M

#165 Skip secure boot tests for Debian 9.
  imagetest/test_suites/image_boot/setup.go
  imagetest/test_suites/security/image_security_test.go
Labels: approved, cla: yes, lgtm, size/S

#167 increase timeout
  imagetest/cmd/manager/main.go
  imagetest/testworkflow.go
  imagetest/testworkflow_test.go
Labels: approved, cla: yes, lgtm, size/M

#166 Show failing licenses
  imagetest/test_suites/image_validation/license_test.go
  imagetest/test_suites/security/image_security_test.go
Labels: approved, cla: yes, lgtm, size/S

#168 Updating syntax so both commands run
  concourse/tasks/generate-build-ids-windows.yaml
Labels: approved, cla: yes, lgtm, size/XS

#169 Updating to a single line command
  concourse/tasks/generate-build-ids-windows.yaml
Labels: approved, cla: yes, lgtm, size/XS

#170 Fixing typo
  concourse/pipelines/windows-image-build.yaml
  concourse/tasks/daisy-build-images-windows.yaml
Labels: approved, cla: yes, lgtm, size/S

#171 promote oslogin
  concourse/pipelines/guest-package-build.yaml
Labels: approved, cla: yes, lgtm, size/M

#173 fix rhel 7.4 sap
  imagetest/test_suites/image_validation/image_validation_test.go
Labels: approved, cla: yes, lgtm, size/XS

#172 Skip secure boot test on Rocky Linux which doesn't yet support it.
  imagetest/test_suites/image_boot/image_boot_test.go
Labels: approved, cla: yes, lgtm, size/XS

#174 strip comments when checking sshd_config
  imagetest/test_suites/security/image_security_test.go
Labels: approved, cla: yes, lgtm, size/S
