Repository GoogleCloudPlatform/guest-test-infra, pull requests merged in 2021-07, with the labels that each got.

#175 add promotions for gce package
  concourse/pipelines/guest-package-build.yaml
Labels: approved, cla: yes, lgtm, size/M

#176 add oslogin staging promotion
  concourse/pipelines/guest-package-build.yaml
Labels: approved, cla: yes, lgtm, size/M

#182 Switch to modern efivars file.
  imagetest/test_suites/image_boot/image_boot_test.go
Labels: approved, cla: yes, lgtm, size/XS

#181 Fix test flakes for Debian and Rocky Linux
  imagetest/cmd/wrapper/main.go
  imagetest/test_suites/image_boot/setup.go
Labels: approved, cla: yes, lgtm, size/S

#184 correct path for package injection
  concourse/pipelines/guest-package-build.yaml
Labels: approved, cla: yes, lgtm, size/XS

#150 add test for alias ip
  imagetest/fixtures.go
  imagetest/test_suites/network/alias_ip_test.go
  imagetest/test_suites/network/setup.go
  imagetest/testworkflow.go
Labels: approved, cla: yes, lgtm, size/L

#186 Add RHEL 8.4 for SAP build.
  concourse/pipelines/linux-image-build.yaml
Labels: approved, cla: yes, lgtm, size/L

#188 add AR promotions
  concourse/pipelines/guest-package-build.yaml
Labels: approved, cla: yes, lgtm, size/M

#187 CIT fixups
  go.mod
  imagetest/fixtures.go
  imagetest/fixtures_test.go
  imagetest/test_suites/disk/setup.go
  imagetest/test_suites/network/setup.go
  imagetest/testworkflow.go
  imagetest/testworkflow_test.go
Labels: approved, cla: yes, lgtm, size/XL

#178 add ssh test
  go.mod
  go.sum
  imagetest/cmd/manager/main.go
  imagetest/fixtures.go
  imagetest/fixtures_test.go
  imagetest/test_suites/ssh/image_ssh_test.go
  imagetest/test_suites/ssh/setup.go
  imagetest/testworkflow.go
  imagetest/utils/test_utils.go
Labels: approved, cla: yes, lgtm, size/L

#192 CIT: listening socket test
  imagetest/test_suites/security/image_security_test.go
Labels: approved, cla: yes, lgtm, size/M

#194 use constraint for CIT
  imagetest/Dockerfile
  imagetest/README.md
  imagetest/cmd/wrapper/main.go
  imagetest/file
  imagetest/test_suites/disk/disk_resize_test.go
  imagetest/test_suites/image_boot/image_boot_test.go
  imagetest/test_suites/image_boot/shutdown_test.go
  imagetest/test_suites/image_validation/clock_test.go
  imagetest/test_suites/image_validation/image_validation_test.go
  imagetest/test_suites/image_validation/license_test.go
  imagetest/test_suites/image_validation/linux_license_test.go
  imagetest/test_suites/image_validation/package_test.go
  imagetest/test_suites/network/alias_ip_test.go
  imagetest/test_suites/network/mtu_test.go
  imagetest/test_suites/security/image_security_test.go
  imagetest/test_suites/ssh/image_ssh_test.go
Labels: approved, cla: yes, lgtm, size/L

#195 add image boot time test
  imagetest/test_suites/image_boot/image_boot_test.go
  imagetest/test_suites/image_boot/setup.go
Labels: approved, cla: yes, lgtm, size/S

#196 add metadata test
  imagetest/cmd/manager/main.go
  imagetest/test_suites/metadata/metadata_test.go
  imagetest/test_suites/metadata/setup.go
Labels: approved, cla: yes, lgtm, size/M

#191 add reboot on host test
  imagetest/test_suites/image_boot/image_boot_test.go
  imagetest/test_suites/image_boot/setup.go
Labels: approved, cla: yes, lgtm, size/M

#190 add local user check
  imagetest/test_suites/ssh/image_ssh_test.go
Labels: approved, cla: yes, lgtm, size/M

#177 add host key test
  imagetest/cmd/manager/main.go
  imagetest/test_suites/hostkey/hostkey_pubish_test.go
  imagetest/test_suites/hostkey/setup.go
  imagetest/utils/test_utils.go
Labels: approved, cla: yes, lgtm, size/M

#200 build imagetest container on commit
  concourse/pipelines/linux-image-build.yaml
Labels: approved, cla: yes, lgtm, size/S

#197 Image test medadata 2
  imagetest/test_suites/metadata/metadata_test.go
  imagetest/utils/test_utils.go
Labels: approved, cla: yes, lgtm, size/M

#201 add ssh-keygen to CIT image
  imagetest/Dockerfile
Labels: approved, cla: yes, lgtm, size/XS

#203 disable oslogin in ssh test
  imagetest/test_suites/ssh/setup.go
Labels: approved, cla: yes, lgtm, size/XS

#202 update trigger for imagetest
  concourse/pipelines/linux-image-build.yaml
Labels: approved, cla: yes, lgtm, size/XS
