Repository GoogleCloudPlatform/guest-test-infra, pull requests merged in 2021-04, with the labels that each got.

#90 Rollback 87
  concourse/pipelines/linux-image-build.yaml
  concourse/pipelines/pipeline-set-pipeline.yaml
Labels: approved, cla: yes, lgtm, size/XXL

#91 add groups to image build
  concourse/pipelines/linux-image-build.yaml
Labels: approved, cla: yes, lgtm, size/M

#93 Add Debian 11 build to image builds.
  concourse/pipelines/linux-image-build.yaml
Labels: approved, cla: yes, lgtm, size/L

#81 Test manager container
  concourse/pipelines/linux-image-build-almalinux.yaml
  concourse/pipelines/linux-image-build-centos.yaml
  concourse/pipelines/linux-image-build-debian.yaml
  concourse/pipelines/linux-image-build-rhel.yaml
  concourse/pipelines/linux-image-build.yaml
  concourse/tasks/build-container-image.yaml
  container_images/test-manager/Dockerfile
  container_images/test-manager/build.sh
Labels: approved, cla: yes, lgtm, size/XXL

#95 add fly-validate-pipelines image
  container_images/cloudbuild.yaml
  container_images/fly-validate-pipelines/Dockerfile
  container_images/fly-validate-pipelines/main.sh
Labels: approved, cla: yes, lgtm, size/M

#96 test wrapper fixes
  test_manager/test_wrapper/test_wrapper.go
  test_manager/utils/test_utils.go
Labels: approved, cla: yes, lgtm, size/L

#102 add eric to OWNERS
  imagetest/OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#99 test wrapper: upload test result as text
  imagetest/cmd/wrapper/main.go
  imagetest/utils/test_utils.go
Labels: approved, cla: yes, lgtm, size/M

#104 add group for dev linux pipeline
  concourse/pipelines/dev-image-build.yaml
Labels: approved, cla: yes, lgtm, size/S

#98 imagetest package
  imagetest/junit.go
  imagetest/junit_test.go
  imagetest/testworkflow.go
  imagetest/testworkflow_test.go
Labels: approved, cla: yes, lgtm, size/XL

#100 add test fixtures
  imagetest/fixtures.go
  imagetest/testworkflow.go
  imagetest/testworkflow_test.go
Labels: approved, cla: yes, lgtm, size/XL

#105 correct package path for oslogin
  concourse/pipelines/guest-package-build.yaml
Labels: approved, cla: yes, lgtm, size/S

#101 add test manager binary
  imagetest/cmd/manager/main.go
  imagetest/test_suites/image_validation/image_validation_test.go
  imagetest/test_suites/image_validation/setup.go
Labels: approved, cla: yes, lgtm, size/L

#106 add custom hostname test
  imagetest/test_suites/image_validation/image_validation_test.go
  imagetest/test_suites/image_validation/setup.go
  imagetest/testworkflow.go
  imagetest/testworkflow_test.go
Labels: approved, cla: yes, lgtm, size/M

#103 update cloud-image-tests container
  container_images/cloud-image-tests/Dockerfile
  container_images/cloud-image-tests/build.sh
Labels: approved, cla: yes, lgtm, size/M

#111 update cloud image test dockerfile
  concourse/pipelines/linux-image-build.yaml
  container_images/cloud-image-tests/build.sh
  imagetest/Dockerfile
Labels: approved, cla: yes, lgtm, size/M

#112 imagetest: add readme
  imagetest/README.md
Labels: approved, cla: yes, lgtm, size/M

#113 fix folder path in docker
  imagetest/Dockerfile
Labels: approved, cla: yes, lgtm, size/XS

#114 create per-project output bucket
  imagetest/cmd/manager/main.go
  imagetest/testworkflow.go
Labels: approved, cla: yes, lgtm, size/M

#108 Image test boot
  go.mod
  go.sum
  imagetest/cmd/manager/main.go
  imagetest/test_suites/image_boot/image_boot_test.go
  imagetest/test_suites/image_boot/setup.go
Labels: approved, cla: yes, lgtm, size/L

#115 Partner images export pipelines.
  concourse/pipelines/partner-image-export.yaml
  concourse/pipelines/pipeline-set-pipeline.yaml
  concourse/tasks/daisy-export-images-partner.yaml
Labels: approved, cla: yes, lgtm, size/XXL

#116 Fix staging variable
  concourse/pipelines/partner-image-export.yaml
Labels: approved, cla: yes, lgtm, size/S

#117 Fix gcs url vars.
  concourse/pipelines/partner-image-export.yaml
Labels: approved, cla: yes, lgtm, size/S

#118 Fix Ubuntu vars.
  concourse/pipelines/partner-image-export.yaml
Labels: approved, cla: yes, lgtm, size/S

#119 Fix a couple pipeline bugs.
  concourse/pipelines/linux-image-build.yaml
  concourse/pipelines/partner-image-export.yaml
Labels: approved, cla: yes, lgtm, size/S

#122 update imagetest readme
  imagetest/README.md
Labels: approved, cla: yes, lgtm, size/M

#107 add image license test
  go.mod
  go.sum
  imagetest/test_suites/image_validation/license_test.go
  imagetest/test_suites/image_validation/setup.go
Labels: approved, cla: yes, lgtm, size/L

#124 fix imagetest binary path
  imagetest/testworkflow.go
Labels: approved, cla: yes, size/XS

#120 add secureboot test
  imagetest/fixtures.go
  imagetest/test_suites/image_boot/image_boot_test.go
  imagetest/test_suites/image_boot/setup.go
Labels: approved, cla: yes, lgtm, size/M

#123 Image test mtu
  imagetest/cmd/manager/main.go
  imagetest/test_suites/network/mtu_test.go
  imagetest/test_suites/network/setup.go
Labels: approved, cla: yes, lgtm, size/M
