Repository GoogleCloudPlatform/guest-test-infra, pull requests merged in 2021-05, with the labels that each got.

#128 Add Rocky Linux 8 build
  concourse/pipelines/linux-image-build.yaml
Labels: approved, cla: yes, lgtm, size/L

#126 add test gcloud gsutil
  imagetest/test_suites/image_validation/package_test.go
  imagetest/test_suites/image_validation/setup.go
Labels: approved, cla: yes, lgtm, size/S

#130 support test filter
  imagetest/cmd/manager/main.go
Labels: approved, cla: yes, lgtm, size/M

#129 add guest packages test
  imagetest/test_suites/image_validation/package_test.go
  imagetest/test_suites/image_validation/setup.go
Labels: approved, cla: yes, lgtm, size/M

#131 use regex \s
  imagetest/test_suites/image_validation/license_test.go
Labels: approved, cla: yes, lgtm, size/XS

#133 Fix license test
  imagetest/README.md
  imagetest/test_suites/image_validation/license_test.go
Labels: approved, cla: yes, lgtm, size/M

#134 Switch daisy/gce-image-publish to release tag.
  concourse/tasks/daisy-build-derivative-images.yaml
  concourse/tasks/daisy-build-images-debian.yaml
  concourse/tasks/daisy-build-images.yaml
  concourse/tasks/daisy-export-images-partner.yaml
  concourse/tasks/daisy-publish-images.yaml
  concourse/tasks/guest-package-build.yaml
  concourse/tasks/package-gointegtest.yaml
Labels: approved, cla: yes, lgtm, size/S

#135 support patches and sources for rpm build
  packagebuild/daisy_startupscript_rpm.sh
Labels: approved, cla: yes, lgtm, size/XS

#125 add linux license check
  imagetest/test_suites/image_validation/linux_license_test.go
  imagetest/utils/test_utils.go
Labels: approved, cla: yes, lgtm, size/M

#136 Artifact registry plugin builds
  concourse/pipelines/guest-package-build.yaml
  concourse/tasks/guest-package-build.yaml
Labels: approved, cla: yes, lgtm, size/L

#137 correct dnf plugin path
  concourse/pipelines/guest-package-build.yaml
Labels: approved, cla: yes, lgtm, size/XS

#141 Guest agent image tests
  concourse/pipelines/guest-package-build.yaml
  concourse/tasks/daisy-build-package-image.yaml
Labels: approved, cla: yes, lgtm, size/L

#142 prune input
  concourse/tasks/daisy-build-package-image.yaml
Labels: approved, cla: yes, size/XS

#140 exit with error when test suites has failure or error
  imagetest/cmd/manager/main.go
  imagetest/junit.go
  imagetest/testworkflow.go
Labels: approved, cla: yes, lgtm, size/M

#69 add e2e-test job and task
  concourse/pipelines/linux-image-build.yaml
  concourse/tasks/image-test.yaml
Labels: approved, cla: yes, lgtm, size/S

#143 merge agent integ test
  concourse/pipelines/guest-package-build.yaml
Labels: approved, cla: yes, lgtm, size/S

#146 Don't run 'go get' inside BUILD_DIR
  packagebuild/daisy_startupscript_goo.sh
Labels: approved, cla: yes, lgtm, size/S

#147 use 'main' for guest-agent
  concourse/pipelines/guest-package-build.yaml
Labels: approved, cla: yes, lgtm, size/S

#148 no err on cp
  packagebuild/daisy_startupscript_rpm.sh
Labels: approved, cla: yes, lgtm, size/XS

#149 fix branch name
  concourse/pipelines/guest-package-build.yaml
Labels: approved, cla: yes, lgtm, size/XS

#139 image test concourse debian centos rhel
  concourse/pipelines/linux-image-build.yaml
Labels: approved, cla: yes, lgtm, size/M

#127 add clock test
  imagetest/test_suites/image_validation/clock_test.go
  imagetest/test_suites/image_validation/setup.go
Labels: approved, cla: yes, lgtm, size/M
