Repository GoogleCloudPlatform/guest-test-infra, pull requests merged in 2021-08, with the labels that each got.

#199 add test TestHostKeysAreUnique
  imagetest/test_suites/hostkey/hostkey_pubish_test.go
  imagetest/test_suites/ssh/image_ssh_test.go
  imagetest/test_suites/ssh/setup.go
  imagetest/utils/test_utils.go
Labels: approved, cla: yes, lgtm, size/L

#206 add gcs_path parameter
  imagetest/cmd/manager/main.go
  imagetest/testworkflow.go
Labels: lgtm, approved, size/M, cla: yes

#207 add logging for config
  imagetest/cmd/manager/main.go
  imagetest/testworkflow.go
Labels: lgtm, approved, cla: yes, size/S

#205 add sleep for ssh and log
  imagetest/test_suites/ssh/image_ssh_test.go
Labels: size/XS, lgtm, approved, cla: yes

#208 fix bug in cit-periodic and move test
  imagetest/cmd/manager/main.go
  imagetest/fixtures.go
  imagetest/test_suites/hostkey/hostkey_pubish_test.go
  imagetest/test_suites/hostkey/setup.go
  imagetest/test_suites/ssh/image_ssh_test.go
  imagetest/test_suites/ssh/setup.go
Labels: size/L, lgtm, approved, cla: yes

#211 skip secure boot on d9 and rocky linux
  imagetest/test_suites/image_boot/setup.go
Labels: size/XS, lgtm, approved, cla: yes

#210 fail on test compilation failure
  imagetest/Dockerfile
Labels: size/XS, lgtm, approved, cla: yes

#209 fix image_boot test
  imagetest/test_suites/image_boot/setup.go
Labels: size/XS, lgtm, approved, cla: yes

#212 CIT: Emit per-testcase errors on workflow failure
  imagetest/Dockerfile
  imagetest/junit.go
  imagetest/junit_test.go
  imagetest/testworkflow.go
Labels: lgtm, approved, size/M, cla: yes

#214 emit finish signal to console multiple times
  imagetest/cmd/wrapper/main.go
Labels: size/XS, lgtm, approved, cla: yes

#204 add test multinic
  imagetest/fixtures.go
  imagetest/fixtures_test.go
  imagetest/test_suites/network/multinic_minimal_network_test.go
  imagetest/test_suites/network/setup.go
  imagetest/testworkflow.go
Labels: size/L, lgtm, approved, cla: yes

#217 Remove test steps until tests are stable.
  concourse/pipelines/linux-image-build.yaml
Labels: lgtm, approved, size/M, cla: yes

#213 add shutdown script test
  imagetest/fixtures.go
  imagetest/test_suites/image_boot/setup.go
  imagetest/test_suites/image_boot/shutdown_test.go
  imagetest/test_suites/metadata/setup.go
  imagetest/test_suites/metadata/shutdown_script_test.go
Labels: size/L, lgtm, approved, cla: yes

#220 rename
  imagetest/test_suites/ssh/image_ssh_test.go
  imagetest/test_suites/ssh/setup.go
Labels: size/XS, lgtm, approved, cla: yes

#215 add startup script test
  imagetest/test_suites/metadata/setup.go
  imagetest/test_suites/metadata/startup_script_test.go
Labels: lgtm, approved, size/M, cla: yes

#221 add project pools and locking
  imagetest/cmd/manager/main.go
  imagetest/fixtures.go
  imagetest/testworkflow.go
Labels: size/L, lgtm, approved, cla: yes

#198 CIT: add test docs
  imagetest/README.md
  imagetest/test_suites/README.md
Labels: size/L, lgtm, approved, cla: yes

#223 Use debian 10 for osconfig package builds
  concourse/pipelines/guest-package-build.yaml
Labels: size/XS, lgtm, approved, cla: yes
