Repository GoogleCloudPlatform/guest-test-infra, pull requests merged in 2021-01, with the labels that each got.

#51 Add CentOS Stream build, remove RHEL 6.
  concourse/pipelines/linux-image-build.yaml
Labels: approved, cla: yes, lgtm, size/L

#54 Cleanup some misconfiguration
  concourse/pipelines/guest-package-build.yaml
  concourse/pipelines/linux-image-build.yaml
Labels: approved, cla: yes, lgtm, size/S

#56 Fix iso paths secret name.
  concourse/pipelines/linux-image-build.yaml
Labels: approved, cla: yes, lgtm, size/S

#53 Bare metal image pipeline
  concourse/pipelines/bare-metal-image-build.yaml
  concourse/tasks/daisy-build-derivative-images.yaml
Labels: approved, cla: yes, lgtm, size/L

#57 Add zmarano to owners.
  OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#58 Fix generated publish version to be vYYYYMMDD
  concourse/pipelines/bare-metal-image-build.yaml
  concourse/tasks/generate-version.yaml
Labels: approved, cla: yes, lgtm, size/XS

#50 add set-pipeline for new pipeline
  concourse/pipelines/pipeline-set-pipeline.yaml
Labels: approved, cla: yes, lgtm, size/XS

#62 Add RHEL BYOS.
  concourse/pipelines/linux-image-build.yaml
Labels: approved, cla: yes, lgtm, size/L

#59 Fix dev image build resources.
  concourse/pipelines/dev-image-build.yaml
Labels: approved, cla: yes, lgtm, size/S

#61 add two new pipeline in set-pipeline
  concourse/pipelines/pipeline-set-pipeline.yaml
Labels: approved, cla: yes, lgtm, size/XS
