Repository GoogleCloudPlatform/guest-test-infra, pull requests merged in 2021-12, with the labels that each got.

#317 Fix windows sql build task
  concourse/tasks/daisy-build-images-windows-sql.yaml
Labels: size/XS, lgtm, approved, cla: yes

#318 Add SQL server builds/ releases
  concourse/pipelines/windows-image-build.yaml
Labels: lgtm, approved, cla: yes, size/XXL

#319 add skip_download to windows builds
  concourse/pipelines/windows-image-build.yaml
Labels: lgtm, approved, size/M

#321 Some packages have license info in their README file.
  imagetest/test_suites/image_validation/license_test.go
Labels: size/XS, lgtm, approved

#304 CIT: more SLES fixes
  imagetest/test_suites/image_validation/license_test.go
  imagetest/test_suites/image_validation/package_test.go
Labels: lgtm, approved, cla: yes, size/S

#320 Update triggered resources
  concourse/pipelines/windows-image-build.yaml
Labels: size/L, lgtm, approved

#322 add groups for windows pipeline
  concourse/pipelines/windows-image-build.yaml
Labels: size/L, lgtm, approved

#323 Add missing vars to the container workflow
  concourse/pipelines/windows-image-build.yaml
Labels: size/XS, lgtm, approved

#324 Fix container task var
  concourse/tasks/daisy-build-images-windows-container.yaml
Labels: size/XS, lgtm, approved

#325 Fix missing var in container task
  concourse/tasks/daisy-build-images-windows-container.yaml
Labels: size/XS, lgtm, approved

#326 Update gcs naming to match publish workflows
  concourse/pipelines/windows-image-build.yaml
Labels: lgtm, approved, size/S

#327 Fix param input
  concourse/pipelines/windows-image-build.yaml
Labels: size/XS, lgtm, approved

#328 Add rollout rate support for the publish to testing
  concourse/tasks/daisy-publish-images.yaml
Labels: size/XS, lgtm, approved

#329 fix the wf reference
  concourse/pipelines/windows-image-build.yaml
Labels: size/XS, lgtm, approved
