Repository GoogleCloudPlatform/guest-test-infra, pull requests merged in 2021-11, with the labels that each got.

#289 use curl in gointegtest
  container_images/gointegtest/run_integ_tests.sh
Labels: lgtm, approved, cla: yes, size/S

#290 Cutover image pipeline - Windows image build
  concourse/pipelines/windows-image-build.yaml
Labels: size/L, lgtm, approved, cla: yes

#291 Cutover image pipeline - Linux related image builds
  concourse/pipelines/bare-metal-image-build.yaml
  concourse/pipelines/debian-worker-image-build.yaml
  concourse/pipelines/linux-image-build.yaml
  concourse/pipelines/partner-image-export.yaml
Labels: size/L, lgtm, approved, cla: yes

#287 Cutover pubsub topic
  concourse/tasks/gcloud-promote-package.yaml
Labels: size/XS, lgtm, approved, cla: yes

#292 Add OS Login tests for getent passwd.
  imagetest/test_suites/oslogin/oslogin_test.go
  imagetest/test_suites/oslogin/setup.go
Labels: lgtm, approved, size/M, cla: yes

#296 fix package and image params
  concourse/pipelines/guest-package-build.yaml
  concourse/pipelines/linux-image-build.yaml
Labels: lgtm, approved, size/M, cla: yes

#298 fix network test
  imagetest/fixtures.go
  imagetest/test_suites/network/alias_ip_test.go
  imagetest/test_suites/network/multinic_minimal_network_test.go
  imagetest/test_suites/network/setup.go
Labels: size/L, lgtm, approved, cla: yes

#295 Fixes for OS Login tests that got missed.
  imagetest/test_suites/oslogin/oslogin_test.go
  imagetest/test_suites/oslogin/setup.go
Labels: lgtm, approved, cla: yes, size/S

#299 test fixes for SLES
  imagetest/test_suites/disk/setup.go
  imagetest/test_suites/image_validation/image_validation_test.go
  imagetest/test_suites/image_validation/license_test.go
  imagetest/test_suites/image_validation/package_test.go
  imagetest/test_suites/network/dhcp_test.go
  imagetest/test_suites/security/image_security_test.go
  imagetest/testworkflow.go
Labels: lgtm, approved, size/M, cla: yes

#297 fix shutdownscripttime test log
  imagetest/test_suites/metadata/shutdown_script_test.go
Labels: size/XS, lgtm, approved, cla: yes

#303 disable OS Login tests
  concourse/tasks/image-test-args.yaml
  concourse/tasks/image-test.yaml
Labels: size/XS, lgtm, approved, cla: yes

#305 Remove deprecated images, add newer ones.
  container_images/gointegtest/integ-test-all.wf.json
  imagetest/cmd/manager/main.go
Labels: lgtm, approved, size/M, cla: yes

#294 Updating the Windows pipeline to use secret manager
  concourse/pipelines/windows-image-build.yaml
Labels: size/L, lgtm, approved, cla: yes

#306 disable oslogin
  concourse/pipelines/guest-package-build.yaml
Labels: size/XS, lgtm, approved, cla: yes

#307 gotest: Allow clients to specify extra test args.
  container_images/gotest/main.sh
Labels: size/XS, lgtm, approved, cla: yes

#308 Updating windows 2012r2 builds to use the correct publish file
  concourse/pipelines/windows-image-build.yaml
Labels: size/XS, lgtm, approved, cla: yes

#310 use git resource rather than container wf
  concourse/tasks/daisy-build-images.yaml
Labels: size/XS, lgtm, approved, cla: yes

#311 use relative parent path for workflow_root
  concourse/tasks/daisy-build-images.yaml
Labels: size/XS, lgtm, approved, cla: yes

#312 use correct relative path
  concourse/tasks/daisy-build-images.yaml
Labels: size/XS, lgtm, approved, cla: yes

#313 Add image for running import/export module tests
  container_images/cli-tools-module-tests/Dockerfile
Labels: lgtm, approved, cla: yes, size/S

#301 Instrument the windows-image-build pipeline with job metrics
  concourse/pipelines/windows-image-build.yaml
Labels: lgtm, approved, cla: yes, size/XL

#302 Instrument the partner-image-export pipeline with job metrics
  concourse/pipelines/partner-image-export.yaml
Labels: lgtm, approved, cla: yes, size/XXL

#314 Concourse build for cli-tools-module-tests
  concourse/pipelines/container-build.yaml
Labels: lgtm, approved, cla: yes, size/S

#309 Add Win2022 to windows release pipeline
  concourse/pipelines/windows-image-build.yaml
Labels: size/L, lgtm, approved, cla: yes

#315 Add sql-2012-enterprise-windows-2012-r2-dc
  concourse/pipelines/windows-image-build.yaml
  concourse/tasks/daisy-build-images-windows-sql.yaml
Labels: size/L, lgtm, approved, cla: yes
