Repository GoogleCloudPlatform/guest-test-infra, pull requests merged in 2022-08, with the labels that each got.

#536 Remove Debian 9 from builds.
  concourse/pipelines/linux-image-build.jsonnet
  container_images/gointegtest/integ-test-all.wf.json
Labels: lgtm, approved, size/M

#537 Remove SQL Server 2012 from Concourse Windows Builds
  concourse/pipelines/windows-image-build.jsonnet
Labels: lgtm, approved, size/S

#522 build & publish windows-install-media
  concourse/pipelines/windows-image-build.jsonnet
  concourse/templates/daisy.libsonnet
Labels: size/L, lgtm, approved

#538 [windows-install-media] fix build var name
  concourse/pipelines/windows-image-build.jsonnet
Labels: size/XS, lgtm, approved

#539 RHEL 9 BYOS image build.
  concourse/pipelines/linux-image-build.jsonnet
Labels: size/XS, lgtm, approved

#540 Add SQL Server 2022 Preview to Windows pipeline
  concourse/pipelines/windows-image-build.jsonnet
Labels: size/L, lgtm, approved

#541 Remove Windows Server SAC 20h2 from Concourse
  concourse/pipelines/windows-image-build.jsonnet
Labels: size/XS, lgtm, approved

#542 Update secret used by SQL22
  concourse/pipelines/windows-image-build.jsonnet
Labels: size/XS, lgtm, approved

#544 Add Windows GooGet tests.
  imagetest/cmd/manager/main.go
  imagetest/test_suites/windows/googet_test.go
  imagetest/test_suites/windows/setup.go
  imagetest/utils/test_utils.go
Labels: size/L, lgtm, approved

#543 Boot time regression
  imagetest/test_suites/image_boot/image_boot_test.go
  imagetest/test_suites/image_boot/setup.go
Labels: size/L, lgtm, approved

#545 Add guest packages tests.
  imagetest/cmd/manager/main.go
  imagetest/test_suites/windows/googet_test.go
  imagetest/test_suites/windows/setup.go
  imagetest/utils/test_utils.go
Labels: size/L, lgtm, approved
