Repository GoogleCloudPlatform/guest-test-infra, pull requests merged in 2022-06, with the labels that each got.

#481 add missing input
  concourse/pipelines/guest-package-build.jsonnet
Labels: lgtm, approved, size/S

#483 Update windows pipeline to support internal env
  concourse/pipelines/windows-image-build.jsonnet
Labels: lgtm, approved, size/M

#484 Update order so internal is after prod
  concourse/pipelines/windows-image-build.jsonnet
Labels: size/XS, lgtm, approved

#482 add el9_arm64 packagebuild workflow
  packagebuild/workflows/build_el9_arm64.wf.json
Labels: lgtm, approved, size/M

#486 prune unused guest-package-build.yaml
  concourse/pipelines/guest-package-build.yaml
Labels: lgtm, approved, size/XXL

#487 Add Windows SSH to guest-package-build.
  concourse/pipelines/guest-package-build.jsonnet
Labels: lgtm, approved, size/S

#488 extract generate-timestamp to template
  concourse/pipelines/guest-package-build.jsonnet
Labels: lgtm, approved, size/M

#489 Fix last stable
  concourse/pipelines/guest-package-build.jsonnet
Labels: lgtm, approved, size/M

#490 correct windows package paths
  concourse/pipelines/guest-package-build.jsonnet
Labels: lgtm, approved, size/S

#492 skip secure boot test on arm
  imagetest/test_suites/image_boot/setup.go
Labels: size/XS, lgtm, approved

#494 remove imagetest-specific OWNERS file
  imagetest/OWNERS
Labels: size/XS, lgtm, approved

#493 use direct ping library in multinic test
  imagetest/go.mod
  imagetest/go.sum
  imagetest/test_suites/network/multinic_minimal_network_test.go
Labels: lgtm, approved, size/S

#495 Follow 8.3 windows file naming and support x86 images
  imagetest/Dockerfile
  imagetest/testworkflow.go
Labels: lgtm, approved, size/S

#497 Fix rocky linux optimized name.
  concourse/pipelines/linux-image-build.jsonnet
Labels: size/XS, lgtm, approved

#498 [new golang build policy] upgrade presubmit golang version to 1.16
  container_images/gobuild/Dockerfile
  packagebuild/common.sh
Labels: size/XS, lgtm, approved

#467 RHUI: Prod currently uses us-east1 only
  concourse/pipelines/rhui-release.jsonnet
Labels: lgtm, approved, size/S

#502 support underscores in packagebuild container
  container_images/daisy-builder/main.sh
Labels: size/XS, lgtm, approved

#503 Update triggers in windows pipeline
  concourse/pipelines/windows-image-build.jsonnet
Labels: lgtm, approved, size/S

#504 add ubuntu proposed images for validation
  concourse/pipelines/partner-image-validations.jsonnet
Labels: lgtm, approved, size/M

#505 add groups to partner validations
  concourse/pipelines/partner-image-validations.jsonnet
Labels: lgtm, approved, size/M

#506 support aussie licenses
  imagetest/test_suites/image_validation/license_test.go
Labels: size/XS, lgtm, approved

#508 logging package contents
  packagebuild/daisy_startupscript_deb.sh
  packagebuild/daisy_startupscript_rpm.sh
Labels: size/XS, lgtm, approved
