Repository GoogleCloudPlatform/guest-test-infra, pull requests merged in 2022-05, with the labels that each got.

#456 Partner image export remove creds
  concourse/pipelines/partner-image-export.yaml
Labels: lgtm, approved, size/M

#457 Remove 81 and add 93,97 COS images
  concourse/pipelines/partner-image-export.yaml
Labels: size/L, lgtm, approved

#458 Transition ARLE publish tasks to spanner
  concourse/tasks/gcloud-promote-package.yaml
  concourse/templates/arle.libsonnet
Labels: size/XS, lgtm, approved

#460 Release testing image to arle prod
  concourse/pipelines/artifact-releaser-test.yaml
Labels: lgtm, approved, size/S

#461 Fix set pipeline for artifact-releaser-test
  concourse/pipelines/pipeline-set-pipeline.yaml
Labels: size/XS, lgtm, approved

#462 Missing steps in release-testing-image
  concourse/pipelines/artifact-releaser-test.yaml
Labels: size/XS, lgtm, approved

#463 Remove get credential tasks from artifact-releaser-test
  concourse/pipelines/artifact-releaser-test.yaml
Labels: size/XS, lgtm, approved

#464 Use gcloud-publish-image template to send pubsub message
  concourse/pipelines/artifact-releaser-test.yaml
Labels: lgtm, approved, size/S

#465 Change publish image type to insertImage
  concourse/tasks/gcloud-publish-image.yaml
Labels: size/XS, lgtm, approved

#451 RHUI roll-out: Wait for MIGs to be stable
  concourse/pipelines/rhui-release.yaml
Labels: size/L, lgtm, approved

#466 Remove yaml version of rhui-release pipeline
  concourse/pipelines/rhui-release.yaml
Labels: lgtm, approved, size/XL

#426 upload ARM packages
  concourse/pipelines/artifact-releaser-test.yaml
  concourse/pipelines/guest-package-build.yaml
  concourse/tasks/gcloud-package-operation.yaml
Labels: lgtm, approved, size/M

#425 run ARM tests for guest agent based on test image
  concourse/pipelines/guest-package-build.yaml
  concourse/tasks/daisy-build-package-image.yaml
  concourse/tasks/image-test-args.yaml
Labels: lgtm, approved, size/M

#468 [package test image] specify us-central1-a for arm machine type
  concourse/tasks/daisy-build-package-image.yaml
Labels: size/XS, lgtm, approved

#469 specify machine type for guest-agent amd64 test
  concourse/pipelines/guest-package-build.yaml
Labels: size/XS, lgtm, approved

#470 [image-test-args] fix a minor typo
  concourse/tasks/image-test-args.yaml
Labels: size/XS, lgtm, approved

#472 RHEL 9 build
  concourse/pipelines/linux-image-build.jsonnet
Labels: size/XS, lgtm, approved

#473 run agent image tests in us-central1
  concourse/tasks/image-test-args.yaml
Labels: size/XS, lgtm, approved

#475 Strip the word stable from date
  concourse/tasks/get-last-stable-tag.yaml
Labels: size/XS, lgtm, approved

#474 [guest-agent image test] fix: verify that shut down script executed no less than 80s
  imagetest/test_suites/metadata/shutdown_script_test.go
Labels: size/XS, lgtm, approved

#477 packagebuilder: fix git version on EL7
  packagebuild/daisy_startupscript_rpm.sh
Labels: size/XS, lgtm, approved

#476 Use templates for guest package build pipeline
  concourse/pipelines/guest-package-build.jsonnet
  concourse/pipelines/pipeline-set-pipeline.yaml
Labels: lgtm, approved, size/XXL

#480 fix daisy typo in guest package build
  concourse/pipelines/guest-package-build.jsonnet
Labels: size/XS, lgtm, approved
