Repository GoogleCloudPlatform/guest-test-infra, pull requests merged in 2022-07, with the labels that each got.

#510 remove EricEdens from OWNERS
  OWNERS
Labels: size/XS, lgtm, approved

#511 Add windows client 8.1 and 10 to Windows pipeline
  concourse/pipelines/windows-image-build.jsonnet
Labels: lgtm, approved, size/M

#513 update OWNERS
  OWNERS
Labels: size/XS, lgtm, approved

#516 add karn and leo to OWNERS
  OWNERS
Labels: size/XS, lgtm, approved

#512 add sles validations
  concourse/pipelines/partner-image-validations.jsonnet
Labels: lgtm, approved, size/M

#518 Add Windows11 to Concourse Windows pipeline
  concourse/pipelines/windows-image-build.jsonnet
Labels: size/XS, lgtm, approved

#507 Support Rocky Linux 8 Optimized for GCP ARM64 build.
  concourse/pipelines/linux-image-build.jsonnet
Labels: lgtm, approved, size/M

#520 Use 'arm64' for the workflow names.
  concourse/pipelines/guest-package-build.jsonnet
Labels: size/XS, lgtm, approved

#521 Fix typo
  concourse/pipelines/guest-package-build.jsonnet
Labels: size/XS, lgtm, approved

#523 Add Debian 11 worker build (there is no staging for any of these).
  concourse/pipelines/debian-worker-image-build.yaml
Labels: size/L, lgtm, approved

#525 Move guest package image builder to Debian 11 worker.
  concourse/pipelines/guest-package-build.jsonnet
Labels: size/XS, lgtm, approved

#527 Add Rocky Linux 9 builds.
  concourse/pipelines/linux-image-build.jsonnet
Labels: size/XS, lgtm, approved

#529 Adding concourse build pipeline for gce-diagnostics package
  concourse/pipelines/guest-package-build.jsonnet
Labels: lgtm, approved, size/M

#531 update partner image exports
  concourse/pipelines/partner-image-export.jsonnet
  concourse/pipelines/partner-image-export.yaml
  concourse/pipelines/pipeline-set-pipeline.yaml
Labels: lgtm, approved, size/XXL

#532 only build diagnostics when changed
  concourse/pipelines/guest-package-build.jsonnet
Labels: size/XS, lgtm, approved

#533 Add in proposed guest agent changes image families for Ubuntu
  concourse/pipelines/partner-image-validations.jsonnet
Labels: size/XS, lgtm, approved

#534 Add RHEL 8.6 image build.
  concourse/pipelines/linux-image-build.jsonnet
Labels: size/XS, lgtm, approved

#535 AlmaLinux 9 build.
  concourse/pipelines/linux-image-build.jsonnet
Labels: size/XS, lgtm, approved
