Repository GoogleCloudPlatform/guest-test-infra, pull requests merged in 2022-02, with the labels that each got.

#352 Remove CentOS 8 from tests.
  concourse/pipelines/guest-package-build.yaml
  container_images/gointegtest/integ-test-all.wf.json
  imagetest/cmd/manager/main.go
  imagetest/test_suites/image_validation/linux_license_test.go
Labels: lgtm, approved, size/M

#332 Add SQL 2017/2019 on server 2022 build jobs
  concourse/pipelines/windows-image-build.yaml
Labels: lgtm, approved, size/XL

#353 Add pre-release builds/tests for CentOS Stream 9.
  concourse/pipelines/guest-package-build.yaml
  concourse/pipelines/linux-image-build.jsonnet
  container_images/gointegtest/integ-test-all.wf.json
  packagebuild/workflows/build_el9.wf.json
Labels: size/L, lgtm, approved

#354 Enable dev repos for EL8/9 builds.
  packagebuild/daisy_startupscript_rpm.sh
Labels: lgtm, approved, size/S

#356 detect coverage percent as integer
  container_images/gotest/main.sh
Labels: size/XS, lgtm, approved

#358 use correct prefix in gcs step
  concourse/pipelines/linux-image-build.jsonnet
Labels: size/XS, lgtm, approved

#359 use us-central1-a for daisy tasks
  concourse/templates/daisy.libsonnet
Labels: size/XS, lgtm, approved

#360 Fork registry image
  concourse/pipelines/container-build.yaml
  container_images/registry-image-forked/.gitignore
  container_images/registry-image-forked/LICENSE.md
  container_images/registry-image-forked/NOTICE.md
  container_images/registry-image-forked/README.md
  container_images/registry-image-forked/backoff.go
  container_images/registry-image-forked/check_test.go
  container_images/registry-image-forked/cmd/check/main.go
  container_images/registry-image-forked/cmd/in/main.go
  container_images/registry-image-forked/cmd/out/main.go
  container_images/registry-image-forked/commands/check.go
  container_images/registry-image-forked/commands/in.go
  container_images/registry-image-forked/commands/logging.go
  container_images/registry-image-forked/commands/out.go
  container_images/registry-image-forked/commands/unpack.go
  container_images/registry-image-forked/dockerfiles/alpine/Dockerfile
  container_images/registry-image-forked/dockerfiles/ubuntu/Dockerfile
  container_images/registry-image-forked/go.mod
  container_images/registry-image-forked/go.sum
  container_images/registry-image-forked/in_test.go
  container_images/registry-image-forked/out_test.go
  container_images/registry-image-forked/suite_test.go
  container_images/registry-image-forked/testdata/file-perms-mtime/Dockerfile
  container_images/registry-image-forked/testdata/metadata/Dockerfile
  container_images/registry-image-forked/testdata/removed-hardlinks/Dockerfile
  container_images/registry-image-forked/testdata/setup-images
  container_images/registry-image-forked/testdata/static.tagged/Dockerfile
  container_images/registry-image-forked/testdata/static/Dockerfile
  container_images/registry-image-forked/testdata/static/older/Dockerfile
  container_images/registry-image-forked/testdata/symlinks/Dockerfile
  container_images/registry-image-forked/testdata/whiteout/Dockerfile
  container_images/registry-image-forked/types.go
  container_images/registry-image-forked/types_test.go
Labels: lgtm, approved, size/XXL

#361 update forked go.sum
  container_images/registry-image-forked/go.sum
Labels: size/XS, approved

#362 publish forked registry resource to c-i-t repo
  concourse/pipelines/container-build.yaml
Labels: size/XS, approved

#363 use new forked image resource
  concourse/pipelines/linux-image-build.jsonnet
Labels: lgtm, approved, size/S

#355 New upload staging and unstable tasks to ARLE
  concourse/pipelines/artifact-releaser-autopush.yaml
  concourse/tasks/gcloud-package-operation.yaml
Labels: lgtm, approved, size/M

#365 Use task gcloud-package-operation for package upload
  concourse/pipelines/guest-package-build.yaml
  concourse/tasks/gcloud-inject-package.yaml
Labels: size/L, lgtm, approved

#366 add project to publish-coverage
  concourse/tasks/publish-coverage.yaml
  container_images/concourse-metrics/cmd/publish-coverage/main.go
Labels: size/XS, lgtm, approved

#369 Update container build workflow
  concourse/pipelines/container-build.jsonnet
  concourse/pipelines/container-build.yaml
  concourse/pipelines/pipeline-set-pipeline.yaml
  concourse/tasks/image-test-args.yaml
  concourse/tasks/image-test.yaml
Labels: size/L, lgtm, approved

#371 Windows template
  concourse/pipelines/linux-image-build.jsonnet
  concourse/pipelines/pipeline-set-pipeline.yaml
  concourse/pipelines/thefile
  concourse/pipelines/windows-image-build.jsonnet
  concourse/pipelines/windows-image-build.yaml
  concourse/templates/arle.libsonnet
  concourse/templates/common.libsonnet
  concourse/templates/daisy.libsonnet
  concourse/templates/gcp-secret-manager.libsonnet
Labels: lgtm, approved, size/XXL

#372 Add daisy binary steps to container-build
  concourse/pipelines/container-build.jsonnet
Labels: size/L, lgtm, approved

#373 fix typo
  concourse/pipelines/windows-image-build.jsonnet
Labels: size/XS, lgtm, approved

#375 rename -arm to -arm64
  concourse/pipelines/linux-image-build.jsonnet
  concourse/templates/common.libsonnet
Labels: size/XS, lgtm, approved

#376 prune credential tasks
  concourse/pipelines/artifact-releaser-autopush.yaml
  concourse/pipelines/bare-metal-image-build.yaml
  concourse/pipelines/debian-worker-image-build.yaml
  concourse/pipelines/guest-package-build.yaml
  concourse/pipelines/partner-image-export.yaml
  concourse/tasks/build-container-image.yaml
  concourse/tasks/certbot-rhui.yaml
  concourse/tasks/daisy-build-derivative-images.yaml
  concourse/tasks/daisy-build-images-debian.yaml
  concourse/tasks/daisy-build-images-windows-container.yaml
  concourse/tasks/daisy-build-images-windows-sql.yaml
  concourse/tasks/daisy-build-images-windows.yaml
  concourse/tasks/daisy-build-images.yaml
  concourse/tasks/daisy-build-package-image.yaml
  concourse/tasks/daisy-export-images-partner.yaml
  concourse/tasks/daisy-publish-images.yaml
  concourse/tasks/gcloud-get-secret.yaml
  concourse/tasks/gcloud-package-operation.yaml
  concourse/tasks/gcloud-promote-package.yaml
  concourse/tasks/gcloud-publish-image.yaml
  concourse/tasks/generate-build-id.yaml
  concourse/tasks/generate-build-ids-windows.yaml
  concourse/tasks/generate-package-version.yaml
  concourse/tasks/generate-timestamp.yaml
  concourse/tasks/generate-version.yaml
  concourse/tasks/get-credential.yaml
  concourse/tasks/get-github-token.yaml
  concourse/tasks/get-last-stable-tag.yaml
  concourse/tasks/gotest.yaml
  concourse/tasks/gsutil-ls.yaml
  concourse/tasks/guest-package-build.yaml
  concourse/tasks/image-test-args.yaml
  concourse/tasks/image-test.yaml
  concourse/tasks/package-gointegtest.yaml
  concourse/tasks/publish-coverage.yaml
  concourse/tasks/publish-job-result.yaml
  concourse/tasks/publish-time-since.yaml
  concourse/tasks/render-templates.yaml
  concourse/tasks/tag-commit.yaml
  concourse/tasks/validate-integtest-result.yaml
  concourse/tasks/validate-version.yaml
Labels: lgtm, approved, size/XL

#377 use specified GCS bucket for rhui build
  concourse/pipelines/linux-image-build.jsonnet
Labels: size/XS, lgtm, approved

#378 Rename arm->arm64
  concourse/pipelines/linux-image-build.jsonnet
Labels: size/XS, lgtm, approved

#379 put gcspath arg in correct location
  concourse/pipelines/linux-image-build.jsonnet
Labels: size/XS, lgtm, approved

#382 RHUI build: prepend -gcs_path
  concourse/pipelines/linux-image-build.jsonnet
Labels: size/XS, lgtm, approved

#383 RHUI build: use full gcs path
  concourse/pipelines/linux-image-build.jsonnet
  concourse/pipelines/thefile
Labels: size/XS, lgtm, approved

#380 Migrating Enterprise Linux builds to use secret manager
  concourse/pipelines/linux-image-build.jsonnet
Labels: lgtm, approved, size/S

#384 prune trailing slash
  concourse/pipelines/linux-image-build.jsonnet
Labels: lgtm, approved, size/S

#381 Publish daisy binaries to compute-image-tools
  concourse/pipelines/container-build.jsonnet
Labels: lgtm, approved, size/M

#386 Daisy bin publish: Fix 'sh: illegal option -'
  concourse/pipelines/container-build.jsonnet
Labels: size/XS, lgtm, approved

#387 add EricEdens to OWNERS
  OWNERS
Labels: size/XS, lgtm, approved

#385 Container build for "daisy test runner"
  concourse/pipelines/container-build.jsonnet
Labels: size/XS, lgtm, approved

#389 daisy binaries: use latest, ensure public
  concourse/pipelines/container-build.jsonnet
Labels: size/XS, lgtm, approved

#391 Fix `sh: illegal option - `
  concourse/pipelines/container-build.jsonnet
Labels: size/XS, lgtm, approved

#392 Add license for python2-futures.
  imagetest/test_suites/image_validation/license_test.go
Labels: size/XS, lgtm, approved

#390 ARM image tests
  concourse/pipelines/linux-image-build.jsonnet
  concourse/tasks/image-test.yaml
  imagetest/Dockerfile
  imagetest/cmd/manager/main.go
  imagetest/test_suites/network/alias_ip_test.go
  imagetest/test_suites/network/dhcp_test.go
  imagetest/test_suites/network/mtu_test.go
  imagetest/testworkflow.go
  imagetest/utils/test_utils.go
Labels: size/L, lgtm, approved
