Repository GoogleCloudPlatform/guest-test-infra, pull requests merged in 2022-04, with the labels that each got.

#439 Secure boot on Rocky Linux 8 is actually supported now.
  imagetest/test_suites/image_boot/image_boot_test.go
Labels: size/XS, lgtm, approved

#440 add rhui publish tasks
  concourse/pipelines/linux-image-build.jsonnet
  concourse/templates/arle.libsonnet
  concourse/templates/common.libsonnet
  concourse/templates/daisy.libsonnet
  concourse/templates/gcp-secret-manager.libsonnet
Labels: size/L, lgtm, approved

#436 comment out guest-agent-publish-coverage since it is broken
  concourse/pipelines/guest-package-build.yaml
Labels: lgtm, approved, size/S

#441 Add pipeline for RHUIv4 release
  concourse/pipelines/pipeline-set-pipeline.yaml
  concourse/pipelines/rhui-release.yaml
Labels: size/L, lgtm, approved

#442 CIT: Support SSH connections to hosts that block SHA1
  concourse/pipelines/container-build.jsonnet
  imagetest/Dockerfile
  imagetest/go.mod
  imagetest/go.sum
Labels: lgtm, approved, size/XL

#443 publish rhui images to testing first
  concourse/pipelines/linux-image-build.jsonnet
Labels: size/XS, lgtm, approved

#444 changes to CIT for ubuntu images
  imagetest/test_suites/image_validation/image_validation_test.go
  imagetest/test_suites/image_validation/license_test.go
  imagetest/test_suites/image_validation/package_test.go
  imagetest/test_suites/security/image_security_test.go
Labels: lgtm, approved, size/S

#445 add rocky linux optimized for gcp
  concourse/pipelines/linux-image-build.jsonnet
Labels: lgtm, approved, size/S

#447 replace rollout rate var
  concourse/pipelines/linux-image-build.jsonnet
Labels: size/XS, lgtm, approved

#446 Fix containers
  concourse/pipelines/container-build.jsonnet
  container_images/concourse-metrics/Dockerfile
  container_images/jsonnet-go/Dockerfile
  container_images/validate-integtest/Dockerfile
Labels: lgtm, approved, size/M

#448 Partner image validation pipeline
  concourse/pipelines/partner-image-validations.jsonnet
  concourse/pipelines/pipeline-set-pipeline.yaml
Labels: size/L, lgtm, approved

#450 rhui-release: wire manual-trigger
  concourse/pipelines/rhui-release.yaml
Labels: size/XS, lgtm, approved

#438 Creating computer-image-windows package build/release
  concourse/pipelines/guest-package-build.yaml
Labels: size/L, lgtm, approved

#454 add set-self
  concourse/pipelines/pipeline-set-pipeline.yaml
Labels: lgtm, approved, size/S

#452 Use jsonnet for RHUI pipeline
  concourse/pipelines/pipeline-set-pipeline.yaml
  concourse/pipelines/rhui-release.jsonnet
Labels: size/L, lgtm, approved

#455 Update container build instructions
  imagetest/README.md
Labels: size/XS, lgtm, approved
