Repository GoogleCloudPlatform/guest-test-infra, pull requests merged in 2022-12, with the labels that each got.

#569 RHEL 7.6 for SAP is EOL, stop building it.
  concourse/pipelines/linux-image-build.jsonnet
Labels: size/XS, lgtm, approved

#568 GVNIC test
  imagetest/fixtures.go
  imagetest/fixtures_test.go
  imagetest/test_suites/network/gvnic_test.go
  imagetest/test_suites/network/setup.go
Labels: size/L, lgtm, approved

#570 Add SQL Server 2022 release versions to Concourse
  concourse/pipelines/windows-image-build.jsonnet
Labels: lgtm, approved, size/S

#573 Add success/failure metrics to imgpublishjob
  concourse/pipelines/windows-image-build.jsonnet
Labels: lgtm, approved, size/S
