Repository GoogleCloudPlatform/guest-test-infra, pull requests merged in 2022-09, with the labels that each got.

#547 Enable testing of Ubuntu 22.10 (Kinetic Kudu) images
  concourse/pipelines/partner-image-validations.jsonnet
Labels: size/XS, lgtm, approved, needs-ok-to-test

#549 no auto deploy to prod; add eu-n-1 to staging
  concourse/pipelines/rhui-release.jsonnet
Labels: lgtm, approved, size/S

#551 publish RHUI images to prod
  concourse/pipelines/linux-image-build.jsonnet
Labels: size/XS, lgtm, approved

#550 Docker tests for Windows container images.
  imagetest/cmd/manager/main.go
  imagetest/test_suites/windows_containers/docker_container_test.go
  imagetest/test_suites/windows_containers/setup.go
  imagetest/utils/test_utils.go
Labels: size/L, lgtm, approved

#548 Enable testing of Ubuntu ARM64 images
  concourse/pipelines/partner-image-validations.jsonnet
Labels: lgtm, approved, size/S, ok-to-test

#553 Added support for Alma Linux boot test
  imagetest/test_suites/image_boot/image_boot_test.go
  imagetest/test_suites/image_boot/setup.go
Labels: size/XS, lgtm, approved

#554 Remove staging publication (except oslogin staging).
  concourse/pipelines/linux-image-build.jsonnet
  concourse/pipelines/partner-image-export.jsonnet
  concourse/pipelines/windows-image-build.jsonnet
Labels: lgtm, approved, size/M

#556 Remove unused partner exports. oslogin-staging publish is automatic
  concourse/pipelines/linux-image-build.jsonnet
  concourse/pipelines/partner-image-export.jsonnet
Labels: lgtm, approved, size/M

#557 add epel-release to package test
  imagetest/test_suites/image_validation/package_test.go
Labels: size/XS, lgtm, approved
