Repository GoogleCloudPlatform/guest-test-infra, pull requests merged in 2022-03, with the labels that each got.

#395 Fix license test for python2-futures.
  imagetest/test_suites/image_validation/license_test.go
Labels: size/XS, lgtm, approved

#396 container images: use workload ID
  container_images/daisy-builder/Dockerfile
  container_images/gobuild/Dockerfile
  container_images/gocheck/Dockerfile
  container_images/gointegtest/main.sh
Labels: size/XS, lgtm, approved

#397 Include packagebuild dir in daisy-builder
  concourse/pipelines/container-build.jsonnet
  container_images/daisy-builder/Dockerfile
Labels: lgtm, approved, size/S

#399 fix daisy-builder path
  container_images/daisy-builder/main.sh
Labels: size/XS, lgtm, approved

#400 Add gce_image_publish build
  concourse/pipelines/container-build.jsonnet
Labels: lgtm, approved, size/M

#402 Container builds: Add a tag with commit sha
  concourse/pipelines/container-build.jsonnet
Labels: lgtm, approved, size/S

#401 Daisy build: Add pre-release tests
  concourse/pipelines/container-build.jsonnet
Labels: size/L, lgtm, approved

#403 Allow newer SSH root user setting "prohibit-password".
  imagetest/test_suites/security/image_security_test.go
Labels: size/XS, lgtm, approved

#404 short circuit dns propagation
  concourse/templates/lego.libsonnet
Labels: size/XS, lgtm, approved

#405 cds image build: correct input
  concourse/pipelines/linux-image-build.jsonnet
Labels: size/XS, lgtm, approved

#406 Update EL9 package build to use centos-cloud.
  packagebuild/workflows/build_el9.wf.json
Labels: size/XS, lgtm, approved

#408 Updating 2012r2 name to match build-publish files
  concourse/pipelines/windows-image-build.jsonnet
Labels: lgtm, approved, size/S

#409 add forked crt to windows image build
  concourse/pipelines/windows-image-build.jsonnet
Labels: size/XS, lgtm, approved

#410 generate CSR
  concourse/pipelines/linux-image-build.jsonnet
  concourse/templates/lego.libsonnet
Labels: size/L, lgtm, approved

#412 Removing underscore replacement since the files currently use dashes
  concourse/pipelines/windows-image-build.jsonnet
Labels: size/XS, lgtm, approved

#394 Add SAP workload test job
  concourse/pipelines/linux-image-build.jsonnet
  concourse/scripts/sap_hana.tf
  concourse/scripts/sap_post_script.sh
Labels: size/L, lgtm, approved

#414 Add myself and remove lawrence from owners
  OWNERS
Labels: size/XS, lgtm, approved

#411 fix keyname
  concourse/pipelines/linux-image-build.jsonnet
Labels: size/XS, lgtm, approved

#415 Adding missing / to GCS Path
  concourse/pipelines/windows-image-build.jsonnet
Labels: size/XS, lgtm, approved

#416 cds build: split inputs
  concourse/pipelines/linux-image-build.jsonnet
Labels: lgtm, approved, size/S

#417 2012r2 --> 2012-r2
  concourse/pipelines/windows-image-build.jsonnet
Labels: lgtm, approved, size/S

#419 Remove Windows Server 2004 build (EOL)
  concourse/pipelines/windows-image-build.jsonnet
Labels: size/XS, lgtm, approved

#421 [concourse] build and publish debian-11-worker-amd64
  concourse/pipelines/debian-worker-image-build.yaml
Labels: size/L, lgtm, approved

#420 [concourse for ARM packages] support ARM packages build
  concourse/pipelines/guest-package-build.yaml
  packagebuild/workflows/build_deb11_arm64.wf.json
  packagebuild/workflows/build_package.wf.json
Labels: lgtm, approved, size/M

#422 add cleanerupper
  concourse/pipelines/container-build.jsonnet
  container_images/cleanerupper/Dockerfile
  container_images/cleanerupper/go.mod
  container_images/cleanerupper/go.sum
  container_images/cleanerupper/main.go
Labels: lgtm, approved, size/XXL

#423 remove unused arg 'gcs-key.credential'
  concourse/pipelines/bare-metal-image-build.yaml
  concourse/pipelines/debian-worker-image-build.yaml
Labels: lgtm, approved, size/S

#424 use golang:1.13 everywhere
  container_images/cleanerupper/Dockerfile
  container_images/concourse-metrics/Dockerfile
  container_images/gobuild/Dockerfile
  container_images/gointegtest/Dockerfile
  container_images/gotest/Dockerfile
  container_images/jsonnet-go/Dockerfile
  container_images/validate-integtest/Dockerfile
  imagetest/Dockerfile
Labels: lgtm, approved, size/S

#428 run post-build image tests in us-central1
  concourse/pipelines/linux-image-build.jsonnet
Labels: size/XS, lgtm, approved

#429 remove unused arg 'google_cloud_repo' for debian-11-worker-arm64
  concourse/pipelines/debian-worker-image-build.yaml
  packagebuild/workflows/build_deb11_arm64.wf.json
Labels: size/XS, lgtm, approved

#430 specify zone=us-central1-a for debian-11-worker-arm64
  concourse/pipelines/debian-worker-image-build.yaml
  concourse/tasks/daisy-build-images-debian.yaml
  packagebuild/workflows/build_deb11_arm64.wf.json
  packagebuild/workflows/build_package.wf.json
Labels: size/XS, lgtm, approved

#432 Modify zone of 'daisy-build-images-debian' to us-central1-a for arm compatibility
  concourse/tasks/daisy-build-images-debian.yaml
Labels: size/XS, lgtm, approved

#433 add GCE image resource
  concourse/pipelines/container-build.jsonnet
  container_images/gce-img-resource/Dockerfile
  container_images/gce-img-resource/README.md
  container_images/gce-img-resource/check/check_command.go
  container_images/gce-img-resource/cmd/check/main.go
  container_images/gce-img-resource/cmd/in/main.go
  container_images/gce-img-resource/in/in_command.go
  container_images/gce-img-resource/types.go
Labels: size/L, lgtm, approved

#434 fix prod publish arg name: source_gcs_path -> gcs_image_path
  concourse/pipelines/debian-worker-image-build.yaml
Labels: size/XS, lgtm, approved

#437 Separating windows package promotion steps
  concourse/pipelines/guest-package-build.yaml
Labels: size/L, lgtm, approved
