Repository GoogleCloudPlatform/guest-test-infra, pull requests merged in 2023-11, with the labels that each got.

#894 Bug fix
  imagetest/test_suites/metadata/startup_script_test.go
  imagetest/test_suites/ssh/host_key_test.go
Labels: size/XS, lgtm, approved

#895 oslogin: 2fa MDS entry will not always be present
  imagetest/test_suites/oslogin/oslogin_test.go
  imagetest/utils/metadata.go
Labels: lgtm, approved, size/S

#893 Imagetest local build support
  imagetest/Dockerfile
  imagetest/cmd/manager/main.go
  imagetest/local_build.sh
  imagetest/testworkflow.go
Labels: size/L, lgtm, approved

#896 Add the ability for TestVM to run on an instance from the beta API.
  imagetest/fixtures.go
  imagetest/fixtures_test.go
  imagetest/testworkflow.go
  imagetest/testworkflow_test.go
Labels: lgtm, approved, size/XL

#897 Update README.md with local testing commands
  imagetest/README.md
Labels: lgtm, approved, size/S

#898 Update packages in cloud-image-tests container and bump golang version to 1.20
  imagetest/Dockerfile
  imagetest/go.mod
Labels: size/XS, lgtm, approved

#899 Set NetworkPerformanceTier to TIER_1 on the t1 client vm
  imagetest/test_suites/networkperf/setup.go
Labels: size/XS, lgtm, approved

#900 Update README.md with manager instructions
  imagetest/README.md
Labels: size/XS, lgtm, approved

#901 Update owners.
  OWNERS
Labels: size/XS, lgtm, approved

#902 Removing Mirantis Docker builds from Concourse
  concourse/pipelines/windows-image-build-staging.jsonnet
  concourse/pipelines/windows-image-build-standard.jsonnet
  concourse/pipelines/windows-image-build.jsonnet
Labels: size/L, lgtm, approved

#903 Remove remaining container builds from Concourse
  concourse/pipelines/windows-image-build-staging.jsonnet
  concourse/pipelines/windows-image-build-standard.jsonnet
  concourse/pipelines/windows-image-build.jsonnet
Labels: size/L, lgtm, approved

#904 Warn about mixing GA and beta instance APIs when creating test suites
  imagetest/README.md
Labels: size/XS, lgtm, approved

#907 Revert "Add SEV_SNP and TDX enablement tests (#905)"
  imagetest/go.mod
  imagetest/go.sum
  imagetest/test_suites/cvm/cvm_test.go
  imagetest/test_suites/cvm/setup.go
Labels: size/L, lgtm, approved

#908 guest agent: add a pipeline for a development branch
  concourse/pipelines/guest-package-build.jsonnet
Labels: lgtm, approved, size/M

#913 Re-enable publish steps to allow testing
  concourse/pipelines/windows-image-build-mbr.jsonnet
Labels: lgtm, approved, size/S

#909 File sync call
  imagetest/test_suites/hotattach/hot_attach_test.go
Labels: lgtm, approved, size/S

#915 package-build: add missing field
  concourse/pipelines/guest-package-build.jsonnet
Labels: size/XS, lgtm, approved

#916 Revamp guest-test-infra presubmit checks
  container_images/citpresubmit/main.sh
  container_images/gotest/main.sh
  container_images/registry-image-forked/in_test.go
Labels: lgtm, approved, size/M

#918 guest-agent-dev: don't add tags to github
  concourse/pipelines/guest-package-build.jsonnet
Labels: size/XS, lgtm, approved

#919 Block CIT submission on successful workflow generation
  container_images/citpresubmit/main.sh
Labels: size/XS, lgtm, approved

#912 Wait for fio to finish installing on linux
  imagetest/test_suites/storageperf/iops_read_test.go
  imagetest/test_suites/storageperf/iops_write_test.go
  imagetest/test_suites/storageperf/setup.go
  imagetest/test_suites/storageperf/storage_perf_utils.go
Labels: lgtm, approved, size/M

#921 Select test projects evenly but in a randomized order
  imagetest/testworkflow.go
Labels: lgtm, approved, size/M

#910 Retry network performance results fetch three times
  imagetest/test_suites/networkperf/performance_test.go
  imagetest/test_suites/networkperf/startupscripts/netclient_startup.sh
  imagetest/test_suites/networkperf/startupscripts/windows_clientstartup.ps1
Labels: lgtm, approved, size/S

#922 Build and publish windows upgrade test container
  concourse/pipelines/container-build.jsonnet
Labels: size/XS, lgtm, approved

#920 Print string instead of float
  imagetest/test_suites/storageperf/iops_read_test.go
  imagetest/test_suites/storageperf/iops_write_test.go
  imagetest/test_suites/storageperf/storage_perf_utils.go
Labels: lgtm, approved, size/M

#924 Print vm name for failing tests
  imagetest/test_suites/storageperf/iops_read_test.go
  imagetest/test_suites/storageperf/iops_write_test.go
  imagetest/test_suites/storageperf/storage_perf_utils.go
Labels: lgtm, approved, size/M

#923 Correct windows upgrade tests dockerfile path
  concourse/pipelines/container-build.jsonnet
Labels: size/XS, lgtm, approved

#925 Correct typo in gce-windows-upgrade-test pipeline context
  concourse/pipelines/container-build.jsonnet
Labels: size/XS, lgtm, approved

#827 OsLogin Tests
  concourse/pipelines/guest-package-build.jsonnet
  imagetest/fixtures.go
  imagetest/go.mod
  imagetest/go.sum
  imagetest/test_suites/oslogin/oslogin_test.go
  imagetest/test_suites/oslogin/oslogin_utils.go
  imagetest/test_suites/oslogin/setup.go
  imagetest/test_suites/oslogin/ssh_test.go
  imagetest/utils/test_utils.go
Labels: lgtm, approved, size/XL

#928 Require the UEFI_COMPATIBLE flag for secure boot tests
  imagetest/test_suites/imageboot/setup.go
Labels: size/XS, lgtm, approved

#930 Skip tests on zypper install issue
  imagetest/test_suites/storageperf/iops_read_test.go
  imagetest/test_suites/storageperf/iops_write_test.go
  imagetest/test_suites/storageperf/storage_perf_utils.go
Labels: lgtm, approved, size/M

#931 Update excluded tests in Windows cit grouping
  concourse/pipelines/windows-image-build-mbr.jsonnet
Labels: size/XS, lgtm, approved

#934 package build: update golang to 1.21
  packagebuild/common.sh
Labels: size/XS, lgtm, approved

#935 Reduce Parallel Thread Count for Network Performance Tests for SUSE Images.
  imagetest/test_suites/networkperf/startupscripts/netclient_startup.sh
  imagetest/test_suites/networkperf/startupscripts/netserver_startup.sh
Labels: lgtm, approved, size/S

#936 Add SEV_SNP and TDX enablement tests to CVM suite.
  imagetest/go.mod
  imagetest/go.sum
  imagetest/test_suites/cvm/cvm_test.go
  imagetest/test_suites/cvm/setup.go
  imagetest/testworkflow.go
Labels: size/L, lgtm, approved

#938 Move CGO_ENABLED declaration from Dockerfile to local_build.sh
  imagetest/Dockerfile
  imagetest/local_build.sh
Labels: size/XS, lgtm, approved

#939 Search dmesg output in go for CVM tests and deduplicate test code
  imagetest/test_suites/cvm/cvm_test.go
Labels: lgtm, approved, size/M

#940 Don't delete resources named do-not-delete
  container_images/cleanerupper/go-cleanerupper/cleanerupper.go
  container_images/cleanerupper/go-cleanerupper/cleanerupper_test.go
Labels: lgtm, approved, size/S

#941 package build: downgrade golang to 1.21.3
  packagebuild/common.sh
Labels: size/XS, lgtm, approved

#942 Call cleanerupper after running a CIT suite to clean up any resources left behind by Daisy.
  container_images/cleanerupper/go-cleanerupper/cleanerupper.go
  container_images/cleanerupper/go-cleanerupper/cleanerupper_test.go
  imagetest/go.mod
  imagetest/go.sum
  imagetest/testworkflow.go
  imagetest/testworkflow_test.go
Labels: size/L, lgtm, approved

#945 Fix various issues with dockerfile builds
  concourse/pipelines/container-build.jsonnet
  imagetest/Dockerfile
  imagetest/README.md
  imagetest/local_build.sh
Labels: lgtm, approved, size/S
