Repository GoogleCloudPlatform/guest-test-infra, pull requests merged in 2023-10, with the labels that each got.

#819 Add guest attributes
  imagetest/cmd/wrapper/main.go
  imagetest/fixtures.go
  imagetest/testworkflow.go
  imagetest/testworkflow_test.go
  imagetest/utils/test_utils.go
Labels: lgtm, approved, size/M

#820 Ubuntu 16 fix
  imagetest/test_suites/storageperf/iops_read_test.go
  imagetest/test_suites/storageperf/iops_write_test.go
  imagetest/test_suites/storageperf/setup.go
Labels: lgtm, approved, size/M

#821 Rollback guest attribute call until fixed
  imagetest/cmd/wrapper/main.go
Labels: size/XS, lgtm, approved

#822 revert guest attribute
  imagetest/testworkflow.go
Labels: size/XS, lgtm, approved

#824 Fix prod image publish.
  concourse/pipelines/linux-image-build.jsonnet
Labels: lgtm, approved, size/S

#828 Skip debian 10 for gvnic machine types
  imagetest/test_suites/shapevalidation/setup.go
  imagetest/test_suites/storageperf/setup.go
Labels: lgtm, approved, size/S

#829 Add CIT to publish pipeline, without removing the publish step
  concourse/pipelines/linux-image-build.jsonnet
Labels: lgtm, approved, size/S

#832 Skip gvnic shape validation for rhel sap versions that don't support it
  imagetest/test_suites/shapevalidation/setup.go
Labels: size/XS, lgtm, approved

#830 Fork Concourse windows image build pipeline for MBR
  concourse/pipelines/windows-image-build-mbr.jsonnet
Labels: size/L, lgtm, approved

#831 Add wait for vm quota test workflow step, and functions to append quotas
  imagetest/cmd/manager/main.go
  imagetest/fixtures.go
  imagetest/go.mod
  imagetest/go.sum
  imagetest/test_suites/shapevalidation/setup.go
  imagetest/test_suites/storageperf/setup.go
  imagetest/testworkflow.go
Labels: size/L, lgtm, approved

#826 Add back guest attributes with fix for metadata shutdown test
  imagetest/cmd/wrapper/main.go
  imagetest/testworkflow.go
  imagetest/utils/test_utils.go
Labels: lgtm, approved, size/M

#833 Fix nil ptr in WaitForVMQuota
  imagetest/fixtures.go
  imagetest/fixtures_test.go
Labels: lgtm, approved, size/S

#835 Revert "Add back guest attributes with fix for metadata shutdown test…
  imagetest/cmd/wrapper/main.go
  imagetest/testworkflow.go
  imagetest/utils/test_utils.go
Labels: lgtm, approved, size/M

#834 docs: Update README.md with correct link to Kaniko Repository & Fix typos
  concourse/README.md
  concourse/pipelines/README.md
Labels: size/XS, lgtm, approved, ok-to-test

#836 Enable MBR Windows pipeline, remove standard Windows pipeline
  concourse/pipelines/pipeline-set-pipeline.yaml
Labels: size/XS, lgtm, approved

#838 Update MBR build pipeline image/workflow naming
  concourse/pipelines/windows-image-build-mbr.jsonnet
Labels: lgtm, approved, size/S

#839 Update image and sbom naming for MBR pipeline
  concourse/pipelines/windows-image-build-mbr.jsonnet
Labels: lgtm, approved, size/S

#840 Check for gve in gvnic tests as well
  imagetest/test_suites/network/gvnic_test.go
  imagetest/test_suites/networkperf/gvnic_test.go
Labels: size/XS, lgtm, approved

#842 Wait for CPUS instead of N1 CPUs during N1 shape validation
  imagetest/test_suites/shapevalidation/setup.go
Labels: size/XS, lgtm, approved

#843 Handle arm images in hotattach suite (use an appropriate machine type…
  imagetest/test_suites/hotattach/hot_attach_test.go
  imagetest/test_suites/hotattach/setup.go
Labels: lgtm, approved, size/S

#844 Update cli-tools-module-tests container to base off bullseye.
  container_images/cli-tools-module-tests/Dockerfile
Labels: size/XS, lgtm, approved

#846 Move VM build tasks out of gcp-guest.
  concourse/tasks/daisy-build-package-image.yaml
  concourse/tasks/package-gointegtest.yaml
Labels: size/XS, lgtm, approved

#845 Check quota less frequently
  imagetest/fixtures.go
Labels: size/XS, lgtm, approved

#849 Move hotattach to primary image tests.
  concourse/pipelines/linux-image-build.jsonnet
Labels: size/XS, lgtm, approved

#850 Exempt EL7 from C3D shape validation
  imagetest/test_suites/shapevalidation/setup.go
Labels: size/XS, lgtm, approved

#848 Shutdown Script Minor Change
  imagetest/fixtures.go
  imagetest/test_suites/metadata/setup.go
  imagetest/testworkflow.go
Labels: lgtm, approved, size/M

#854 Skip broken secureboot test on opensuse-leap arm
  imagetest/test_suites/imageboot/setup.go
Labels: size/XS, lgtm, approved

#852 RHEL for SAP BYOS and RHEL 9 BYOS for arm64
  concourse/pipelines/linux-image-build.jsonnet
Labels: size/XS, lgtm, approved

#853 Remove telemetry from non-prod windows pipelines
  concourse/pipelines/windows-image-build-mbr.jsonnet
  concourse/pipelines/windows-image-build-staging.jsonnet
  concourse/pipelines/windows-image-build-standard.jsonnet
Labels: size/L, lgtm, approved

#860 Remove 2012 R2 from prod windows build pipeline
  concourse/pipelines/windows-image-build.jsonnet
Labels: lgtm, approved, size/S

#859 Fix windows-image-build-standard publish-to-prod pipelines and align test configuration with linux pipelines
  concourse/pipelines/windows-image-build-standard.jsonnet
Labels: lgtm, approved, size/M

#841 Test pdbalanced performance on ARM64 images in storageperf
  imagetest/test_suites/storageperf/setup.go
  imagetest/test_suites/storageperf/storage_perf_utils.go
Labels: size/L, lgtm, approved

#863 Fix architecture check and vm zone in storage perf.
  imagetest/test_suites/storageperf/setup.go
Labels: size/XS, lgtm, approved

#864 Wait calls for hotattach
  imagetest/test_suites/hotattach/hot_attach_test.go
Labels: size/L, lgtm, approved

#855 Shutdown attribute
  imagetest/cmd/wrapper/main.go
  imagetest/testworkflow.go
  imagetest/utils/test_utils.go
Labels: lgtm, approved, size/M

#847 Add a wait for disk quota step
  imagetest/fixtures.go
  imagetest/fixtures_test.go
  imagetest/test_suites/storageperf/setup.go
  imagetest/testworkflow.go
Labels: size/L, lgtm, approved

#861 Catch up Windows Staging pipeline to current state
  concourse/pipelines/windows-image-build-staging.jsonnet
Labels: lgtm, approved, size/M

#868 Remove publish from mbr build
  concourse/pipelines/windows-image-build-mbr.jsonnet
Labels: lgtm, approved, size/S

#866 Guest attribute testing and network reboot setup
  imagetest/fixtures_test.go
  imagetest/test_suites/network/setup.go
  imagetest/testworkflow_test.go
Labels: size/L, lgtm, approved

#869 Quick style fix
  imagetest/test_suites/network/setup.go
Labels: size/XS, lgtm, approved

#865 Run networkperf on multiple machine types, defined in test setup.
  imagetest/test_suites/networkperf/performance_test.go
  imagetest/test_suites/networkperf/setup.go
Labels: size/L, lgtm, approved

#870 Stop skipping hotattach on arm
  imagetest/test_suites/hotattach/setup.go
Labels: size/XS, lgtm, approved

#872 Create disks for networkperf images based on VM zone
  imagetest/test_suites/networkperf/setup.go
Labels: lgtm, approved, size/S

#800 Refactor Testworkflow structure...
  imagetest/README.md
  imagetest/cmd/manager/main.go
  imagetest/fixtures_test.go
  imagetest/test_suites/cvm/setup.go
  imagetest/test_suites/hotattach/setup.go
  imagetest/test_suites/imageboot/setup.go
  imagetest/test_suites/metadata/setup.go
  imagetest/test_suites/network/setup.go
  imagetest/test_suites/networkperf/setup.go
  imagetest/test_suites/shapevalidation/setup.go
  imagetest/test_suites/storageperf/setup.go
  imagetest/test_suites/windowsimagevalidation/setup.go
  imagetest/testworkflow.go
  imagetest/testworkflow_test.go
  imagetest/utils/test_utils.go
Labels: lgtm, approved, size/XL

#875 Revert using the compute API for test result names.
  imagetest/testworkflow.go
Labels: size/XS, lgtm, approved

#877 Add a required features section to storage perf test config and specify GVNIC for instances that require it.
  imagetest/test_suites/storageperf/setup.go
Labels: lgtm, approved, size/M

#876 Use daisy instance struct
  imagetest/fixtures.go
  imagetest/fixtures_test.go
  imagetest/test_suites/hotattach/setup.go
  imagetest/test_suites/metadata/setup.go
  imagetest/test_suites/network/setup.go
  imagetest/test_suites/networkperf/setup.go
  imagetest/test_suites/shapevalidation/setup.go
  imagetest/test_suites/storageperf/setup.go
  imagetest/testworkflow.go
  imagetest/testworkflow_test.go
Labels: size/L, lgtm, approved

#878 Fetch machine type for test from compute api in networkperf
  imagetest/test_suites/networkperf/setup.go
Labels: lgtm, approved, size/M

#881 Report network tier correctly in networkperf
  imagetest/test_suites/networkperf/performance_test.go
  imagetest/test_suites/networkperf/setup.go
Labels: size/XS, lgtm, approved

#880 Move some tests from imagevalidation to packagevalidation
  imagetest/cmd/manager/main.go
  imagetest/test_suites/hostnamevalidation/hostname_validation_test.go
  imagetest/test_suites/hostnamevalidation/linux_license_test.go
  imagetest/test_suites/hostnamevalidation/setup.go
  imagetest/test_suites/packagevalidation/clock_test.go
  imagetest/test_suites/packagevalidation/license_test.go
  imagetest/test_suites/packagevalidation/package_test.go
  imagetest/test_suites/packagevalidation/setup.go
Labels: lgtm, approved, size/M

#882 Create licensevalidation suite
  imagetest/cmd/manager/main.go
  imagetest/test_suites/licensevalidation/license_test.go
  imagetest/test_suites/licensevalidation/linux_license_test.go
  imagetest/test_suites/licensevalidation/setup.go
  imagetest/test_suites/packagevalidation/setup.go
  imagetest/test_suites/windowsimagevalidation/image_validation_test.go
Labels: lgtm, approved, size/M

#883 More windows migration
  imagetest/test_suites/hostnamevalidation/hostname_validation_test.go
  imagetest/test_suites/hostnamevalidation/setup.go
  imagetest/test_suites/packagevalidation/clock_test.go
  imagetest/test_suites/packagevalidation/package_test.go
  imagetest/test_suites/packagevalidation/setup.go
  imagetest/test_suites/windowsimagevalidation/image_validation_test.go
  imagetest/utils/test_utils.go
Labels: size/L, lgtm, approved

#884 Migrate tests out of windows test suite
  imagetest/cmd/manager/main.go
  imagetest/test_suites/packagevalidation/driver_package_test.go
  imagetest/test_suites/packagevalidation/googet_test.go
  imagetest/test_suites/packagevalidation/setup.go
  imagetest/test_suites/windows/setup.go
Labels: lgtm, approved, size/M

#885 Deletewinvalidation
  imagetest/cmd/manager/main.go
  imagetest/test_suites/disk/disk_readwrite_test.go
  imagetest/test_suites/disk/disk_resize_test.go
  imagetest/test_suites/disk/setup.go
  imagetest/test_suites/packagevalidation/setup.go
  imagetest/test_suites/packagevalidation/windows_version_test.go
  imagetest/test_suites/windowsimagevalidation/setup.go
Labels: size/L, lgtm, approved

#888 Remove unnecessary promote-to-stable steps from guest package build pipeline
  concourse/pipelines/guest-package-build.jsonnet
Labels: size/L, lgtm, approved

#889 Remove SAP workload test (and required scripts from concourse)
  concourse/pipelines/linux-image-build.jsonnet
  concourse/scripts/sap_hana.tf
  concourse/scripts/sap_post_script.sh
Labels: size/L, lgtm, approved

#890 util: unify metadata code
  .gitignore
  imagetest/build.sh
  imagetest/cmd/wrapper/main.go
  imagetest/test_suites/disk/disk_resize_test.go
  imagetest/test_suites/hostnamevalidation/hostname_validation_test.go
  imagetest/test_suites/imageboot/image_boot_test.go
  imagetest/test_suites/licensevalidation/license_test.go
  imagetest/test_suites/licensevalidation/linux_license_test.go
  imagetest/test_suites/metadata/metadata_test.go
  imagetest/test_suites/metadata/shutdown_script_test.go
  imagetest/test_suites/metadata/startup_script_test.go
  imagetest/test_suites/network/alias_ip_test.go
  imagetest/test_suites/network/dhcp_test.go
  imagetest/test_suites/network/gvnic_test.go
  imagetest/test_suites/network/mtu_test.go
  imagetest/test_suites/network/multinic_minimal_network_test.go
  imagetest/test_suites/networkperf/gvnic_test.go
  imagetest/test_suites/networkperf/performance_test.go
  imagetest/test_suites/packagevalidation/clock_test.go
  imagetest/test_suites/packagevalidation/googet_test.go
  imagetest/test_suites/packagevalidation/package_test.go
  imagetest/test_suites/packagevalidation/windows_version_test.go
  imagetest/test_suites/security/image_security_test.go
  imagetest/test_suites/sql/sql_test.go
  imagetest/test_suites/ssh/host_key_test.go
  imagetest/test_suites/ssh/image_ssh_test.go
  imagetest/test_suites/storageperf/iops_read_test.go
  imagetest/test_suites/storageperf/iops_write_test.go
  imagetest/utils/metadata.go
  imagetest/utils/test_utils.go
Labels: size/L, lgtm, approved

#891 Add mTLS MDS tests to verify credentials exists
  imagetest/test_suites/mdsmtls/mds_mtls_test.go
  imagetest/test_suites/mdsmtls/setup.go
Labels: size/L, lgtm, approved

#892 oslogin: only test sshd's PAM config if 2fa is enabled
  imagetest/test_suites/oslogin/oslogin_test.go
Labels: lgtm, approved, size/M
