Repository GoogleCloudPlatform/guest-test-infra, pull requests merged in 2023-08, with the labels that each got.

#743 test: don't fail if we succeed to create marker file
  imagetest/test_suites/disk/disk_resize_test.go
  imagetest/test_suites/image_boot/image_boot_test.go
  imagetest/test_suites/network/alias_ip_test.go
Labels: lgtm, approved, size/S

#742 Allow test vm to have multiple disks
  imagetest/fixtures.go
  imagetest/testworkflow.go
  imagetest/testworkflow_test.go
Labels: lgtm, approved, size/M

#745 Change fatal to fatalf
  imagetest/test_suites/disk/disk_resize_test.go
  imagetest/test_suites/image_boot/image_boot_test.go
  imagetest/test_suites/network/alias_ip_test.go
Labels: size/XS, lgtm, approved

#746 Non-blocking Testsuite
  concourse/pipelines/guest-package-build.jsonnet
  concourse/pipelines/linux-image-build.jsonnet
  concourse/pipelines/partner-image-validations.jsonnet
  concourse/tasks/image-test-args.yaml
  imagetest/cmd/manager/main.go
  imagetest/test_suites/storage_perf/iops_print_test.go
  imagetest/test_suites/storage_perf/setup.go
Labels: lgtm, approved, size/M

#747 Support vm with multiple disks
  imagetest/fixtures.go
  imagetest/fixtures_test.go
  imagetest/test_suites/storage_perf/setup.go
  imagetest/testworkflow.go
  imagetest/testworkflow_test.go
Labels: size/L, lgtm, approved

#748 Allow hyperdisk testing by changing boot disk
  imagetest/test_suites/storage_perf/setup.go
  imagetest/testworkflow.go
Labels: size/XS, lgtm, approved

#749 guest-oslogin: exclude storage perf tests
  concourse/pipelines/guest-package-build.jsonnet
Labels: size/XS, lgtm, approved

#751 Fix unused import in network test suite.
  imagetest/test_suites/network/gvnic_test.go
Labels: size/XS, lgtm, approved

#750 fio read test
  imagetest/test_suites/storage_perf/iops_print_test.go
  imagetest/test_suites/storage_perf/iops_read_test.go
  imagetest/test_suites/storage_perf/setup.go
  imagetest/test_suites/storage_perf/storage_perf_utils.go
Labels: size/L, lgtm, approved

#753 Test systemd-timesyncd configuration on Debian 12
  imagetest/test_suites/image_validation/clock_test.go
Labels: lgtm, approved, size/S

#756 Change imagetest's image map to a project map
  imagetest/cmd/manager/main.go
Labels: size/L, lgtm, approved

#755 Add guidance on writing tests for Linux+Windows
  imagetest/README.md
Labels: lgtm, approved, size/M

#757 Update owners.
  OWNERS
Labels: size/XS, lgtm, approved

#754 Pass in machine type to fixtures
  imagetest/fixtures.go
  imagetest/fixtures_test.go
  imagetest/test_suites/storage_perf/setup.go
  imagetest/testworkflow.go
  imagetest/testworkflow_test.go
Labels: lgtm, approved, size/M

#759 Update image_boot test to support Windows boot testing
  imagetest/test_suites/image_boot/image_boot_test.go
Labels: size/L, lgtm, approved

#760 Add IsWindows to test utils
  imagetest/utils/test_utils.go
Labels: size/XS, lgtm, approved

#758 add startup scripts
  imagetest/test_suites/storage_perf/iops_read_test.go
  imagetest/test_suites/storage_perf/setup.go
  imagetest/test_suites/storage_perf/startupscripts/install_fio.ps1
  imagetest/test_suites/storage_perf/startupscripts/install_fio.sh
  imagetest/test_suites/storage_perf/storage_perf_utils.go
Labels: lgtm, approved, size/M

#752 Create gvnic jumbo frames performance test
  imagetest/cmd/manager/main.go
  imagetest/fixtures.go
  imagetest/test_suites/network_perf/gvnic_test.go
  imagetest/test_suites/network_perf/performance_test.go
  imagetest/test_suites/network_perf/setup.go
  imagetest/test_suites/network_perf/startupscripts/netclient_startup.sh
  imagetest/test_suites/network_perf/startupscripts/netserver_startup.sh
  imagetest/test_suites/network_perf/targets.txt
  imagetest/testworkflow.go
Labels: size/L, lgtm, approved

#762 Confirm a PK is enrolled when checking secure boot state on linux systems
  imagetest/test_suites/image_boot/image_boot_test.go
Labels: lgtm, approved, size/S

#765 rename test suites
  imagetest/README.md
  imagetest/cmd/manager/main.go
  imagetest/test_suites/imageboot/image_boot_test.go
  imagetest/test_suites/imageboot/setup.go
  imagetest/test_suites/imagevalidation/clock_test.go
  imagetest/test_suites/imagevalidation/image_validation_test.go
  imagetest/test_suites/imagevalidation/license_test.go
  imagetest/test_suites/imagevalidation/linux_license_test.go
  imagetest/test_suites/imagevalidation/package_test.go
  imagetest/test_suites/imagevalidation/setup.go
  imagetest/test_suites/networkperf/gvnic_test.go
  imagetest/test_suites/networkperf/performance_test.go
  imagetest/test_suites/networkperf/setup.go
  imagetest/test_suites/networkperf/startupscripts/netclient_startup.sh
  imagetest/test_suites/networkperf/startupscripts/netserver_startup.sh
  imagetest/test_suites/networkperf/targets.txt
  imagetest/test_suites/storageperf/iops_read_test.go
  imagetest/test_suites/storageperf/setup.go
  imagetest/test_suites/storageperf/startupscripts/install_fio.ps1
  imagetest/test_suites/storageperf/startupscripts/install_fio.sh
  imagetest/test_suites/storageperf/storage_perf_utils.go
  imagetest/test_suites/windowscontainers/docker_container_test.go
  imagetest/test_suites/windowscontainers/setup.go
  imagetest/test_suites/windowsimagevalidation/image_validation_test.go
  imagetest/test_suites/windowsimagevalidation/setup.go
Labels: lgtm, approved, size/M

#766 Fix test_utils return on runtime
  imagetest/utils/test_utils.go
Labels: size/XS, lgtm, approved

#770 Update Windows conditionals in boottest
  imagetest/test_suites/imageboot/image_boot_test.go
Labels: size/XS, lgtm, approved

#771 Remove underscore from concourse pipeline test exclusion
  concourse/pipelines/guest-package-build.jsonnet
  concourse/pipelines/linux-image-build.jsonnet
  concourse/pipelines/partner-image-validations.jsonnet
  concourse/tasks/image-test-args.yaml
Labels: lgtm, approved, size/S

#772 Expand secure boot test to cover supported images on ARM
  imagetest/test_suites/imageboot/image_boot_test.go
  imagetest/test_suites/imageboot/setup.go
Labels: lgtm, approved, size/M

#773 Create sql test suite
  imagetest/cmd/manager/main.go
  imagetest/test_suites/sql/setup.go
  imagetest/test_suites/sql/sql_test.go
Labels: lgtm, approved, size/M

#768 Fio windows testing
  imagetest/fixtures.go
  imagetest/test_suites/storageperf/iops_read_test.go
  imagetest/test_suites/storageperf/setup.go
  imagetest/test_suites/storageperf/startupscripts/install_fio.ps1
  imagetest/test_suites/storageperf/storage_perf_utils.go
Labels: lgtm, approved, size/M
