Repository GoogleCloudPlatform/guest-test-infra, pull requests merged in 2023-12, with the labels that each got.

#946 Print more detailed error message
  imagetest/test_suites/storageperf/storage_perf_utils.go
Labels: lgtm, approved, size/S

#951 Update redhat arm64 secure boot issue link
  imagetest/test_suites/imageboot/setup.go
Labels: size/XS, lgtm, approved

#947 Update TestGuestPackages
  imagetest/test_suites/packagevalidation/package_test.go
Labels: size/L, lgtm, approved

#952 package build: use private image for concourse metrics
  concourse/pipelines/guest-package-build.jsonnet
Labels: size/XS, lgtm, approved

#948 send google creds for all guest os owned registry images
  concourse/pipelines/artifact-releaser-test.jsonnet
  concourse/tasks/generate-timestamp.yaml
  concourse/tasks/gotest.yaml
  concourse/tasks/publish-coverage.yaml
  concourse/tasks/publish-job-result.yaml
  concourse/tasks/publish-time-since.yaml
  concourse/tasks/render-templates.yaml
  concourse/tasks/validate-integtest-result.yaml
Labels: lgtm, approved, size/S

#953 render-templates: use registry-image-forked
  concourse/tasks/render-templates.yaml
Labels: size/XS, lgtm, approved

#954 render-templates: use registry-image
  concourse/tasks/render-templates.yaml
Labels: size/XS, lgtm, approved

#955 pipeline-set: use registry-image-private
  concourse/pipelines/pipeline-set-pipeline.yaml
  concourse/tasks/render-templates.yaml
Labels: size/XS, lgtm, approved

#956 Define guest-image-private within render-templates.yaml
  concourse/tasks/render-templates.yaml
Labels: size/XS, lgtm, approved

#957 Use guest-image-private resource_type
  concourse/pipelines/pipeline-set-pipeline.yaml
  concourse/tasks/render-templates.yaml
Labels: size/XS, lgtm, approved

#958 Remove tag from registry-image-private fetch
  concourse/tasks/render-templates.yaml
Labels: size/XS, lgtm, approved

#959 Add tag to resource_type in pipeline-set-pipelines
  concourse/pipelines/pipeline-set-pipeline.yaml
Labels: size/XS, lgtm, approved

#960 render-template: enable debug for resource type
  concourse/pipelines/pipeline-set-pipeline.yaml
Labels: size/XS, lgtm, approved

#962 package build: add registry-image-private resource type
  concourse/pipelines/guest-package-build.jsonnet
Labels: size/XS, lgtm, approved, do-not-merge/hold

#963 package build: don't use google_auth for resource type
  concourse/pipelines/guest-package-build.jsonnet
Labels: size/XS, lgtm, approved

#964 Bump CIT go version from 1.20 to 1.21
  imagetest/Dockerfile
  imagetest/go.mod
Labels: size/XS, lgtm, approved

#967 Add try catch to ps1 networkperf startup scripts
  imagetest/test_suites/networkperf/startupscripts/windows_clientstartup.ps1
  imagetest/test_suites/networkperf/startupscripts/windows_serverstartup.ps1
Labels: size/XS, lgtm, approved

#969 Check for google-cloud-cli on all (non suse) distros, falling back to google-cloud-sdk if neccessary
  imagetest/test_suites/packagevalidation/package_test.go
Labels: lgtm, approved, size/S

#968 Define registry-image-private in a template and import it across pipelines that need it
  concourse/pipelines/artifact-releaser-test.jsonnet
  concourse/pipelines/partner-image-validations.jsonnet
  concourse/templates/common.libsonnet
Labels: lgtm, approved, size/S

#950 Move the mdsmtls test suite to a guestagent test suite to test agent features
  imagetest/cmd/manager/main.go
  imagetest/cmd/wrapper/main.go
  imagetest/test_suites/guestagent/mds_mtls_test.go
  imagetest/test_suites/guestagent/setup.go
  imagetest/test_suites/guestagent/telemetry.go
  imagetest/utils/metadata.go
Labels: size/L, lgtm, approved

#973 Remove RHEL 8.1 for SAP from build pipeline.
  concourse/pipelines/linux-image-build.jsonnet
Labels: size/XS, lgtm, approved

#970 Update Networkperf Tests
  imagetest/test_suites/networkperf/performance_test.go
  imagetest/test_suites/networkperf/setup.go
  imagetest/test_suites/networkperf/startupscripts/linux_clientstartup.sh
  imagetest/test_suites/networkperf/startupscripts/linux_common.sh
  imagetest/test_suites/networkperf/startupscripts/linux_serverstartup.sh
  imagetest/test_suites/networkperf/startupscripts/netclient_startup.sh
  imagetest/test_suites/networkperf/startupscripts/netserver_startup.sh
  imagetest/test_suites/networkperf/startupscripts/windows_clientstartup.ps1
  imagetest/test_suites/networkperf/startupscripts/windows_common.ps1
  imagetest/test_suites/networkperf/startupscripts/windows_serverstartup.ps1
Labels: size/L, lgtm, approved

#975 Update README
  imagetest/test_suites/README.md
  imagetest/test_suites/oslogin/README.md
Labels: size/L, lgtm, approved

#976 Add Missing # from Test Suites README
  imagetest/test_suites/README.md
Labels: size/XS, lgtm, approved

#965 Test that nvme udev rules are triggering and creating device symlinks from the name
  imagetest/test_suites/disk/block_device_naming_test.go
  imagetest/test_suites/disk/setup.go
Labels: lgtm, approved, size/M

#977 Require GVNIC for udev tests, required for machine families that support nvme
  imagetest/test_suites/disk/setup.go
Labels: size/XS, lgtm, approved

#978 Update README.md
  imagetest/test_suites/README.md
Labels: size/L, lgtm, approved

#983 Correct default statement in customhostname readme section
  imagetest/test_suites/README.md
Labels: size/XS, lgtm, approved

#980 Add better partner support in the security suite.
  imagetest/test_suites/security/image_security_test.go
Labels: lgtm, approved, size/M

#982 Delete package legality test
  imagetest/test_suites/README.md
  imagetest/test_suites/licensevalidation/license_test.go
  imagetest/test_suites/licensevalidation/setup.go
Labels: size/L, lgtm, approved

#984 Report actual and expected values for autoclean interval test failures
  imagetest/test_suites/security/image_security_test.go
Labels: size/XS, lgtm, approved

#986 Dump apt config from apt rather than parsing selected config files
  imagetest/test_suites/security/image_security_test.go
Labels: lgtm, approved, size/S

#988 Document shapevalidation
  imagetest/test_suites/README.md
Labels: lgtm, approved, size/S

#987 Add missing hostnamevalidation exceptions for opensuse
  imagetest/test_suites/hostnamevalidation/hostname_validation_test.go
Labels: size/XS, lgtm, approved

#993 Update guestagent suite
  imagetest/test_suites/guestagent/setup.go
  imagetest/test_suites/guestagent/snapshot_test.go
  imagetest/test_suites/guestagent/telemetry.go
  imagetest/test_suites/guestagent/telemetry_test.go
Labels: size/L, lgtm, approved

#994 Don't fail snapshot test when the agent configuration doesn't exist yet
  imagetest/test_suites/guestagent/snapshot_test.go
Labels: size/XS, lgtm, approved
