Repository GoogleCloudPlatform/guest-test-infra, pull requests merged in 2023-02, with the labels that each got.

#592 Older distros don't have GVNIC drivers.
  imagetest/test_suites/network/setup.go
Labels: size/XS, lgtm, approved

#593 feat: Update Ubuntu releases
  imagetest/cmd/manager/main.go
Labels: size/XS, lgtm, approved, ok-to-test

#591 Add sbom-destination input variable with .sbom.json file extension
  concourse/pipelines/linux-image-build.jsonnet
  concourse/templates/daisy.libsonnet
Labels: size/XS, lgtm, approved

#595 Add sbom dest local var
  concourse/templates/daisy.libsonnet
Labels: size/XS, lgtm, approved

#597 SBOM destination by replacing gcs_url suffix
  concourse/pipelines/linux-image-build.jsonnet
  concourse/templates/daisy.libsonnet
Labels: lgtm, approved, size/S

#598 Revert sbom destination bug
  concourse/templates/daisy.libsonnet
Labels: size/XS, lgtm, approved

#599 rpm build: make sure we have python3-devel available
  packagebuild/daisy_startupscript_rpm.sh
Labels: size/XS, lgtm, approved

#601 Fix GCS dir for yum-plugin-artifact-registry
  concourse/pipelines/guest-package-build.jsonnet
Labels: size/XS, lgtm, approved

#603 quotation mistake
  concourse/tasks/generate-id.yaml
Labels: size/XS, lgtm, approved

#604 Change name of outputs directory to conform with tee command
  concourse/tasks/generate-id.yaml
Labels: size/XS, lgtm, approved

#606 Remove extra parenthesis in the echo statement
  concourse/tasks/generate-id.yaml
Labels: size/XS, lgtm, approved

#594 Fork windows image build for staging builds
  concourse/pipelines/pipeline-set-pipeline.yaml
  concourse/pipelines/windows-image-build-staging.jsonnet
Labels: lgtm, approved, size/XL

#607 Sbom dest
  concourse/pipelines/linux-image-build.jsonnet
  concourse/tasks/generate-build-id-sbom.yaml
  concourse/templates/daisy.libsonnet
Labels: lgtm, approved, size/M

#608 Remove staging windows build from pipeline
  concourse/pipelines/pipeline-set-pipeline.yaml
Labels: size/XS, lgtm, approved

#609 add id generation to windows staging
  concourse/pipelines/windows-image-build-staging.jsonnet
Labels: lgtm, approved, size/S

#610 Change resource type for worker
  concourse/templates/common.libsonnet
Labels: size/XS, lgtm, approved

#611 Add comments for common id generation
  concourse/pipelines/linux-image-build.jsonnet
Labels: size/XS, lgtm, approved

#612 Re-introduce Windows staging env
  concourse/pipelines/pipeline-set-pipeline.yaml
  concourse/pipelines/windows-image-build-staging.jsonnet
Labels: size/XS, lgtm, approved

#613 Remove linskeyd from OWNERS file
  OWNERS
Labels: size/XS, lgtm, approved

#614 Removing Windows 8.1 from build pipelines
  concourse/pipelines/windows-image-build-staging.jsonnet
  concourse/pipelines/windows-image-build.jsonnet
Labels: lgtm, approved, size/S
