Repository GoogleCloudPlatform/guest-test-infra, pull requests merged in 2023-06, with the labels that each got.

#696 Increase CIT timeout to 45m. More test cases are running now.
  imagetest/cmd/manager/main.go
Labels: size/XS, lgtm, approved

#697 Fix googet build failure due to invalid json passed to jq
  packagebuild/daisy_startupscript_goo.sh
Labels: size/XS, lgtm, approved

#698 Cleanup partner image validation pipeline
  concourse/pipelines/partner-image-validations.jsonnet
Labels: lgtm, approved, size/M

#699 Update CIT tests for SLES
  imagetest/test_suites/image_validation/license_test.go
  imagetest/test_suites/network/dhcp_test.go
Labels: lgtm, approved, size/S

#702 Change Package resources in Artifact Releaser Test to Github Release Tags.
  concourse/pipelines/artifact-releaser-test.jsonnet
  concourse/templates/common.libsonnet
Labels: size/L, lgtm, approved

#704 Change time resource to trigger every 3h to match ARLE build intervals.
  concourse/pipelines/artifact-releaser-test.jsonnet
Labels: lgtm, approved, size/S

#706 Use bullseye base containers due to incompatibilites with bookworm based containers.
  container_images/build-essential/Dockerfile
  container_images/cleanerupper/Dockerfile
  container_images/flake8/Dockerfile
  container_images/gobuild/Dockerfile
  container_images/gocheck/Dockerfile
  container_images/gointegtest/Dockerfile
  container_images/gotest/Dockerfile
  container_images/jsonnet-go/Dockerfile
  container_images/validate-integtest/Dockerfile
Labels: lgtm, approved, size/S

#705 Fix minor issues with resources and skip_download field
  concourse/pipelines/artifact-releaser-test.jsonnet
Labels: size/XS, lgtm, approved

#707 Update README.md for sbom util gcs root
  packagebuild/README.md
Labels: size/XS, lgtm, approved

#708 Get compute-image-tools resource in publish image job, fix topic for uploading packages to staging.
  concourse/pipelines/artifact-releaser-test.jsonnet
Labels: size/XS, lgtm, approved

#703 Fix link formatting (markdown)
  imagetest/test_suites/README.md
Labels: size/XS, lgtm, approved

#709 sbom: fix sbom path on debian package build
  concourse/pipelines/guest-package-build.jsonnet
Labels: size/XS, lgtm, approved

#710 Add registry-image-forked resource type to artifact-releaser-test.
  concourse/pipelines/artifact-releaser-test.jsonnet
Labels: lgtm, approved, size/S

#711 Switch image publishing method from gcepublishtask to arlepublishtask
  concourse/pipelines/artifact-releaser-test.jsonnet
Labels: lgtm, approved, size/S

#712 Create separate publish task for artifact-releaser-test.
  concourse/pipelines/artifact-releaser-test.jsonnet
Labels: size/L, lgtm, approved

#714 windows: fix certgen upload resource name
  concourse/pipelines/guest-package-build.jsonnet
Labels: size/XS, lgtm, approved

#715 Update container dependencies and test dependencies
  container_images/cleanerupper/Dockerfile
  container_images/cleanerupper/go.mod
  container_images/cleanerupper/go.sum
  container_images/gobuild/Dockerfile
  container_images/gocheck/Dockerfile
  container_images/gointegtest/Dockerfile
  container_images/gointegtest/common.sh
  container_images/gointegtest/integ-test-all.wf.json
  container_images/gointegtest/run_integ_tests.sh
  container_images/gotest/Dockerfile
  container_images/jsonnet-go/Dockerfile
  container_images/validate-integtest/Dockerfile
  container_images/validate-integtest/validate-result.sh
Labels: lgtm, approved, size/XXL
