Repository GoogleCloudPlatform/guest-test-infra, pull requests merged in 2023-04, with the labels that each got.

#641 sbom: start publishing sboms to its own bucket
  concourse/pipelines/linux-image-build.jsonnet
  concourse/tasks/generate-build-id-sbom.yaml
  concourse/templates/common.libsonnet
Labels: size/XS, lgtm, approved

#642 SBOM bucket
  concourse/templates/common.libsonnet
Labels: size/XS, lgtm, approved

#643 gcssbom resource: use the resource's "constructor"
  concourse/pipelines/linux-image-build.jsonnet
  concourse/templates/common.libsonnet
Labels: lgtm, approved, size/S

#644 arlepublishtask: make sure to pass the sbom's path
  concourse/pipelines/linux-image-build.jsonnet
  concourse/templates/arle.libsonnet
Labels: lgtm, approved, size/S

#645 arle: pass sbom_gcs_path to all jobs of interest
  concourse/pipelines/linux-image-build.jsonnet
  concourse/templates/arle.libsonnet
Labels: size/XS, lgtm, approved

#646 sbom: start passing sbom's gcs path to arle's pubsub
  concourse/pipelines/linux-image-build.jsonnet
  concourse/templates/arle.libsonnet
Labels: lgtm, approved, size/S

#648 Add bookworm to Concourse image build
  concourse/pipelines/linux-image-build.jsonnet
  concourse/templates/common.libsonnet
Labels: size/XS, lgtm, approved

#649 Deal with CentOS Stream failures.
  imagetest/test_suites/image_boot/image_boot_test.go
  imagetest/test_suites/image_validation/image_validation_test.go
Labels: lgtm, approved, size/S

#652 Cleanup unused baremetal image pipeline.
  concourse/pipelines/README.md
  concourse/pipelines/bare-metal-image-build.yaml
  concourse/pipelines/pipeline-set-pipeline.yaml
Labels: lgtm, approved, size/XL

#651 Cleanup old partner test config.
  concourse/pipelines/partner-image-validations.jsonnet
Labels: lgtm, approved, size/M
