Repository GoogleCloudPlatform/guest-test-infra, pull requests merged in 2023-05, with the labels that each got.

#654 Update Windows build pipeline container image builds
  concourse/pipelines/windows-image-build.jsonnet
Labels: lgtm, approved, size/S

#655 Revert the boot time test change for CentOS Stream 8 (they fixed it).
  imagetest/test_suites/image_boot/image_boot_test.go
Labels: size/XS, lgtm, approved

#656 Fix image validation test.
  imagetest/test_suites/image_validation/image_validation_test.go
Labels: lgtm, approved, size/S

#657 Update arle.libsonnet
  concourse/templates/arle.libsonnet
Labels: size/XS, lgtm, approved

#659 Also skip custom hostname test on RHEL 9.
  imagetest/test_suites/image_validation/image_validation_test.go
Labels: size/XS, lgtm, approved

#660 Add package build script
  packagebuild/test_build.sh
Labels: lgtm, approved, size/M

#661 Use GCC 10 for EL7 rpm package builds
  packagebuild/daisy_startupscript_rpm.sh
  packagebuild/test_build.sh
Labels: lgtm, approved, size/S

#662 Split the packages installation into two separate commands
  packagebuild/daisy_startupscript_rpm.sh
Labels: size/XS, lgtm, approved

#663 Splitting DockerEE and DockerCE due to daisy variables
  concourse/pipelines/windows-image-build.jsonnet
Labels: size/L, lgtm, approved

#664 sbom: introduce the sbom generation calls to packages build
  packagebuild/daisy_startupscript_deb.sh
  packagebuild/daisy_startupscript_rpm.sh
Labels: lgtm, approved, size/M

#666 Skip custom hostname test on all EL9 builds.
  imagetest/test_suites/image_validation/image_validation_test.go
Labels: lgtm, approved, size/S

#665 sbom: fix rpm file lookup
  packagebuild/daisy_startupscript_rpm.sh
Labels: size/XS, lgtm, approved

#668 sbom: fix the path we are looking up source rpms
  packagebuild/daisy_startupscript_rpm.sh
Labels: size/XS, lgtm, approved

#669 sbom: set sbomutil as executable
  packagebuild/daisy_startupscript_deb.sh
  packagebuild/daisy_startupscript_rpm.sh
Labels: size/XS, lgtm, approved

#670 sbom: move it all to common.sh
  packagebuild/common.sh
  packagebuild/daisy_startupscript_deb.sh
  packagebuild/daisy_startupscript_rpm.sh
Labels: size/L, lgtm, approved

#671 sbom: don't try to create manifest when copying gcs object
  packagebuild/common.sh
Labels: size/XS, lgtm, approved

#667 Fix custom hostname test.
  imagetest/test_suites/image_validation/image_validation_test.go
Labels: lgtm, approved, size/M

#672 sbom: fix an inverted boolean check
  packagebuild/common.sh
Labels: size/XS, lgtm, approved

#673 Add RHEL 8.8 and 9.2 for SAP builds.
  concourse/pipelines/linux-image-build.jsonnet
Labels: size/XS, lgtm, approved

#674 sbom: fix a type in the argument passed to generate_and_push_sbom
  packagebuild/daisy_startupscript_deb.sh
  packagebuild/daisy_startupscript_rpm.sh
Labels: size/XS, lgtm, approved

#675 sbom: normalize sbomutil and sbom_file paths
  packagebuild/common.sh
Labels: size/XS, lgtm, approved

#677 sbom: add support to arm64
  concourse/pipelines/guest-package-build.jsonnet
  packagebuild/common.sh
Labels: size/XS, lgtm, approved

#678 Packages SBOM
  packagebuild/daisy_startupscript_deb.sh
  packagebuild/daisy_startupscript_goo.sh
Labels: lgtm, approved, size/S

#679 sbom: fix the call to generate_and_push_sbom for rpm build
  packagebuild/daisy_startupscript_rpm.sh
Labels: size/XS, lgtm, approved

#680 Don't fail fast for package and image test builds.
  concourse/pipelines/guest-package-build.jsonnet
Labels: size/XS, lgtm, approved

#681 sbom: add sbomfile to ARLE's pubsub call
  concourse/pipelines/guest-package-build.jsonnet
Labels: lgtm, approved, size/M

#682 sbom: enable sbom generation for googet packages
  packagebuild/daisy_startupscript_goo.sh
Labels: size/XS, lgtm, approved

#683 On Debian 12 the guest is not getting the right search domains
  packagebuild/daisy_startupscript_deb.sh
Labels: size/XS, lgtm, approved

#684 packages: fix compute-image-tools git-resource definition
  concourse/pipelines/guest-package-build.jsonnet
Labels: size/XS, lgtm, approved

#685 Fix missing comma.
  concourse/pipelines/guest-package-build.jsonnet
Labels: size/XS, lgtm, approved

#686 Migrate from syft source to sbom util source
  concourse/pipelines/linux-image-build.jsonnet
Labels: lgtm, approved, size/S

#687 Fix sbom util path name error
  concourse/pipelines/linux-image-build.jsonnet
Labels: size/XS, lgtm, approved

#688 Fix a couple test cases for Debian 12.
  imagetest/test_suites/image_validation/image_validation_test.go
  imagetest/test_suites/network/setup.go
  imagetest/test_suites/security/image_security_test.go
Labels: lgtm, approved, size/M

#689 Debian SBOM publishing
  concourse/pipelines/linux-image-build.jsonnet
Labels: lgtm, approved, size/S

#691 Re-enable multi-nic test for Debian 12.
  imagetest/test_suites/network/setup.go
Labels: size/XS, lgtm, approved

#693 Windows sbom resource
  concourse/pipelines/windows-image-build.jsonnet
Labels: lgtm, approved, size/M

#694 Pass in sbom_destination
  concourse/pipelines/windows-image-build.jsonnet
Labels: lgtm, approved, size/S

#695 Pass sbom destination on the correct line
  concourse/pipelines/windows-image-build.jsonnet
Labels: size/XS, lgtm, approved
