Repository GoogleCloudPlatform/guest-test-infra, pull requests merged in 2023-09, with the labels that each got.

#775 write iops
  imagetest/test_suites/storageperf/iops_read_test.go
  imagetest/test_suites/storageperf/iops_write_test.go
  imagetest/test_suites/storageperf/setup.go
  imagetest/test_suites/storageperf/startupscripts/install_fio.ps1
  imagetest/test_suites/storageperf/storage_perf_utils.go
Labels: size/L, lgtm, approved

#779 Stop building RHEL 7.7 for SAP- it is EOL.
  concourse/pipelines/linux-image-build.jsonnet
Labels: size/XS, lgtm, approved

#777 Update networkperf test suite to support windows images
  imagetest/fixtures.go
  imagetest/test_suites/networkperf/performance_test.go
  imagetest/test_suites/networkperf/setup.go
  imagetest/test_suites/networkperf/startupscripts/windows_clientstartup.ps1
  imagetest/test_suites/networkperf/startupscripts/windows_serverstartup.ps1
Labels: size/L, lgtm, approved

#782 Add shapevalidation test
  concourse/pipelines/guest-package-build.jsonnet
  concourse/pipelines/image-release-testing.jsonnet
  concourse/pipelines/linux-image-build.jsonnet
  concourse/pipelines/partner-image-validations.jsonnet
  concourse/pipelines/pipeline-set-pipeline.yaml
  concourse/tasks/image-test-args.yaml
  imagetest/cmd/manager/main.go
  imagetest/fixtures.go
  imagetest/fixtures_test.go
  imagetest/test_suites/shapevalidation/setup.go
  imagetest/test_suites/shapevalidation/shapevalidation_test.go
  imagetest/test_suites/shapevalidation/sysinfo_linux.go
  imagetest/test_suites/shapevalidation/sysinfo_windows.go
  imagetest/testworkflow.go
Labels: lgtm, approved, size/XL

#781 Throughput testing
  imagetest/test_suites/storageperf/iops_read_test.go
  imagetest/test_suites/storageperf/iops_write_test.go
  imagetest/test_suites/storageperf/setup.go
  imagetest/test_suites/storageperf/storage_perf_utils.go
  imagetest/utils/test_utils.go
Labels: size/L, lgtm, approved

#784 Skip FQDN test on EL9.
  imagetest/test_suites/imagevalidation/image_validation_test.go
Labels: lgtm, approved, size/S

#783 Remove debian-12 arm secure boot exception
  imagetest/test_suites/imageboot/setup.go
Labels: size/XS, lgtm, approved

#785 Hot Attach Test Suite
  concourse/pipelines/guest-package-build.jsonnet
  concourse/pipelines/linux-image-build.jsonnet
  concourse/pipelines/partner-image-validations.jsonnet
  concourse/tasks/image-test-args.yaml
  imagetest/cmd/manager/main.go
  imagetest/test_suites/README.md
  imagetest/test_suites/hotattach/hot_attach_test.go
  imagetest/test_suites/hotattach/setup.go
  imagetest/test_suites/shapevalidation/setup.go
  imagetest/testworkflow.go
Labels: size/L, lgtm, approved

#786 Enable C3D shape validation
  imagetest/test_suites/shapevalidation/setup.go
Labels: size/XS, lgtm, approved

#778 Create CVM Test Suite.
  imagetest/cmd/manager/main.go
  imagetest/fixtures.go
  imagetest/test_suites/cvm/cvm_test.go
  imagetest/test_suites/cvm/setup.go
Labels: lgtm, approved, size/M

#787 Add release testing set prior to publishing linux images to prod, inc…
  concourse/pipelines/image-release-testing.jsonnet
  concourse/pipelines/linux-image-build.jsonnet
  concourse/pipelines/pipeline-set-pipeline.yaml
  imagetest/test_suites/shapevalidation/setup.go
Labels: size/L, lgtm, approved

#789 Enable release testing in windows release pipelines
  concourse/pipelines/linux-image-build.jsonnet
  concourse/pipelines/windows-image-build-standard.jsonnet
Labels: lgtm, approved, size/M

#788 Fiomachinetypes
  imagetest/test_suites/storageperf/iops_read_test.go
  imagetest/test_suites/storageperf/iops_write_test.go
  imagetest/test_suites/storageperf/setup.go
  imagetest/testworkflow.go
  imagetest/utils/test_utils.go
Labels: size/L, lgtm, approved

#790 Fix nil error in build
  imagetest/testworkflow.go
Labels: lgtm, approved, size/S

#793 Skip arm images in CVM testing
  imagetest/test_suites/cvm/setup.go
Labels: size/XS, lgtm, approved

#794 Update Metadata Test Suite to include Windows
  imagetest/fixtures.go
  imagetest/test_suites/metadata/scripts/daemonScriptLinux.sh
  imagetest/test_suites/metadata/scripts/daemonScriptWindows.ps1
  imagetest/test_suites/metadata/scripts/shutdownScriptLinux.sh
  imagetest/test_suites/metadata/scripts/shutdownScriptWindows.ps1
  imagetest/test_suites/metadata/scripts/shutdownTimeLinux.sh
  imagetest/test_suites/metadata/scripts/shutdownTimeWindows.ps1
  imagetest/test_suites/metadata/scripts/startupScriptLinux.sh
  imagetest/test_suites/metadata/scripts/startupScriptWindows.ps1
  imagetest/test_suites/metadata/setup.go
  imagetest/test_suites/metadata/shutdown_script_test.go
  imagetest/test_suites/metadata/startup_script_test.go
Labels: size/L, lgtm, approved

#795 Add rhel sap 8.1 and 8.2 cvm exclusions
  imagetest/test_suites/cvm/setup.go
Labels: size/XS, lgtm, approved

#792 oslogin test: update tests based on new authorization implementation
  imagetest/test_suites/oslogin/oslogin_test.go
Labels: lgtm, approved, size/S

#796 Add x64Shape and arm64Shape flags to control default machine shapes p…
  imagetest/cmd/manager/main.go
  imagetest/testworkflow.go
Labels: lgtm, approved, size/M

#791 Benchmark
  imagetest/test_suites/hotattach/hot_attach_test.go
  imagetest/test_suites/hotattach/setup.go
  imagetest/test_suites/storageperf/iops_read_test.go
  imagetest/test_suites/storageperf/iops_write_test.go
  imagetest/test_suites/storageperf/setup.go
  imagetest/test_suites/storageperf/storage_perf_utils.go
  imagetest/utils/test_utils.go
Labels: size/L, lgtm, approved

#797 Only count CPUs and NUMA nodes that are online on linux
  imagetest/test_suites/shapevalidation/sysinfo_linux.go
Labels: lgtm, approved, size/M

#799 Change directory setup to be cleaner, make success output make more sense
  imagetest/test_suites/networkperf/performance_test.go
  imagetest/test_suites/networkperf/setup.go
  imagetest/test_suites/networkperf/targets/default_targets.txt
  imagetest/test_suites/networkperf/targets/tier1_targets.txt
Labels: lgtm, approved, size/S

#798 Add SQL Power Plan and Remote Connectivity Tests
  imagetest/test_suites/sql/setup.go
  imagetest/test_suites/sql/sql_test.go
  imagetest/test_suites/sql/startupscripts/remote_auth_client_setup.ps1
  imagetest/test_suites/sql/startupscripts/remote_auth_server_setup.ps1
Labels: size/L, lgtm, approved

#801 Int64 fix
  imagetest/test_suites/hotattach/hot_attach_test.go
  imagetest/test_suites/hotattach/setup.go
  imagetest/test_suites/storageperf/iops_read_test.go
  imagetest/test_suites/storageperf/iops_write_test.go
  imagetest/test_suites/storageperf/storage_perf_utils.go
  imagetest/utils/test_utils.go
Labels: lgtm, approved, size/S

#802 Skip the c3d family during storageperf testing on windows 2012 and 2016
  imagetest/test_suites/storageperf/setup.go
Labels: size/XS, lgtm, approved

#803 Update README documentation for networkperf and CVM test suites.
  imagetest/test_suites/README.md
Labels: lgtm, approved, size/S

#805 Add CIT presubmit container
  concourse/pipelines/container-build.jsonnet
  container_images/citpresubmit/Dockerfile
  container_images/citpresubmit/main.sh
Labels: lgtm, approved, size/M

#806 pd balanced tests
  imagetest/test_suites/storageperf/iops_read_test.go
  imagetest/test_suites/storageperf/iops_write_test.go
  imagetest/test_suites/storageperf/setup.go
  imagetest/test_suites/storageperf/storage_perf_utils.go
Labels: size/L, lgtm, approved

#808 Install go-junit-report in the cit presubmit container
  container_images/citpresubmit/Dockerfile
Labels: size/XS, lgtm, approved

#809 Change to imagetest directory in CIT presubmit even when $BUILD_DIR is unset
  container_images/citpresubmit/main.sh
Labels: size/XS, lgtm, approved

#810 Install all dependencies for dockerfile
  container_images/citpresubmit/Dockerfile
Labels: size/XS, lgtm, approved

#812 Fix existing presubmit failures that slipped through the presubmit gap.
  imagetest/fixtures.go
  imagetest/utils/test_utils.go
Labels: size/XS, lgtm, approved

#807 Fix json unmarshal error
  imagetest/test_suites/storageperf/setup.go
  imagetest/utils/test_utils.go
Labels: lgtm, approved, size/S

#813 Remove dash in linux command
  imagetest/utils/test_utils.go
Labels: size/XS, lgtm, approved

#814 Fix el7 disk partition condition
  imagetest/utils/test_utils.go
Labels: size/XS, lgtm, approved

#815 Hotattach fix, storageperf machine types
  imagetest/test_suites/hotattach/hot_attach_test.go
  imagetest/test_suites/hotattach/setup.go
  imagetest/test_suites/storageperf/setup.go
  imagetest/test_suites/storageperf/storage_perf_utils.go
Labels: lgtm, approved, size/S

#816 Windows write test fix
  imagetest/test_suites/storageperf/iops_read_test.go
  imagetest/test_suites/storageperf/iops_write_test.go
  imagetest/test_suites/storageperf/setup.go
  imagetest/test_suites/storageperf/startupscripts/install_fio.ps1
  imagetest/test_suites/storageperf/storage_perf_utils.go
Labels: lgtm, approved, size/S

#817 Pass down machine types through TestWorkflow
  imagetest/cmd/manager/main.go
  imagetest/fixtures.go
  imagetest/fixtures_test.go
  imagetest/test_suites/networkperf/performance_test.go
  imagetest/test_suites/networkperf/setup.go
  imagetest/testworkflow.go
  imagetest/testworkflow_test.go
Labels: size/L, lgtm, approved

#818 Set h3 region
  imagetest/test_suites/storageperf/setup.go
Labels: size/XS, lgtm, approved
