Repository GoogleCloudPlatform/guest-test-infra, pull requests merged in 2023-03, with the labels that each got.

#622 RHEL 9 for SAP image build.
  concourse/pipelines/linux-image-build.jsonnet
Labels: size/XS, lgtm, approved

#621 Removing RHUI image build and release process
  concourse/pipelines/linux-image-build.jsonnet
  concourse/pipelines/pipeline-set-pipeline.yaml
  concourse/pipelines/rhui-release.jsonnet
Labels: size/L, lgtm, approved

#623 Fix license tests for RHEL 9 for SAP.
  imagetest/test_suites/image_validation/license_test.go
  imagetest/test_suites/image_validation/linux_license_test.go
Labels: size/XS, lgtm, approved

#624 Fix missing variable in worker builds.
  concourse/pipelines/debian-worker-image-build.yaml
Labels: size/XS, lgtm, approved

#620 Update build to go1.19.6 as 1.18 is EOL, update tests to match go version
  container_images/gobuild/Dockerfile
  container_images/gocheck/Dockerfile
  container_images/gointegtest/Dockerfile
  container_images/gotest/Dockerfile
  packagebuild/common.sh
Labels: lgtm, approved, size/S

#626 Fix sbom file pattern for all Debian images
  concourse/pipelines/linux-image-build.jsonnet
Labels: size/XS, lgtm, approved

#627 Replace go get calls with go install
  container_images/gocheck/Dockerfile
  container_images/gointegtest/Dockerfile
  container_images/gotest/Dockerfile
Labels: size/XS, lgtm, approved

#629 Cover is not a binary, no need to install it
  container_images/gotest/Dockerfile
Labels: size/XS, lgtm, approved

#628 registry-image-forked: remove go download
  container_images/registry-image-forked/dockerfiles/alpine/Dockerfile
  container_images/registry-image-forked/dockerfiles/ubuntu/Dockerfile
Labels: size/XS, lgtm, approved

#630 Fix 'registry-image-forked' build
  concourse/pipelines/container-build.jsonnet
  container_images/registry-image-forked/dockerfiles/alpine/Dockerfile
  container_images/registry-image-forked/dockerfiles/ubuntu/Dockerfile
Labels: size/XS, lgtm, approved

#631 registry-image-forked: fix failing testsuite
  container_images/registry-image-forked/suite_test.go
  imagetest/test_suites/disk/disk_resize_test.go
  imagetest/test_suites/image_boot/image_boot_test.go
  imagetest/test_suites/image_validation/clock_test.go
  imagetest/test_suites/image_validation/image_validation_test.go
  imagetest/test_suites/image_validation/license_test.go
  imagetest/test_suites/image_validation/linux_license_test.go
  imagetest/test_suites/image_validation/package_test.go
  imagetest/test_suites/metadata/metadata_test.go
  imagetest/test_suites/metadata/shutdown_script_test.go
  imagetest/test_suites/metadata/startup_script_test.go
  imagetest/test_suites/network/alias_ip_test.go
  imagetest/test_suites/network/dhcp_test.go
  imagetest/test_suites/network/gvnic_test.go
  imagetest/test_suites/network/mtu_test.go
  imagetest/test_suites/network/multinic_minimal_network_test.go
  imagetest/test_suites/oslogin/oslogin_test.go
  imagetest/test_suites/security/image_security_test.go
  imagetest/test_suites/ssh/host_key_test.go
  imagetest/test_suites/ssh/image_ssh_test.go
  imagetest/test_suites/windows/driver_package_test.go
  imagetest/test_suites/windows/googet_test.go
  imagetest/test_suites/windows_containers/docker_container_test.go
  imagetest/test_suites/windows_image_validation/image_validation_test.go
Labels: size/L, lgtm, approved

#632 fix go build directives all across the repo.
  imagetest/test_suites/disk/disk_resize_test.go
  imagetest/test_suites/image_boot/image_boot_test.go
  imagetest/test_suites/image_validation/clock_test.go
  imagetest/test_suites/image_validation/image_validation_test.go
  imagetest/test_suites/image_validation/license_test.go
  imagetest/test_suites/image_validation/linux_license_test.go
  imagetest/test_suites/image_validation/package_test.go
  imagetest/test_suites/metadata/metadata_test.go
  imagetest/test_suites/metadata/shutdown_script_test.go
  imagetest/test_suites/metadata/startup_script_test.go
  imagetest/test_suites/network/alias_ip_test.go
  imagetest/test_suites/network/dhcp_test.go
  imagetest/test_suites/network/gvnic_test.go
  imagetest/test_suites/network/mtu_test.go
  imagetest/test_suites/network/multinic_minimal_network_test.go
  imagetest/test_suites/oslogin/oslogin_test.go
  imagetest/test_suites/security/image_security_test.go
  imagetest/test_suites/ssh/host_key_test.go
  imagetest/test_suites/ssh/image_ssh_test.go
  imagetest/test_suites/windows/driver_package_test.go
  imagetest/test_suites/windows/googet_test.go
  imagetest/test_suites/windows_containers/docker_container_test.go
  imagetest/test_suites/windows_image_validation/image_validation_test.go
Labels: lgtm, approved, size/M

#633 Update Golang version in `cloud-image-tests` for consistency
  imagetest/Dockerfile
Labels: size/XS, lgtm, approved

#634 Fix OpenSSL version mismatch
  imagetest/Dockerfile
Labels: size/XS, lgtm, approved

#635 Add CE Docker builds to Windows pipeline
  concourse/pipelines/windows-image-build-staging.jsonnet
  concourse/pipelines/windows-image-build.jsonnet
Labels: lgtm, approved, size/S

#636 Update workflow names in pipeline def
  concourse/pipelines/windows-image-build-staging.jsonnet
  concourse/pipelines/windows-image-build.jsonnet
Labels: size/XS, lgtm, approved

#637 debian packages: fetch sbomutil from gcs
  packagebuild/daisy_startupscript_deb.sh
  packagebuild/daisy_startupscript_rpm.sh
  packagebuild/workflows/build_deb10.wf.json
  packagebuild/workflows/build_deb11.wf.json
  packagebuild/workflows/build_deb11_arm64.wf.json
  packagebuild/workflows/build_deb9.wf.json
  packagebuild/workflows/build_el6.wf.json
  packagebuild/workflows/build_el7.wf.json
  packagebuild/workflows/build_el8.wf.json
  packagebuild/workflows/build_el8_arm64.wf.json
  packagebuild/workflows/build_el9.wf.json
  packagebuild/workflows/build_el9_arm64.wf.json
Labels: lgtm, approved, size/M

#638 googet packages: fetch sbomutil from gcs
  packagebuild/daisy_startupscript_goo.sh
  packagebuild/workflows/build_goo.wf.json
Labels: lgtm, approved, size/S

#639 package build: pass down sbom_util_gcs_root
  concourse/pipelines/guest-package-build.jsonnet
  packagebuild/workflows/build_package.wf.json
Labels: size/XS, lgtm, approved

#640 package build(sbom): sbomutil fetching
  packagebuild/daisy_startupscript_deb.sh
  packagebuild/daisy_startupscript_goo.sh
  packagebuild/daisy_startupscript_rpm.sh
Labels: lgtm, approved, size/S
