Repository GoogleCloudPlatform/guest-test-infra, pull requests merged in 2024-06, with the labels that each got.

#1184 Stop building CentOS Stream 8.
  concourse/pipelines/artifact-releaser-test.jsonnet
  concourse/pipelines/linux-image-build.jsonnet
  container_images/gointegtest/integ-test-all.wf.json
Labels: lgtm, approved, size/M

#1165 Make it possible to release windows images with CIT failures
  concourse/pipelines/windows-image-build-mbr.jsonnet
  concourse/pipelines/windows-image-build-staging.jsonnet
  concourse/pipelines/windows-image-build-standard.jsonnet
  concourse/pipelines/windows-image-build.jsonnet
Labels: lgtm, approved, size/M

#1186 Add Arm osconfig files for Debian
  concourse/pipelines/guest-package-build.jsonnet
Labels: size/XS, lgtm, approved

#1189 Small fixes for apt packages
  concourse/pipelines/guest-package-build.jsonnet
Labels: lgtm, approved, size/S

#1190 Fix GCS path for apt transport
  concourse/pipelines/guest-package-build.jsonnet
Labels: size/XS, lgtm, approved

#1191 Fix apt transport sbom path
  concourse/pipelines/guest-package-build.jsonnet
Labels: size/XS, lgtm, approved

#1187 Fix default state of runtests in windows-image-build*
  concourse/pipelines/windows-image-build-mbr.jsonnet
  concourse/pipelines/windows-image-build-standard.jsonnet
  concourse/pipelines/windows-image-build.jsonnet
Labels: lgtm, approved, size/M

#1192 Use start time in Ms as the filename
  concourse/pipelines/linux-image-build.jsonnet
  concourse/pipelines/windows-image-build.jsonnet
  concourse/tasks/generate-hash.yaml
Labels: size/XS, lgtm, approved

#1193 Fix yum and dnf plugin paths
  concourse/pipelines/guest-package-build.jsonnet
Labels: lgtm, approved, size/S

#1194 Update local file name variable in generate hash
  concourse/tasks/generate-hash.yaml
Labels: size/XS, lgtm, approved

#1195 Fix dnf and yum naming
  concourse/pipelines/guest-package-build.jsonnet
Labels: size/XS, lgtm, approved

#1196 Fix arm package file naming for dnf plugin
  concourse/pipelines/guest-package-build.jsonnet
Labels: size/XS, lgtm, approved

#1198 Generate hash on the correct file
  concourse/tasks/generate-hash.yaml
Labels: size/XS, lgtm, approved

#1199 Pass in windows sha hash
  concourse/pipelines/windows-image-build.jsonnet
Labels: size/XS, lgtm, approved

#1200 Only print the hash and not the file name
  concourse/tasks/generate-hash.yaml
Labels: size/XS, lgtm, approved

#1197 Add RHEL 8.10 for SAP builds.
  concourse/pipelines/linux-image-build.jsonnet
Labels: size/XS, lgtm, approved

#1201 Add support for COS milestones (+109, +105)
  concourse/pipelines/guest-package-build.jsonnet
Labels: size/XS, lgtm, approved, ok-to-test

#1202 Pass in el9 instead of el8 arm for el9 yum plugin
  concourse/pipelines/guest-package-build.jsonnet
Labels: size/XS, lgtm, approved

#1203 Remove calls to sha256 sum
  concourse/pipelines/linux-image-build.jsonnet
  concourse/pipelines/windows-image-build.jsonnet
  concourse/templates/arle.libsonnet
Labels: lgtm, approved, size/S

#1204 Add support for the sbom shasum text file resource
  concourse/pipelines/linux-image-build.jsonnet
  concourse/pipelines/windows-image-build.jsonnet
  concourse/tasks/generate-build-id-shasum.yaml
  concourse/templates/arle.libsonnet
  concourse/templates/common.libsonnet
  concourse/templates/daisy.libsonnet
Labels: size/L, lgtm, approved

#1205 Fix shaum typo
  concourse/pipelines/linux-image-build.jsonnet
Labels: size/XS, lgtm, approved

#1207 pass in linux hash
  concourse/pipelines/linux-image-build.jsonnet
Labels: size/XS, lgtm, approved

#1206 Stop building CentOS 7, RHEL 7, RHEL 7 for SAP, and Debian 10.
  concourse/pipelines/linux-image-build.jsonnet
Labels: size/XS, lgtm, approved

#1208 Pass in correct parameter for windows hash
  concourse/pipelines/windows-image-build.jsonnet
Labels: size/XS, lgtm, approved

#1210 Getsha
  concourse/pipelines/linux-image-build.jsonnet
Labels: size/XS, lgtm, approved
