Repository GoogleCloudPlatform/guest-test-infra, pull requests merged in 2024-05, with the labels that each got.

#1152 Stop building RHEL 8.2 for SAP- EOL.
  concourse/pipelines/linux-image-build.jsonnet
Labels: size/XS, lgtm, approved

#1153 Start building RHEL 9.4 for SAP.
  concourse/pipelines/linux-image-build.jsonnet
Labels: size/XS, lgtm, approved

#1155 Fix CIT on SQL Server
  imagetest/test_suites/loadbalancer/loadbalancer_test.go
  imagetest/test_suites/security/image_security_test.go
Labels: lgtm, approved, size/M

#1154 Add COS configs to the concourse pipeline
  concourse/pipelines/guest-package-build.jsonnet
Labels: lgtm, approved, size/M, ok-to-test

#1145 Require n4 shapevalidation for linux image releases
  concourse/pipelines/linux-image-build.jsonnet
Labels: size/XS, lgtm, approved

#1156 Update install_package_cos.wf.json path to the correct path (add /cos)
  concourse/pipelines/guest-package-build.jsonnet
Labels: size/XS, lgtm, approved, ok-to-test

#1157 Wait for services to start on windows
  imagetest/test_suites/packagevalidation/windows_version_test.go
Labels: lgtm, approved, size/M

#1160 Pass commit-sha into COS preloading scripts (not package-version)
  concourse/pipelines/guest-package-build.jsonnet
Labels: size/XS, lgtm, approved, needs-ok-to-test

#1161 Pass in image family (not full path to image family)
  concourse/pipelines/guest-package-build.jsonnet
Labels: size/XS, lgtm, approved, needs-ok-to-test

#1163 Fix CIT build job
  concourse/pipelines/container-build.jsonnet
Labels: lgtm, approved, size/S

#1164 Fix branch name
  concourse/pipelines/container-build.jsonnet
Labels: size/XS, lgtm, approved

#1167 Update CIT to run only during testing publish for Windows
  concourse/pipelines/windows-image-build.jsonnet
Labels: size/XS, lgtm, approved

#1168 Update prepublish task prod --> testing
  concourse/pipelines/windows-image-build.jsonnet
Labels: lgtm, approved, size/S

#1169 Win11 24h2 preview and sql server 2022 on win2025 preview
  concourse/pipelines/windows-image-build.jsonnet
Labels: approved, size/S

#1166 Compute sha 256 hash
  concourse/pipelines/linux-image-build.jsonnet
  concourse/pipelines/windows-image-build.jsonnet
  concourse/tasks/generate-hash.yaml
  concourse/templates/arle.libsonnet
Labels: lgtm, approved, size/M

#1171 Use container with gcloud
  concourse/tasks/generate-hash.yaml
Labels: size/XS, lgtm, approved

#1172 Finish adding AR tasks
  concourse/pipelines/guest-package-build.jsonnet
Labels: lgtm, approved, size/M

#1173 Remove rapture concourse tasks
  concourse/pipelines/guest-package-build.jsonnet
Labels: size/L, lgtm, approved

#1174 Remove staging promotion task
  concourse/pipelines/guest-package-build.jsonnet
Labels: size/L, lgtm, approved

#1175 Fix osconfig file path
  concourse/pipelines/guest-package-build.jsonnet
Labels: size/XS, approved

#1176 Introduce a stable build and release pipeline for guest-agent.
  concourse/pipelines/guest-package-build.jsonnet
Labels: lgtm, approved, size/S

#1177 Move guest-agent stable branch to topic-stable.
  concourse/pipelines/guest-package-build.jsonnet
Labels: size/XS, lgtm, approved

#1178 Temporarily disable cit tests on cos image.
  concourse/pipelines/guest-package-build.jsonnet
Labels: size/XS, lgtm, approved

#1179 bump parallel count to 15 for cit package tests.
  concourse/pipelines/guest-package-build.jsonnet
Labels: size/XS, lgtm, approved

#1180 temporarily disable cos derived image build.
  concourse/pipelines/guest-package-build.jsonnet
Labels: size/XS, lgtm, approved

#1181 enable stable releases upload.
  concourse/pipelines/guest-package-build.jsonnet
Labels: size/XS, lgtm, approved

#1182 use package instead of repo_name for tagging.
  concourse/pipelines/guest-package-build.jsonnet
Labels: lgtm, approved, size/S

#1183 make sure we upload stable guest-agent to the same dir as the main one.
  concourse/pipelines/guest-package-build.jsonnet
Labels: size/XS, lgtm, approved
