Repository GoogleCloudPlatform/guest-test-infra, pull requests merged in 2024-09, with the labels that each got.

#1231 Exclude known-failing mdsroutes test from image build but not guest-a…
  concourse/pipelines/linux-image-build.jsonnet
  concourse/pipelines/partner-image-validations.jsonnet
  concourse/pipelines/windows-image-build-mbr.jsonnet
  concourse/pipelines/windows-image-build-staging.jsonnet
  concourse/pipelines/windows-image-build-standard.jsonnet
  concourse/pipelines/windows-image-build.jsonnet
Labels: lgtm, approved, size/S

#1232 Make ubuntu accelerator prototype image pipelines
  concourse/pipelines/linux-image-build.jsonnet
Labels: lgtm, approved, size/S

#1233 Force latest version to clear cache
  concourse/pipelines/container-build.jsonnet
Labels: size/XS, lgtm, approved

#1234 Fix repo definition for kaniko
  concourse/pipelines/container-build.jsonnet
Labels: size/XS, lgtm, approved

#1236 Remove debian11-arm64 from guest package build
  concourse/pipelines/guest-package-build.jsonnet
Labels: lgtm, approved, size/S

#1235 Add other COS LTS milestones
  concourse/pipelines/guest-package-build.jsonnet
Labels: lgtm, approved, size/S, needs-ok-to-test

#1237 Include test suites instead of excluding
  concourse/pipelines/linux-image-build.jsonnet
  concourse/pipelines/windows-image-build.jsonnet
Labels: size/XS, lgtm, approved

#1238 Filter for exact suite names
  concourse/pipelines/linux-image-build.jsonnet
  concourse/pipelines/windows-image-build-mbr.jsonnet
  concourse/pipelines/windows-image-build-staging.jsonnet
  concourse/pipelines/windows-image-build-standard.jsonnet
  concourse/pipelines/windows-image-build.jsonnet
Labels: lgtm, approved, size/S

#1239 Use a single capturing group in image build filters
  concourse/pipelines/linux-image-build.jsonnet
  concourse/pipelines/windows-image-build-mbr.jsonnet
  concourse/pipelines/windows-image-build-staging.jsonnet
  concourse/pipelines/windows-image-build-standard.jsonnet
  concourse/pipelines/windows-image-build.jsonnet
Labels: lgtm, approved, size/S

#1240 Add registry-image-private to debian-worker-image-build pipeline
  concourse/pipelines/debian-worker-image-build.yaml
Labels: size/XS, lgtm, approved

#1241 Don't redefine resource_types
  concourse/pipelines/debian-worker-image-build.yaml
Labels: size/XS, lgtm, approved

#1242 Build guest-agent for debian 12 ARM and update worker.
  concourse/pipelines/guest-package-build.jsonnet
Labels: lgtm, approved, size/S

#1243 Add rocky to accelerator pipeline
  concourse/pipelines/linux-image-build.jsonnet
Labels: size/XS, lgtm, approved
