Repository GoogleCloudPlatform/guest-test-infra, pull requests merged in 2024-08, with the labels that each got.

#1227 Clean load balancer resources in cleanerupper image.
  container_images/cleanerupper/go-cleanerupper/cleanerupper.go
  container_images/cleanerupper/go-cleanerupper/cleanerupper_test.go
  container_images/cleanerupper/go-cleanerupper/go.mod
  container_images/cleanerupper/go-cleanerupper/go.sum
  container_images/cleanerupper/go.mod
  container_images/cleanerupper/go.sum
  container_images/cleanerupper/main.go
Labels: lgtm, approved, size/XXL

#1228 Revert "Exclude mdsmtls from image and package release pipelines unti…
  concourse/pipelines/guest-package-build.jsonnet
  concourse/pipelines/linux-image-build.jsonnet
  concourse/pipelines/partner-image-validations.jsonnet
  concourse/pipelines/windows-image-build-mbr.jsonnet
  concourse/pipelines/windows-image-build-staging.jsonnet
  concourse/pipelines/windows-image-build-standard.jsonnet
  concourse/pipelines/windows-image-build.jsonnet
Labels: lgtm, approved, size/S

#1229 Revert "Revert "Exclude mdsmtls from image and package release pipelines unti…"
  concourse/pipelines/guest-package-build.jsonnet
  concourse/pipelines/linux-image-build.jsonnet
  concourse/pipelines/partner-image-validations.jsonnet
  concourse/pipelines/windows-image-build-mbr.jsonnet
  concourse/pipelines/windows-image-build-staging.jsonnet
  concourse/pipelines/windows-image-build-standard.jsonnet
  concourse/pipelines/windows-image-build.jsonnet
Labels: lgtm, approved, size/S

#1230 Remove Debian 11 arm from concourse build
  concourse/pipelines/linux-image-build.jsonnet
Labels: size/XS, lgtm, approved
