Repository GoogleCloudPlatform/guest-test-infra, pull requests merged in 2024-11, with the labels that each got.

#1286 Add extra_repo to guest-agent-dev pipeline
  concourse/pipelines/guest-package-build.jsonnet
Labels: size/L, lgtm, approved

#1288 Remove osconfig package builds.
  concourse/pipelines/artifact-releaser-test.jsonnet
  concourse/pipelines/guest-package-build.jsonnet
Labels: size/L, lgtm, approved

#1287 Test passing in cit suite filter as a list with override
  concourse/pipelines/linux-image-build.jsonnet
Labels: lgtm, approved, size/S

#1289 Fix old reference to citsuite
  concourse/pipelines/linux-image-build.jsonnet
Labels: size/XS, lgtm, approved

#1285 Add arm64 variants for CentOS Stream 9, RHEL 8, and AlmaLinux 9
  concourse/pipelines/linux-image-build.jsonnet
Labels: size/XS, lgtm, approved

#1291 Update cit filtering to use append instead of replace method
  concourse/pipelines/linux-image-build.jsonnet
Labels: size/XS, lgtm, approved

#1294 Test using default registry-image resource
  concourse/pipelines/windows-image-build-staging.jsonnet
Labels: size/XS, lgtm, approved

#1295 Add NIC naming tests and package manager tests to guest-configs release pipeline
  concourse/pipelines/guest-package-build.jsonnet
Labels: size/XS, lgtm, approved

#1298 Update work_dir for accelerator image builds
  concourse/pipelines/linux-image-build.jsonnet
Labels: size/XS, lgtm, approved

#1299 Switch rocky-8 from 550 to latest
  concourse/pipelines/linux-image-build.jsonnet
Labels: size/XS, lgtm, approved

#1297 Move rocky accelerator under EL builds
  concourse/pipelines/linux-image-build.jsonnet
Labels: size/XS, lgtm, approved

#1301 update builds to occur starting between 10:30 and 11:00 AM
  concourse/pipelines/linux-image-build.jsonnet
  concourse/pipelines/windows-image-build.jsonnet
Labels: lgtm, approved, size/S

#1302 fix time format for pipeline triggers
  concourse/pipelines/linux-image-build.jsonnet
  concourse/pipelines/windows-image-build.jsonnet
Labels: size/XS, lgtm, approved

#1303 change initial_version to bool instead of string
  concourse/pipelines/linux-image-build.jsonnet
  concourse/pipelines/windows-image-build.jsonnet
Labels: size/XS, lgtm, approved

#1305 revert "Test OSLogin on images before publishing (#1250)"
  concourse/pipelines/linux-image-build.jsonnet
Labels: lgtm, approved, size/S

#1296 Add metrics to windows staging pipeline using public registry image resource
  concourse/pipelines/windows-image-build-staging.jsonnet
Labels: lgtm, approved, size/M

#1304 Fork Linux build pipeline for development purposes
  concourse/pipelines/linux-image-build-dev.jsonnet
  concourse/pipelines/pipeline-set-pipeline.yaml
Labels: size/L, lgtm, approved

#1307 Fix Rocky Accelerator publish gsc_dir
  concourse/pipelines/linux-image-build.jsonnet
Labels: size/XS, lgtm, approved

#1309 Drop "-with" prefix from remaining accelerator image names
  concourse/pipelines/linux-image-build.jsonnet
Labels: size/XS, lgtm, approved

#1310 Sync Dev pipeline to reflect current prod pipelines
  concourse/pipelines/linux-image-build-dev.jsonnet
Labels: lgtm, approved, size/S

#1312 Switch accelerator gcs-dir to rocky-linux in linux-image-build-dev
  concourse/pipelines/linux-image-build-dev.jsonnet
Labels: size/XS, lgtm, approved

#1313 SQL on 2025, cleanup, cit on c3
  concourse/pipelines/windows-image-build.jsonnet
Labels: lgtm, approved, size/M

#1314 Update linux-image-build and linux-image-build-dev cit invocations
  concourse/pipelines/linux-image-build-dev.jsonnet
  concourse/pipelines/linux-image-build.jsonnet
  concourse/templates/common.libsonnet
Labels: lgtm, approved, size/M

#1318 Allow extra, custom test tasks in image build pipelines
  concourse/pipelines/linux-image-build-dev.jsonnet
  concourse/pipelines/linux-image-build.jsonnet
Labels: lgtm, approved, size/M
