Repository GoogleCloudPlatform/guest-test-infra, pull requests merged in 2024-07, with the labels that each got.

#1212 Update guest package release pipelines
  concourse/pipelines/guest-package-build.jsonnet
Labels: size/L, lgtm, approved

#1211 Add step to load shasum in windows publish
  concourse/pipelines/windows-image-build.jsonnet
Labels: lgtm, approved, size/S

#1214 Add COS back to the guest-agent release pipeline
  concourse/pipelines/guest-package-build.jsonnet
Labels: size/XS, lgtm, approved

#1215 Update args to install_packag_cos.wf.json
  concourse/pipelines/guest-package-build.jsonnet
Labels: size/XS, lgtm, approved, needs-ok-to-test

#1216 Use kaniko:latest
  concourse/pipelines/container-build.jsonnet
Labels: size/XS, lgtm, approved

#1217 Revert "Use kaniko:latest"
  concourse/pipelines/container-build.jsonnet
Labels: size/XS, lgtm, approved

#1218 Force kaniko to run to deal with cgroupsv2 change
  concourse/pipelines/container-build.jsonnet
Labels: size/XS, lgtm, approved

#1219 Removing deprecated 2014 and 2012 references from builds
  concourse/pipelines/windows-image-build-mbr.jsonnet
  concourse/pipelines/windows-image-build-staging.jsonnet
  concourse/pipelines/windows-image-build-standard.jsonnet
  concourse/pipelines/windows-image-build.jsonnet
Labels: lgtm, approved, size/M

#1220 Allo guest agent or guest agent stable to be the package path
  concourse/pipelines/guest-package-build.jsonnet
Labels: lgtm, approved, size/M

#1221 Use guest-agent-stable as the gcs directory
  concourse/pipelines/guest-package-build.jsonnet
Labels: size/XS, lgtm, approved

#1222 Temporarily disable COS derived image builds and tests
  concourse/pipelines/guest-package-build.jsonnet
Labels: lgtm, approved, size/S

#1223 Revert "Temporarily disable COS derived image builds and tests"
  concourse/pipelines/guest-package-build.jsonnet
Labels: lgtm, approved, size/S

#1224 Exclude mdsmtls from image and package release pipelines until rollout is finished
  concourse/pipelines/guest-package-build.jsonnet
  concourse/pipelines/linux-image-build.jsonnet
  concourse/pipelines/partner-image-validations.jsonnet
  concourse/pipelines/windows-image-build-mbr.jsonnet
  concourse/pipelines/windows-image-build-staging.jsonnet
  concourse/pipelines/windows-image-build-standard.jsonnet
  concourse/pipelines/windows-image-build.jsonnet
Labels: lgtm, approved, size/S

#1225 Bump go sdk version to latest
  container_images/gointegtest/common.sh
  packagebuild/common.sh
Labels: size/XS, lgtm, approved

#1226 Filter LSSD where hotattach is filtered or excluded
  concourse/pipelines/guest-package-build.jsonnet
  concourse/pipelines/partner-image-validations.jsonnet
  concourse/tasks/image-test-args.yaml
Labels: size/XS, lgtm, approved
