Repository GoogleCloudPlatform/guest-test-infra, pull requests merged in 2024-01, with the labels that each got.

#990 Test that startup and shutdown scripts are not executed on agent reinstallation
  imagetest/test_suites/metadata/shutdown_script_test.go
  imagetest/test_suites/metadata/startup_script_test.go
Labels: size/L, lgtm, approved

#995 Windows password test
  imagetest/test_suites/cvm/setup.go
  imagetest/test_suites/guestagent/setup.go
  imagetest/test_suites/guestagent/windows_password_test.go
  imagetest/test_suites/hotattach/hot_attach_test.go
  imagetest/test_suites/oslogin/oslogin_utils.go
  imagetest/test_suites/oslogin/ssh_test.go
  imagetest/utils/test_utils.go
Labels: size/L, lgtm, approved

#998 Add a fallback command to retry reinstalling guest agent during startup/shutdown script testing
  imagetest/test_suites/metadata/shutdown_script_test.go
  imagetest/test_suites/metadata/startup_script_test.go
Labels: lgtm, approved, size/S

#997 Skip telemetry testing when the agent never mentions it.
  imagetest/test_suites/guestagent/telemetry_test.go
Labels: lgtm, approved, size/M

#999 Build centos-7-predictable-nic
  concourse/pipelines/linux-image-build.jsonnet
Labels: size/XS, lgtm, approved

#1000 Add aliases for apt reinstall in metadata suite
  imagetest/test_suites/metadata/shutdown_script_test.go
  imagetest/test_suites/metadata/startup_script_test.go
Labels: size/XS, lgtm, approved

#1001 Allow override compute client endpoint
  imagetest/cmd/manager/main.go
  imagetest/local_build.sh
  imagetest/testworkflow.go
  imagetest/testworkflow_test.go
Labels: lgtm, approved, size/M

#1004 Disable centos-7-predictable-nic-builds
  concourse/pipelines/linux-image-build.jsonnet
Labels: size/XS, lgtm, approved

#1006 package_test: we haven't published a rocky 8 for arm with google-cloud-cli
  imagetest/test_suites/packagevalidation/package_test.go
Labels: size/XS, lgtm, approved

#1003 Check snap for packages when available
  imagetest/test_suites/packagevalidation/package_test.go
Labels: lgtm, approved, size/M

#1005 Test guest flush snapshots with VSS on windows
  imagetest/test_suites/guestagent/setup.go
  imagetest/test_suites/guestagent/snapshot_test.go
Labels: size/L, lgtm, approved

#1007 Revert "package_test: we haven't published a rocky 8 for arm with google-cloud-cli (#1006)"
  imagetest/test_suites/packagevalidation/package_test.go
Labels: size/XS, lgtm, approved

#1008 package_test: define a generic package rules structure
  imagetest/test_suites/packagevalidation/package_test.go
Labels: size/L, lgtm, approved

#1011 Skip checking for google-cloud-cli on sles and suse
  imagetest/test_suites/packagevalidation/package_test.go
Labels: size/XS, lgtm, approved

#1010 Add windows support in security suite
  imagetest/test_suites/security/image_security_test.go
Labels: lgtm, approved, size/S

#1013 Spelling correction in metadata test suite.
  imagetest/test_suites/metadata/shutdown_script_test.go
Labels: size/XS, lgtm, approved

#1012 Don't create windowscontainers or sql VMs if the image being tested isn't windows
  imagetest/test_suites/sql/setup.go
  imagetest/test_suites/windowscontainers/setup.go
Labels: size/L, lgtm, approved

#1014 Retry reinstalling guest-agent on suse when it fails
  imagetest/test_suites/metadata/shutdown_script_test.go
  imagetest/test_suites/metadata/startup_script_test.go
Labels: size/XS, lgtm, approved

#1015 Only run sql suite tests on windows SQL server images
  imagetest/test_suites/sql/setup.go
Labels: size/XS, lgtm, approved

#1002 Hyperdisk test case commands
  imagetest/test_suites/storageperf/iops_read_test.go
  imagetest/test_suites/storageperf/iops_write_test.go
  imagetest/test_suites/storageperf/setup.go
  imagetest/test_suites/storageperf/startupscripts/install_fio.ps1
  imagetest/test_suites/storageperf/storage_perf_utils.go
Labels: size/L, lgtm, approved

#1016 Remove header manually when an OS is too old to support the -H flag in ss
  imagetest/test_suites/security/image_security_test.go
Labels: lgtm, approved, size/S

#1017 Add ssh testing support for windows
  imagetest/test_suites/guestagent/telemetry_test.go
  imagetest/test_suites/security/image_security_test.go
  imagetest/test_suites/security/setup.go
  imagetest/test_suites/ssh/host_key_test.go
  imagetest/test_suites/ssh/image_ssh_test.go
  imagetest/test_suites/ssh/setup.go
  imagetest/utils/test_utils.go
Labels: size/L, lgtm, approved

#1019 Skip running alias ip tests on windows, skip creating the multinic vm at all when there's nothing to test
  imagetest/test_suites/network/setup.go
Labels: lgtm, approved, size/M

#1018 Pdbalancefill
  imagetest/test_suites/packagevalidation/package_test.go
  imagetest/test_suites/storageperf/setup.go
  imagetest/test_suites/storageperf/storage_perf_utils.go
Labels: size/L, lgtm, approved

#1020 Check DHCP settings on windows
  imagetest/test_suites/network/dhcp_test.go
Labels: lgtm, approved, size/M

#1022 Auto delete mounted disks
  imagetest/testworkflow.go
Labels: size/XS, lgtm, approved

#1009 Test windows-sysprep-specialize
  imagetest/test_suites/metadata/setup.go
  imagetest/test_suites/metadata/sysprep_test.go
Labels: lgtm, approved, size/S

#1021 In windows security tests, add an adminstrator to the test vm and check the ssh config in reference to that user
  imagetest/test_suites/security/image_security_test.go
Labels: lgtm, approved, size/S

#1023 Implement TestSockets in windows
  imagetest/test_suites/security/image_security_test.go
Labels: lgtm, approved, size/M

#1025 Add a prep command for guest agent reinstallation
  imagetest/test_suites/metadata/metadata_utils.go
  imagetest/test_suites/metadata/shutdown_script_test.go
  imagetest/test_suites/metadata/startup_script_test.go
Labels: size/L, lgtm, approved

#1026 Add LSSD case for hotattach
  imagetest/test_suites/hotattach/hot_attach_test.go
  imagetest/test_suites/hotattach/setup.go
Labels: size/L, lgtm, approved

#1027 Add recently used info from PD to storageperf
  imagetest/test_suites/README.md
Labels: lgtm, approved, size/S

#1030 Remove quintonamore from OWNERS
  OWNERS
Labels: size/XS, lgtm, approved

#1029 Add LSSD support and cases to storageperf
  imagetest/test_suites/storageperf/iops_read_test.go
  imagetest/test_suites/storageperf/iops_write_test.go
  imagetest/test_suites/storageperf/setup.go
  imagetest/test_suites/storageperf/storage_perf_utils.go
Labels: size/L, lgtm, approved

#1031 Autodelete all disks created for testvms
  imagetest/testworkflow.go
Labels: size/XS, lgtm, approved

#1034 Run citpresubmit in compute-image-test-pool-001
  container_images/citpresubmit/main.sh
Labels: size/XS, lgtm, approved

#1035 Run hotattach on whatever machine type the rest of the suite is run on
  imagetest/test_suites/hotattach/setup.go
Labels: size/XS, lgtm, approved

#1033 Add C4 performance and shapevalidation
  imagetest/test_suites/networkperf/setup.go
  imagetest/test_suites/networkperf/targets/default_targets.txt
  imagetest/test_suites/networkperf/targets/tier1_targets.txt
  imagetest/test_suites/shapevalidation/setup.go
  imagetest/test_suites/shapevalidation/shapevalidation_test.go
  imagetest/test_suites/storageperf/setup.go
  imagetest/test_suites/storageperf/storage_perf_utils.go
Labels: size/L, lgtm, approved

#1036 Add n4 performance testing and shape validation
  imagetest/test_suites/networkperf/setup.go
  imagetest/test_suites/networkperf/targets/default_targets.txt
  imagetest/test_suites/shapevalidation/setup.go
  imagetest/test_suites/storageperf/setup.go
  imagetest/test_suites/storageperf/storage_perf_utils.go
Labels: lgtm, approved, size/M

#1037 Update usage of CIT in concourse pipelines
  concourse/pipelines/guest-package-build.jsonnet
  concourse/pipelines/linux-image-build.jsonnet
  concourse/pipelines/partner-image-validations.jsonnet
  concourse/tasks/image-test-args.yaml
Labels: lgtm, approved, size/M

#1040 Fix issues with gen 4 networkperf testing
  imagetest/fixtures.go
  imagetest/test_suites/networkperf/setup.go
Labels: lgtm, approved, size/M

#1041 Specify boot disk type for storageperf test cases
  imagetest/test_suites/storageperf/setup.go
Labels: lgtm, approved, size/M

#1043 Pipe GCEGuestAgent logs on windows to Format-List to force line wrapping
  imagetest/test_suites/guestagent/telemetry_test.go
Labels: lgtm, approved, size/S

#1024 Remove google-cloud-sdk as a substitute for google-cloud-cli
  imagetest/test_suites/packagevalidation/package_test.go
Labels: size/XS, lgtm, approved

#1038 Test Server-Gui-Shell installation state
  imagetest/test_suites/packagevalidation/setup.go
  imagetest/test_suites/packagevalidation/windows_version_test.go
Labels: lgtm, approved, size/S

#1032 Switch disk types to hyperdisk extreme for machine types that don't support PD
  imagetest/testworkflow.go
Labels: lgtm, approved, size/S

#1046 Switch compute-image-test-pool-001 back to gcp-guest in concourse pipelines
  concourse/pipelines/guest-package-build.jsonnet
  concourse/tasks/image-test-args.yaml
Labels: size/XS, lgtm, approved

#1045 Test gcesysprep
  imagetest/test_suites/packagevalidation/gce_sysprep_test.go
  imagetest/test_suites/packagevalidation/setup.go
Labels: size/L, lgtm, approved

#1039 Fix guest agent package name on windows
  imagetest/test_suites/metadata/shutdown_script_test.go
  imagetest/test_suites/metadata/startup_script_test.go
Labels: lgtm, approved, size/S
