Repository GoogleCloudPlatform/guest-test-infra, pull requests merged in 2024-03, with the labels that each got.

#1091 Send daisy logs to GCS
  imagetest/testworkflow.go
Labels: size/XS, lgtm, approved

#1092 Revert license activation check changes in #1060
  imagetest/test_suites/licensevalidation/license_test.go
Labels: lgtm, approved, size/S

#1090 Improve suspend testing reliability
  imagetest/cmd/wrapper/main.go
  imagetest/fixtures.go
  imagetest/fixtures_test.go
  imagetest/go.mod
  imagetest/go.sum
  imagetest/test_suites/imageboot/setup.go
  imagetest/test_suites/imageboot/suspend_resume_test.go
Labels: size/L, lgtm, approved

#1094 Expect google windows-internal licenses for windows bios images
  imagetest/test_suites/licensevalidation/setup.go
Labels: size/XS, lgtm, approved

#1095 Fix check for ubuntu 1804 in imageboot
  imagetest/test_suites/imageboot/setup.go
Labels: size/XS, lgtm, approved

#1096 Test suspend on suse images
  imagetest/test_suites/imageboot/setup.go
Labels: size/XS, lgtm, approved

#1097 add set_exit_status flag
  imagetest/cmd/manager/main.go
Labels: size/XS, lgtm, approved

#1098 oslogin: retry for a minute when creating ssh client
  imagetest/test_suites/oslogin/ssh_test.go
Labels: lgtm, approved, size/M

#1099 Correct parentheses around exit status logic
  imagetest/cmd/manager/main.go
Labels: size/XS, lgtm, approved

#1100 metadata utils: query repo and use repo for dnf and yum ops
  imagetest/test_suites/metadata/metadata_utils.go
Labels: lgtm, approved, size/M

#1101 metadata: fix repo argument for yum and dnf
  imagetest/test_suites/metadata/metadata_utils.go
Labels: lgtm, approved, size/S

#1102 metadata: don't rely on yum's database cache
  imagetest/test_suites/metadata/metadata_utils.go
Labels: size/XS, lgtm, approved

#1103 Retry winrm client connections until the test times out or the connection succeeds
  imagetest/test_suites/winrm/winrm_test.go
Labels: lgtm, approved, size/S

#1104 metadata: do actually disable other repos
  imagetest/test_suites/metadata/metadata_utils.go
Labels: size/XS, lgtm, approved

#1108 metadata: fix the dnf and yum repo restriction
  imagetest/test_suites/metadata/metadata_utils.go
  imagetest/test_suites/metadata/shutdown_script_test.go
  imagetest/test_suites/metadata/startup_script_test.go
Labels: lgtm, approved, size/M

#1107 Test that images can function as L3 and L7 load balancer backends
  imagetest/cmd/manager/main.go
  imagetest/fixtures.go
  imagetest/test_suites/loadbalancer/loadbalancer_test.go
  imagetest/test_suites/loadbalancer/setup.go
Labels: lgtm, approved, size/XL

#1093 Test SEV live migration
  imagetest/test_suites/cvm/cvm_test.go
  imagetest/test_suites/cvm/setup.go
Labels: lgtm, approved, size/M

#1111 remove the redhat c3 metal stuff from concourse
  concourse/pipelines/linux-image-build.jsonnet
Labels: lgtm, approved, size/S

#1110 Fix windows bios images license test failures
  imagetest/test_suites/licensevalidation/license_test.go
  imagetest/test_suites/licensevalidation/setup.go
Labels: size/XS, lgtm, approved

#1109 Skip MTU test on old sysprep versions
  imagetest/test_suites/network/mtu_test.go
Labels: lgtm, approved, size/S

#1113 Refactor imageboot and test power plan settings on windows.
  concourse/pipelines/guest-package-build.jsonnet
  imagetest/cmd/manager/main.go
  imagetest/test_suites/imageboot/setup.go
  imagetest/test_suites/livemigrate/live_migrate_test.go
  imagetest/test_suites/livemigrate/setup.go
  imagetest/test_suites/suspendresume/setup.go
  imagetest/test_suites/suspendresume/suspend_resume_test.go
Labels: size/L, lgtm, approved

#1112 Update package_test.go to skip COS in TestStandardPrograms
  imagetest/test_suites/packagevalidation/package_test.go
Labels: size/XS, lgtm, approved, ok-to-test

#1114 Wait for zypper lock for a long time
  imagetest/test_suites/metadata/metadata_utils.go
  imagetest/test_suites/metadata/shutdown_script_test.go
  imagetest/test_suites/metadata/startup_script_test.go
Labels: lgtm, approved, size/M

#949 Enable mdsmtls test suite, skip tests if the MDS doesn't offer tls creds
  imagetest/cmd/manager/main.go
  imagetest/test_suites/mdsmtls/mds_mtls_test.go
  imagetest/test_suites/mdsmtls/setup.go
Labels: size/L, lgtm, approved

#1115 Skip the agent-reinstall section of startup script test on SUSE
  imagetest/test_suites/metadata/startup_script_test.go
Labels: size/XS, lgtm, approved

#1117 Mark tests not skipped or run as disabled
  imagetest/junit.go
  imagetest/test_suites/metadata/shutdown_script_test.go
  imagetest/testworkflow.go
Labels: lgtm, approved, size/M

#1116 Move imagetesttask to common lib and enable CIT for windows
  concourse/pipelines/linux-image-build.jsonnet
  concourse/pipelines/partner-image-validations.jsonnet
  concourse/pipelines/windows-image-build-mbr.jsonnet
  concourse/pipelines/windows-image-build-staging.jsonnet
  concourse/pipelines/windows-image-build-standard.jsonnet
  concourse/pipelines/windows-image-build.jsonnet
  concourse/templates/common.libsonnet
Labels: size/L, lgtm, approved

#1118 Correct bct-prod to bct-prod-images
  concourse/pipelines/windows-image-build.jsonnet
Labels: size/XS, lgtm, approved
