Repository GoogleCloudPlatform/guest-test-infra, pull requests merged in 2024-10, with the labels that each got.

#1245 Bump package build and container build's golang version
  container_images/gointegtest/common.sh
  packagebuild/common.sh
Labels: size/XS, lgtm, approved

#1246 Comment out metrics reporting from image and package build
  concourse/pipelines/guest-package-build.jsonnet
  concourse/pipelines/linux-image-build.jsonnet
  concourse/pipelines/windows-image-build.jsonnet
Labels: size/L, lgtm, approved

#1247 Add arm64 package build for apt-transport
  concourse/pipelines/guest-package-build.jsonnet
Labels: size/XS, lgtm, approved

#1248 update go containers to also install protobuffer tools.
  container_images/gobuild/Dockerfile
  container_images/gocheck/Dockerfile
  container_images/gotest/Dockerfile
Labels: size/XS, lgtm, approved

#1249 Revert "update go containers to also install protobuffer tools. (#1248)"
  container_images/gobuild/Dockerfile
  container_images/gocheck/Dockerfile
  container_images/gotest/Dockerfile
Labels: size/XS, lgtm, approved

#1251 Update OWNERS
  OWNERS
Labels: size/XS, lgtm, approved

#1250 Test oslogin concourse
  concourse/pipelines/linux-image-build.jsonnet
Labels: lgtm, approved, size/S

#1252 container-images: install protobuffer tooling.
  container_images/gobuild/Dockerfile
  container_images/gocheck/Dockerfile
  container_images/gotest/Dockerfile
Labels: lgtm, approved, size/S

#1254 package build: pass in extra git ref
  packagebuild/workflows/build_deb11.wf.json
  packagebuild/workflows/build_deb11_arm64.wf.json
  packagebuild/workflows/build_deb12.wf.json
  packagebuild/workflows/build_deb12_arm64.wf.json
  packagebuild/workflows/build_el6.wf.json
  packagebuild/workflows/build_el8.wf.json
  packagebuild/workflows/build_el8_arm64.wf.json
  packagebuild/workflows/build_el9.wf.json
  packagebuild/workflows/build_el9_arm64.wf.json
  packagebuild/workflows/build_goo.wf.json
  packagebuild/workflows/build_package.wf.json
Labels: lgtm, approved, size/M

#1256 Exclude acceleratorconfig test from package builds
  concourse/pipelines/guest-package-build.jsonnet
Labels: size/XS, lgtm, approved

#1253 package build: add extra source to guest-agent build pipeline
  concourse/pipelines/guest-package-build.jsonnet
Labels: lgtm, approved, size/M

#1257 All byol publishes after prod release
  concourse/pipelines/windows-image-build.jsonnet
Labels: size/XS, lgtm, approved

#1258 package build: selectively pass daisy args & pipeline shift
  concourse/pipelines/guest-package-build.jsonnet
Labels: lgtm, approved, size/S

#1259 Switch CIT package tests to explicit include list
  concourse/pipelines/guest-package-build.jsonnet
Labels: size/XS, lgtm, approved

#1261 Updating pass field so it triggers from the prod publish
  concourse/pipelines/windows-image-build.jsonnet
Labels: size/XS, lgtm, approved

#1263 rpm build: build package with extra source
  packagebuild/common.sh
  packagebuild/daisy_startupscript_rpm.sh
Labels: lgtm, approved, size/M

#1264 Add extra repo support in googet packaging startup script
  packagebuild/daisy_startupscript_goo.sh
  packagebuild/test_build.sh
Labels: lgtm, approved, size/S

#1260 Build and test derivative images for guest-configs
  concourse/pipelines/guest-package-build.jsonnet
Labels: size/L, lgtm, approved

#1267 Fix guest environment build pipeline failures
  concourse/pipelines/guest-package-build.jsonnet
Labels: lgtm, approved, size/S

#1268 rpmbuild: fix extra rpmbuild flags variable name
  packagebuild/daisy_startupscript_rpm.sh
Labels: size/XS, lgtm, approved

#1270 rpm build: rpmbuild seems to dislike the single quotes
  packagebuild/daisy_startupscript_rpm.sh
Labels: size/XS, lgtm, approved

#1262 Modify debian startupscripts to utilize extra_repo if it exists
  packagebuild/daisy_startupscript_deb.sh
Labels: lgtm, approved, size/S

#1272 rpmbuild: properly set root dir and enable tracing
  packagebuild/daisy_startupscript_rpm.sh
Labels: size/XS, lgtm, approved

#1274 rpm build: install make and add arm64 support
  packagebuild/common.sh
  packagebuild/daisy_startupscript_rpm.sh
Labels: lgtm, approved, size/S

#1275 Install protoc go extensions
  packagebuild/daisy_startupscript_deb.sh
Labels: size/XS, lgtm, approved

#1269 Fix buildid name generation
  concourse/pipelines/guest-package-build.jsonnet
Labels: size/XS, lgtm, approved

#1276 package build: fix generate-build-id
  concourse/pipelines/guest-package-build.jsonnet
Labels: size/XS, lgtm, approved

#1277 Fix derivative image naming for rocky-linux-9 in guest-configs
  concourse/pipelines/guest-package-build.jsonnet
Labels: size/XS, lgtm, approved

#1278 package build: fix rocky vs rock linux typo
  concourse/pipelines/guest-package-build.jsonnet
Labels: size/XS, lgtm, approved

#1279 Fix more typos in build_guest_configs
  concourse/pipelines/guest-package-build.jsonnet
Labels: size/XS, lgtm, approved

#1265 Update linux image build test filter, switch partner images to filter
  concourse/pipelines/linux-image-build.jsonnet
  concourse/pipelines/partner-image-validations.jsonnet
Labels: size/XS, lgtm, approved

#1281 Skip MDS routes test
  concourse/pipelines/guest-package-build.jsonnet
Labels: size/XS, lgtm, approved

#1282 Enable metrics, remove EOL workers, windows builds to daily
  concourse/pipelines/debian-worker-image-build.yaml
  concourse/pipelines/linux-image-build.jsonnet
  concourse/pipelines/windows-image-build.jsonnet
Labels: lgtm, approved, size/XL

#1283 Re-enable metrics for package builds
  concourse/pipelines/guest-package-build.jsonnet
Labels: lgtm, approved, size/S

#1284 COS 101 is EOL. Move other COS package tests to Debian 12 worker.
  concourse/pipelines/guest-package-build.jsonnet
Labels: lgtm, approved, size/S
