Repository GoogleCloudPlatform/guest-test-infra, pull requests merged in 2024-04, with the labels that each got.

#1123 Update setup.go to skip alias tests for COS images
  imagetest/test_suites/network/setup.go
Labels: size/XS, lgtm, approved, ok-to-test

#1122 Update package_test.go to include COS package validation
  imagetest/test_suites/packagevalidation/package_test.go
Labels: lgtm, approved, size/M, ok-to-test

#1124 On EL7, use an extra VM to test gvnic instead of the multinic vm
  imagetest/test_suites/network/setup.go
Labels: lgtm, approved, size/S

#1125 Enforce a lack of dashes in testworkflow vm names.
  imagetest/fixtures.go
  imagetest/test_suites/cvm/setup.go
  imagetest/test_suites/disk/setup.go
  imagetest/test_suites/guestagent/setup.go
  imagetest/test_suites/hotattach/setup.go
  imagetest/test_suites/metadata/setup.go
  imagetest/test_suites/network/setup.go
  imagetest/test_suites/networkperf/setup.go
  imagetest/test_suites/packagevalidation/setup.go
  imagetest/test_suites/security/setup.go
  imagetest/test_suites/shapevalidation/setup.go
  imagetest/test_suites/sql/setup.go
  imagetest/test_suites/ssh/setup.go
  imagetest/test_suites/storageperf/setup.go
  imagetest/test_suites/storageperf/storage_perf_utils.go
  imagetest/testworkflow.go
Labels: lgtm, approved, size/M

#1126 Upgrade go sdk version to latest.
  container_images/gointegtest/common.sh
  packagebuild/common.sh
Labels: size/XS, lgtm, approved

#1121 Delete shutdown script time tests
  imagetest/test_suites/metadata/setup.go
  imagetest/test_suites/metadata/shutdown_script_test.go
Labels: lgtm, approved, size/M

#1128 Disable registry package build call
  concourse/pipelines/guest-package-build.jsonnet
Labels: size/L, lgtm, approved

#1127 Fix GetRealVMName call in ssh suite
  imagetest/test_suites/ssh/host_key_test.go
  imagetest/test_suites/ssh/image_ssh_test.go
Labels: size/XS, lgtm, approved

#1130 Disable CIT in windows piplines
  concourse/pipelines/windows-image-build-staging.jsonnet
  concourse/pipelines/windows-image-build-standard.jsonnet
  concourse/pipelines/windows-image-build.jsonnet
Labels: size/XS, lgtm, approved

#1132 Disable dhcp test on debian 12
  imagetest/test_suites/network/dhcp_test.go
Labels: size/XS, lgtm, approved

#1133 package build: disable debian-10 backport repos
  packagebuild/daisy_startupscript_deb.sh
Labels: size/XS, lgtm, approved

#1131 Prepare CIT for the move to a new repository
  container_images/cleanerupper/go-cleanerupper/go.mod
  imagetest/cleanerupper/cleanerupper.go
  imagetest/cleanerupper/cleanerupper_test.go
  imagetest/file
  imagetest/go.mod
  imagetest/go.sum
  imagetest/junit.go
  imagetest/junit_test.go
  imagetest/test_suites/network/multinic_minimal_network_test.go
  imagetest/test_suites/network/setup.go
  imagetest/testworkflow.go
Labels: lgtm, approved, size/XXL

#1129 Use single quote string in windows password test
  imagetest/test_suites/guestagent/windows_password_test.go
Labels: size/XS, lgtm, approved

#1137 Rename ping marker file for windows images
  imagetest/test_suites/network/multinic_minimal_network_test.go
Labels: size/XS, lgtm, approved

#1138 package build(goo): disable debian-10 backport repos
  packagebuild/daisy_startupscript_goo.sh
Labels: size/XS, lgtm, approved

#1139 Add Debian 12 worker builds.
  concourse/pipelines/debian-worker-image-build.yaml
Labels: size/L, lgtm, approved

#1140 Don't fail metadata tests unless the agent fails to reinstall
  imagetest/test_suites/metadata/metadata_utils.go
  imagetest/test_suites/metadata/shutdown_script_test.go
  imagetest/test_suites/metadata/startup_script_test.go
Labels: lgtm, approved, size/M

#1136 Make CIT's post-testworkflow cleanerupper more aggressive
  imagetest/cleanerupper/cleanerupper.go
  imagetest/cleanerupper/cleanerupper_test.go
Labels: lgtm, approved, size/S

#1141 Wait for ping on first boot instead of second
  imagetest/test_suites/network/multinic_minimal_network_test.go
Labels: lgtm, approved, size/M

#1147 Fix issues with CIT in windows
  imagetest/test_suites/guestagent/windows_password_test.go
  imagetest/test_suites/packagevalidation/windows_version_test.go
  imagetest/test_suites/security/image_security_test.go
  imagetest/test_suites/winrm/setup.go
  imagetest/utils/test_utils.go
Labels: size/L, lgtm, approved

#1148 Allow 14 char passwords and use one in winrm
  imagetest/test_suites/winrm/setup.go
  imagetest/utils/test_utils.go
Labels: size/XS, lgtm, approved

#1146 Revert "Disable CIT in windows piplines (#1130)"
  concourse/pipelines/windows-image-build-staging.jsonnet
  concourse/pipelines/windows-image-build-standard.jsonnet
  concourse/pipelines/windows-image-build.jsonnet
Labels: size/XS, lgtm, approved

#1150 Don't accept envoy proxy error messages from load balancer
  imagetest/test_suites/loadbalancer/loadbalancer_test.go
Labels: size/XS, lgtm, approved

#1149 Revert "Disable registry package build call"
  concourse/pipelines/guest-package-build.jsonnet
Labels: size/L, lgtm, approved

#1151 AR additional package builds
  concourse/pipelines/guest-package-build.jsonnet
Labels: lgtm, approved, size/M
