Repository GoogleCloudPlatform/guest-test-infra, pull requests merged in 2024-02, with the labels that each got.

#1049 Adding additional windows builds
  concourse/pipelines/windows-image-build-staging.jsonnet
  concourse/pipelines/windows-image-build-standard.jsonnet
  concourse/pipelines/windows-image-build.jsonnet
Labels: lgtm, approved, size/M

#1050 Add 4 more users for each OSLogin 2FA SSH test
  imagetest/test_suites/oslogin/README.md
  imagetest/test_suites/oslogin/setup.go
  imagetest/test_suites/oslogin/ssh_test.go
Labels: size/L, lgtm, approved

#1048 Clean test workflows even on failure
  imagetest/testworkflow.go
Labels: lgtm, approved, size/S

#1053 Move derivative image build back to gcp-guest
  concourse/pipelines/guest-package-build.jsonnet
Labels: size/XS, lgtm, approved

#1054 Permanently disable DHCP tests for debian-10 and debian-11
  imagetest/test_suites/network/dhcp_test.go
Labels: size/XS, lgtm, approved

#1051 Test setting subnetwork region and take base name of region url
  imagetest/fixtures_test.go
  imagetest/go.mod
  imagetest/go.sum
  imagetest/test_suites/networkperf/setup.go
Labels: lgtm, approved, size/S

#1056 Fix gocheck
  imagetest/utils/test_utils.go
Labels: size/XS, lgtm, approved

#1052 Refactoring disk tests to work on COS
  imagetest/cmd/wrapper/main.go
  imagetest/test_suites/disk/disk_readwrite_test.go
  imagetest/test_suites/disk/disk_resize_test.go
Labels: lgtm, approved, size/S, ok-to-test

#1055 Test that google_osconfig_agent is disabled
  imagetest/test_suites/packagevalidation/gce_sysprep_test.go
Labels: size/XS, lgtm, approved

#1060 Refactor licensevalidation suite.
  imagetest/test_suites/licensevalidation/license_test.go
  imagetest/test_suites/licensevalidation/linux_license_test.go
  imagetest/test_suites/licensevalidation/setup.go
Labels: size/L, lgtm, approved

#1061 Account for rhel-sap-byos and architecture suffixes in licensevalidation
  imagetest/test_suites/licensevalidation/setup.go
Labels: lgtm, approved, size/S

#1058 Add better support for COS, SLES, and Ubuntu in the network suite.
  imagetest/test_suites/network/alias_ip_test.go
  imagetest/test_suites/network/setup.go
Labels: size/XS, lgtm, approved

#1063 Integrate rhel and rhel-byos licensevalidation rules, use image name rather than family name
  imagetest/test_suites/licensevalidation/setup.go
Labels: size/XS, lgtm, approved

#1064 Disable license testing on linux again
  imagetest/test_suites/licensevalidation/setup.go
Labels: lgtm, approved, size/M

#1057 Exclude 4th gen machine type testing from release pipelines
  concourse/pipelines/linux-image-build.jsonnet
  concourse/pipelines/windows-image-build-standard.jsonnet
Labels: size/XS, lgtm, approved

#1068 Run linux image test pipelines in us-central1-b
  concourse/pipelines/linux-image-build.jsonnet
Labels: size/XS, lgtm, approved

#1069 Take base name of region in all cases for networkperf
  imagetest/test_suites/networkperf/setup.go
Labels: size/XS, lgtm, approved

#1070 Add winrm test suite
  imagetest/cmd/manager/main.go
  imagetest/test_suites/winrm/setup.go
  imagetest/test_suites/winrm/winrm_test.go
Labels: size/L, lgtm, approved

#1059 Check IP configuration in network test suite
  imagetest/test_suites/network/setup.go
  imagetest/test_suites/network/static_ip_test.go
Labels: size/L, lgtm, approved

#1066 Fix and enable linux license validation, exclude from guest package integration test pipelines
  concourse/pipelines/guest-package-build.jsonnet
  imagetest/test_suites/licensevalidation/setup.go
Labels: lgtm, approved, size/M

#1071 Avoid line breaks when getting agent output on windows
  imagetest/test_suites/guestagent/telemetry_test.go
Labels: size/XS, lgtm, approved

#1072 Adding RHEL9 C3M to build workflow
  concourse/pipelines/linux-image-build.jsonnet
Labels: size/XS, lgtm, approved

#1073 Add rhel c3m image support in licensevalidation
  imagetest/test_suites/licensevalidation/setup.go
Labels: size/XS, lgtm, approved

#1075 Add rhel c3m image group that skips CIT
  concourse/pipelines/linux-image-build.jsonnet
Labels: lgtm, approved, size/S

#1065 Artifact Registry task template
  concourse/pipelines/guest-package-build.jsonnet
Labels: lgtm, approved, size/M

#1076 Stop checking for known issues in CIT
  imagetest/test_suites/metadata/shutdown_script_test.go
  imagetest/test_suites/packagevalidation/gce_sysprep_test.go
  imagetest/test_suites/packagevalidation/package_test.go
Labels: lgtm, approved, size/M

#1078 Fix exclude name for licensevalidation
  concourse/pipelines/guest-package-build.jsonnet
Labels: size/XS, lgtm, approved

#1077 Retry setting guest attributes in the cit manager up to three times
  imagetest/cmd/wrapper/main.go
Labels: lgtm, approved, size/S

#1080 Switch to C3D for X86_64 disk naming tests
  imagetest/test_suites/disk/setup.go
Labels: size/XS, lgtm, approved

#1081 Pass timeout into the VM through metadata…
  imagetest/cmd/wrapper/main.go
  imagetest/test_suites/network/multinic_minimal_network_test.go
  imagetest/testworkflow.go
Labels: lgtm, approved, size/M

#1082 Retry partner image validation three times
  concourse/pipelines/partner-image-validations.jsonnet
Labels: size/XS, lgtm, approved

#1083 Artifact Registry basic testing
  concourse/pipelines/artifact-releaser-test.jsonnet
Labels: lgtm, approved, size/S

#1084 Add livemigrate and suspend/resume testing to imageboot suite
  imagetest/test_suites/imageboot/live_migrate_test.go
  imagetest/test_suites/imageboot/setup.go
  imagetest/test_suites/imageboot/suspend_resume_test.go
Labels: size/L, lgtm, approved

#1086 Fix licensevalidation exclusion
  concourse/pipelines/guest-package-build.jsonnet
Labels: size/XS, lgtm, approved

#1085 Improve reliability of suspend/resume and livemigrate testing
  imagetest/test_suites/imageboot/live_migrate_test.go
  imagetest/test_suites/imageboot/suspend_resume_test.go
Labels: size/XS, lgtm, approved

#1087 Mark test start on windows correctly
  imagetest/test_suites/imageboot/live_migrate_test.go
  imagetest/test_suites/imageboot/suspend_resume_test.go
Labels: size/XS, lgtm, approved

#1089 Remove package version tasks for yum-plugin-artifact-registry
  concourse/pipelines/guest-package-build.jsonnet
Labels: lgtm, approved, size/S
