Repository GoogleCloudPlatform/guest-test-infra, pull requests merged in 2025-07, with the labels that each got.

#1414 Scope down oslogin arm image tests to deb13
  concourse/pipelines/guest-package-dev-build.jsonnet
Labels: size/XS, lgtm, approved

#1415 For the dev pipeline decrease the timeout and increase parallel
  concourse/pipelines/linux-image-build-dev.jsonnet
Labels: size/XS, lgtm, approved

#1416 Don't retry CIT
  concourse/pipelines/linux-image-build-dev.jsonnet
Labels: size/XS, lgtm, approved

#1420 Drop guestconfigs tests from Debian13 test build
  concourse/pipelines/guest-package-dev-build.jsonnet
Labels: lgtm, approved, size/M

#1421 Add centos-stream-9 to guest-agent package build/test pipeline
  concourse/pipelines/guest-package-build.jsonnet
Labels: size/XS, lgtm, approved

#1425 add el10 to dev package build pipeline and rename el10 x86 images
  concourse/pipelines/guest-package-dev-build.jsonnet
  concourse/pipelines/linux-image-build-dev.jsonnet
Labels: lgtm, approved, size/M

#1428 Revert "Temporarily disable a3u CIT tests in image build"
  concourse/pipelines/accelerator-image-build.jsonnet
Labels: lgtm, approved, size/M

#1427 Add windows image build task, not adding to list of images to test yet.
  concourse/pipelines/guest-package-build.jsonnet
Labels: lgtm, approved, size/M

#1430 User correct worker image and machine type for ubuntu arm images
  concourse/pipelines/guest-package-build.jsonnet
Labels: size/XS, lgtm, approved

#1432 add missing el10 dev package builds
  concourse/pipelines/guest-package-dev-build.jsonnet
  packagebuild/workflows/build_el10.wf.json
  packagebuild/workflows/build_el10_arm64.wf.json
Labels: lgtm, approved, size/S

#1433 Add sles-15 to image derivation
  concourse/pipelines/guest-package-build.jsonnet
Labels: size/XS, lgtm, approved

#1434 Update rhel package build script
  packagebuild/daisy_startupscript_rpm.sh
Labels: size/XS, lgtm, approved

#1435 Fix typo in package name for el10 guest-configs
  concourse/pipelines/guest-package-dev-build.jsonnet
Labels: size/XS, lgtm, approved

#1437 Add all built images to test list
  concourse/pipelines/guest-package-build.jsonnet
Labels: lgtm, approved, size/M

#1436 Use Debian 12 worker in Deb13/RHEL10 package build
  concourse/pipelines/guest-package-dev-build.jsonnet
Labels: size/XS, lgtm, approved

#1439 Update pipelines to use new guest package builder project.
  concourse/pipelines/guest-package-build.jsonnet
  concourse/pipelines/guest-package-dev-build.jsonnet
Labels: lgtm, approved, size/XL

#1441 Update source image to use in package build workflow
  packagebuild/workflows/build_goo.wf.json
Labels: size/XS, lgtm, approved

#1444 temporarily modify rpm package build script to source the google cloud sdk to unblock el10 builds
  packagebuild/daisy_startupscript_rpm.sh
Labels: lgtm, approved, size/S

#1445 disable the derivative image and cit tests for oslogin package builds to unblock el10 builds
  concourse/pipelines/guest-package-dev-build.jsonnet
Labels: size/L, lgtm, approved

#1446 Increase timeout to 45m for guest agent builds
  concourse/pipelines/guest-package-build.jsonnet
Labels: size/XS, lgtm, approved

#1447 temporarily disable trixie derivative images in dev package build pipeline for oslogin
  concourse/pipelines/guest-package-dev-build.jsonnet
Labels: lgtm, approved, size/M

#1448 Stop building on Debian 11 for guest configs, reuse Debian 12's instead
  concourse/pipelines/guest-package-build.jsonnet
Labels: lgtm, approved, size/S
