Repository GoogleCloudPlatform/guest-test-infra, pull requests merged in 2025-01, with the labels that each got.

#1325 Update A3Ultra reservation name
  concourse/pipelines/linux-image-build.jsonnet
Labels: size/XS, lgtm, approved

#1326 Update go-containerregistry version
  container_images/registry-image-forked/check_test.go
  container_images/registry-image-forked/commands/check.go
  container_images/registry-image-forked/go.mod
  container_images/registry-image-forked/in_test.go
  container_images/registry-image-forked/out_test.go
  container_images/registry-image-forked/types.go
Labels: size/L, lgtm, approved

#1327 Update go-containerregistry sum
  container_images/registry-image-forked/go.sum
Labels: size/XS, lgtm, approved

#1328 Update Go deps for registry-image-forked
  container_images/registry-image-forked/go.mod
  container_images/registry-image-forked/go.sum
Labels: lgtm, approved, size/XXL

#1329 Update dependencies
  container_images/registry-image-forked/go.mod
  container_images/registry-image-forked/go.sum
Labels: lgtm, approved, size/XXL

#1330 Update windows staging pipeline to use forked registry image
  concourse/pipelines/windows-image-build-staging.jsonnet
Labels: lgtm, approved, size/S

#1324 Add rocky linux accelerator images with nvidia 550 to the dev pipeline
  concourse/pipelines/linux-image-build-dev.jsonnet
  concourse/pipelines/linux-image-build.jsonnet
Labels: lgtm, approved, size/M

#1334 Run accelerator tests on the accelerator images in -dev
  concourse/pipelines/linux-image-build-dev.jsonnet
Labels: lgtm, approved, size/S

#1335 Add public image tags to containers
  concourse/pipelines/container-build.jsonnet
Labels: size/XS, lgtm, approved

#1333 Cleanup owners file.
  OWNERS
Labels: size/XS, lgtm, approved

#1336 Add public image tags to container builds
  concourse/pipelines/container-build.jsonnet
Labels: size/XS, lgtm, approved
