Repository GoogleCloudPlatform/guest-test-infra, pull requests merged in 2025-04, with the labels that each got.

#1362 Remove prepublish tests from accelerator pipeline
  concourse/pipelines/accelerator-image-build.jsonnet
Labels: lgtm, approved, size/S

#1363 Stagger Accelerator CIT Test publish tasks
  concourse/pipelines/accelerator-image-build.jsonnet
Labels: lgtm, approved, size/M

#1368 Enable cos builds/tests reverted in #1357
  concourse/pipelines/guest-package-build.jsonnet
Labels: lgtm, approved, size/M

#1369 Revert "Enable cos builds/tests reverted in #1357"
  concourse/pipelines/guest-package-build.jsonnet
Labels: lgtm, approved, size/M

#1371 Enable cos builds/tests reverted in #1369
  concourse/pipelines/guest-package-build.jsonnet
Labels: lgtm, approved, size/M

#1373 COS 105 is deprecated, remove 105 and add 121
  concourse/pipelines/guest-package-build.jsonnet
Labels: lgtm, approved, size/S

#1374 Change machine type to use c4a for arm builds
  concourse/pipelines/guest-package-build.jsonnet
Labels: lgtm, approved, size/S

#1375 Change machine type to use c4a for arm builds
  concourse/pipelines/guest-package-build.jsonnet
Labels: size/XS, lgtm, approved

#1372 rhel 10 package build
  concourse/pipelines/guest-package-build.jsonnet
Labels: size/L, lgtm, approved

#1376 Add build_el10 wf files
  packagebuild/workflows/build_el10.wf.json
  packagebuild/workflows/build_el10_arm64.wf.json
Labels: size/L, lgtm, approved

#1377 fix typo in images list for rhel-10
  concourse/pipelines/guest-package-build.jsonnet
Labels: size/XS, lgtm, approved

#1379 t2a -> c4a for arm builds
  concourse/pipelines/guest-package-build.jsonnet
  packagebuild/workflows/build_deb11_arm64.wf.json
  packagebuild/workflows/build_deb12_arm64.wf.json
  packagebuild/workflows/build_el10_arm64.wf.json
  packagebuild/workflows/build_el8_arm64.wf.json
  packagebuild/workflows/build_el9_arm64.wf.json
Labels: lgtm, approved, size/M

#1380 use hyperdisk-balanced instead of pd-ssd for package build
  concourse/pipelines/guest-package-build.jsonnet
Labels: lgtm, approved, size/S

#1381 parameterize disk_type in package build workflow
  packagebuild/workflows/build_deb11_arm64.wf.json
  packagebuild/workflows/build_deb12_arm64.wf.json
  packagebuild/workflows/build_el10_arm64.wf.json
  packagebuild/workflows/build_el8_arm64.wf.json
  packagebuild/workflows/build_el9_arm64.wf.json
  packagebuild/workflows/build_package.wf.json
Labels: lgtm, approved, size/S

#1378 Update guest package build pipeline for Debian 13
  concourse/pipelines/guest-package-build.jsonnet
  packagebuild/workflows/build_deb13.wf.json
Labels: size/L, lgtm, approved

#1382 Update repo reference in package upload
  concourse/pipelines/guest-package-build.jsonnet
Labels: size/XS, lgtm, approved

#1383 set disk type for rhel-10 arm package build to hyperdisk-balanced
  concourse/pipelines/guest-package-build.jsonnet
Labels: size/XS, lgtm, approved

#1384 Disable deb13 and rhel10 builds for guest-agent
  concourse/pipelines/guest-package-build.jsonnet
Labels: lgtm, approved, size/S
