Repository GoogleCloudPlatform/guest-test-infra, pull requests merged in 2025-02, with the labels that each got.

#1337 guest package build: force fetching tags
  concourse/pipelines/guest-package-build.jsonnet
Labels: size/XS, lgtm, approved

#1338 Adding Arnav
  OWNERS
Labels: size/XS, lgtm, approved

#1340 oslogin: add stable build pipeline
  concourse/pipelines/guest-package-build.jsonnet
Labels: lgtm, approved, size/M

#1341 oslogin: shorten stable so image names are under 64 chars
  concourse/pipelines/guest-package-build.jsonnet
Labels: lgtm, approved, size/S

#1342 Removing SQL 2022 Express
  concourse/pipelines/windows-image-build.jsonnet
Labels: size/XS, lgtm, approved

#1343 Use the a3 ultra machine shape by default
  concourse/pipelines/linux-image-build.jsonnet
Labels: size/XS, lgtm, approved

#1344 Pass in europe-west1-b as the zone for accelerator builds
  concourse/pipelines/linux-image-build.jsonnet
Labels: size/XS, lgtm, approved

#1345 Pass in the acceleratortype
  concourse/pipelines/linux-image-build.jsonnet
Labels: size/XS, lgtm, approved

#1346 Update reservation name for A3 tests
  concourse/pipelines/linux-image-build-dev.jsonnet
  concourse/pipelines/linux-image-build.jsonnet
Labels: size/XS, lgtm, approved
