Repository GoogleCloudPlatform/guest-test-infra, pull requests merged in 2025-09, with the labels that each got.

#1496 Support multiple binaries from single source package
  packagebuild/daisy_startupscript_deb.sh
Labels: lgtm, approved, size/S

#1497 Use renamed variable in build script
  packagebuild/daisy_startupscript_deb.sh
Labels: size/XS, lgtm, approved

#1498 Add package upload workflow for new config package
  concourse/pipelines/guest-package-dev-build.jsonnet
Labels: lgtm, approved, size/S

#1502 add rhel 10 byos to image build pipeline
  concourse/pipelines/linux-image-build.jsonnet
Labels: size/XS, lgtm, approved

#1506 Add support to target specific Debian versions in package build
  packagebuild/daisy_startupscript_deb.sh
  packagebuild/workflows/build_deb11.wf.json
  packagebuild/workflows/build_deb11_arm64.wf.json
  packagebuild/workflows/build_deb12.wf.json
  packagebuild/workflows/build_deb12_arm64.wf.json
  packagebuild/workflows/build_deb13.wf.json
  packagebuild/workflows/build_deb13_arm64.wf.json
  packagebuild/workflows/build_package.wf.json
Labels: lgtm, approved, size/M

#1510 Add rhel10 and deb13 to pipeline
  concourse/pipelines/guest-package-build.jsonnet
Labels: lgtm, approved, size/M

#1515 Remove Debian 13 from dev image build pipeline
  concourse/pipelines/linux-image-build-dev.jsonnet
Labels: lgtm, approved, size/M

#1516 Add rhel-10-byos images
  concourse/pipelines/guest-package-build.jsonnet
Labels: lgtm, approved, size/S

#1517 Use right project for rhel-10-byos image
  concourse/pipelines/guest-package-build.jsonnet
Labels: size/XS, lgtm, approved

#1518 Add rocky and centos 10
  concourse/pipelines/guest-package-build.jsonnet
Labels: lgtm, approved, size/M

#1519 Image name should be less than 64 char
  concourse/pipelines/guest-package-build.jsonnet
Labels: size/XS, lgtm, approved

#1520 Add Windows 11 25h2
  concourse/pipelines/windows-image-build.jsonnet
Labels: lgtm, approved, size/S

#1521 Add trigger field to package build job to customize whether it triggers off of commits
  concourse/pipelines/guest-package-build.jsonnet
Labels: lgtm, approved, size/S

#1522 Revert "Add trigger field to package build job to customize whether it triggers off of commits"
  concourse/pipelines/guest-package-build.jsonnet
Labels: lgtm, approved, size/S

#1523 Revert "Revert "Add trigger field to package build job to customize whether it triggers off of commits""
  concourse/pipelines/guest-package-build.jsonnet
Labels: lgtm, approved, size/S
