Repository GoogleCloudPlatform/guest-test-infra, pull requests merged in 2025-03, with the labels that each got.

#1347 Do not try to pass in the shasum variable in media image publish jobs
  concourse/pipelines/windows-image-build.jsonnet
Labels: size/XS, lgtm, approved

#1348 Fork accelerator build into its own pipeline
  concourse/pipelines/accelerator-image-build.jsonnet
Labels: size/L, lgtm, approved

#1350 Remove accelerator builds from generic Linux pipelines
  concourse/pipelines/linux-image-build-dev.jsonnet
  concourse/pipelines/linux-image-build.jsonnet
Labels: lgtm, approved, size/M

#1352 cleanup owners file
  OWNERS
Labels: size/XS, lgtm, approved

#1354 Enable plugin manager and compat manager test suite on guest-agent
  concourse/pipelines/guest-package-build.jsonnet
Labels: size/XS, lgtm, approved

#1355 Windows 2025 IPU
  concourse/pipelines/windows-image-build.jsonnet
Labels: lgtm, approved, size/S

#1356 Update daisy.libsonnet
  concourse/templates/daisy.libsonnet
Labels: size/XS, lgtm, approved

#1357 Disable cos temporarily until package build is fixed
  concourse/pipelines/guest-package-build.jsonnet
  concourse/pipelines/windows-image-build-staging.jsonnet
Labels: lgtm, approved, size/M

#1359 Add necessary changes for building A4 with Concourse
  concourse/pipelines/accelerator-image-build.jsonnet
Labels: lgtm, approved, size/S

#1360 Fix isopath trimming for accelerator builds
  concourse/pipelines/accelerator-image-build.jsonnet
Labels: size/XS, lgtm, approved
