Repository GoogleCloudPlatform/guest-test-infra, pull requests merged in 2025-08, with the labels that each got.

#1454 Put OSLogin CIT tests in oslogin-cit project
  concourse/pipelines/guest-package-build.jsonnet
Labels: size/XS, lgtm, approved

#1455 Run agent tests in guest-package-builder project
  concourse/pipelines/guest-package-build.jsonnet
Labels: size/XS, lgtm, approved

#1456 temporarily remove centos-stream-10 derivative image builds for guest-configs and guest-agent packages in dev pipeline
  concourse/pipelines/guest-package-dev-build.jsonnet
Labels: lgtm, approved, size/M

#1458 run package build CIT tests in multiple zones
  concourse/pipelines/guest-package-build.jsonnet
Labels: size/XS, lgtm, approved

#1459 Cit package build multi zone x86
  concourse/pipelines/guest-package-build.jsonnet
Labels: size/XS, lgtm, approved

#1460 Use correct regions for T2A series
  concourse/pipelines/guest-package-build.jsonnet
Labels: size/XS, lgtm, approved

#1464 Add more zones to run tests in
  concourse/pipelines/guest-package-build.jsonnet
Labels: size/XS, lgtm, approved

#1465 Fix T2A supported zones
  concourse/pipelines/guest-package-build.jsonnet
Labels: size/XS, lgtm, approved

#1467 Start building RHEL 9.6 for SAP
  concourse/pipelines/guest-package-build.jsonnet
  concourse/pipelines/linux-image-build.jsonnet
Labels: size/XS, lgtm, approved

#1468 Use other zones before central1-a to avoid resource exhaustion
  concourse/pipelines/guest-package-build.jsonnet
Labels: size/XS, lgtm, approved

#1469 Remove rhel-9-6-sap-ha image derivation until images/family/rhel-9-6-sap-ha is available
  concourse/pipelines/guest-package-build.jsonnet
Labels: size/XS, lgtm, approved

#1471 move package builds for rpm from centos stream 10 to rhel 10
  packagebuild/workflows/build_el10.wf.json
  packagebuild/workflows/build_el10_arm64.wf.json
Labels: size/XS, lgtm, approved

#1473 Add nicsetup test suite to test pipeline
  concourse/pipelines/guest-package-build.jsonnet
Labels: size/XS, lgtm, approved

#1479 Split windows test and run on different machine type to improve test/build times
  concourse/pipelines/guest-package-build.jsonnet
Labels: lgtm, approved, size/M

#1481 Split partner images to run in parallel, add oslogin tests
  concourse/pipelines/guest-package-build.jsonnet
Labels: lgtm, approved, size/M

#1482 Add all remaining rhel-sap-ha images
  concourse/pipelines/guest-package-build.jsonnet
Labels: lgtm, approved, size/M

#1484 Add ubuntu 1604 and all sles sp images to test list
  concourse/pipelines/guest-package-build.jsonnet
Labels: lgtm, approved, size/M

#1485 Add all remaining ubuntu arm images and sles byos images
  concourse/pipelines/guest-package-build.jsonnet
Labels: lgtm, approved, size/M

#1486 add rhel and centos stream 10, and el 10 package and image prod setup
  concourse/pipelines/linux-image-build.jsonnet
Labels: size/XS, lgtm, approved

#1487 add el 10 package builds to non-dev pipeline
  concourse/pipelines/linux-image-build-dev.jsonnet
Labels: size/XS, lgtm, approved

#1489 Add sysprep pacakge to the image build
  concourse/pipelines/guest-package-build.jsonnet
Labels: lgtm, approved, size/S

#1491 Tests are extremely flaky on Rhel 8-6 remove it from the list
  concourse/pipelines/guest-package-build.jsonnet
Labels: size/XS, lgtm, approved

#1495 Add retry attempts for each test tasks
  concourse/pipelines/guest-package-build.jsonnet
Labels: size/XS, lgtm, approved
